"""add_phase10_communication_hub_tasks_and_notifications

Revision ID: 0ad5d0f1ece4
Revises: 385abc1d4309
Create Date: 2026-07-30 16:04:37.497419

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ad5d0f1ece4"
down_revision: str | Sequence[str] | None = "385abc1d4309"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PHASE10_TABLES = (
    "communication_channels",
    "conversations",
    "conversation_status_history",
    "conversation_assignments",
    "conversation_links",
    "messages",
    "message_delivery_attempts",
    "message_status_history",
    "message_attachments",
    "message_templates",
    "scheduled_messages",
    "communication_preferences",
    "communication_consents",
    "communication_suppressions",
    "inbound_webhook_events",
    "provider_status_events",
    "manual_call_logs",
    "task_records",
    "task_assignments",
    "task_status_history",
    "notifications",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communication_channels",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("provider_config_key", sa.String(length=120), nullable=True),
        sa.Column("default_sender_identity", sa.String(length=200), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("inbound_enabled", sa.Boolean(), nullable=False),
        sa.Column("outbound_enabled", sa.Boolean(), nullable=False),
        sa.Column("requires_template", sa.Boolean(), nullable=False),
        sa.Column("business_hours_restricted", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("fallback_channel_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "code IN ('internal', 'email', 'sms', 'whatsapp', 'voice_log', 'web_chat', 'manual_call')",  # noqa: E501
            name=op.f("ck_communication_channels_valid_code"),
        ),
        sa.CheckConstraint(
            "fallback_channel_id IS NULL OR fallback_channel_id != id",
            name=op.f("ck_communication_channels_valid_fallback_channel"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_channels_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["fallback_channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_communication_channels_fallback_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_channels_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communication_channels")),
        sa.UniqueConstraint("code", name=op.f("uq_communication_channels_code")),
    )
    op.create_table(
        "notifications",
        sa.Column("recipient_staff_id", sa.Uuid(), nullable=False),
        sa.Column("notification_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("record_type", sa.String(length=32), nullable=True),
        sa.Column("record_id", sa.Uuid(), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_notifications_valid_priority"),
        ),
        sa.CheckConstraint(
            "record_type IS NULL OR record_type IN ('reservation', 'order', 'lead', 'customer', 'conversation', 'task', 'inventory_item')",  # noqa: E501
            name=op.f("ck_notifications_valid_record_type"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_notifications_recipient_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_recipient_staff_id_read_at",
        "notifications",
        ["recipient_staff_id", "read_at"],
        unique=False,
    )
    op.create_index(
        "uq_notifications_dedup_key",
        "notifications",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("dedup_key IS NOT NULL"),
    )
    op.create_table(
        "task_records",
        sa.Column("task_number", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_department_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("completion_notes", sa.Text(), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("related_type", sa.String(length=32), nullable=True),
        sa.Column("related_id", sa.Uuid(), nullable=True),
        sa.Column("is_recurring_template", sa.Boolean(), nullable=False),
        sa.Column("recurrence_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parent_task_id", sa.Uuid(), nullable=True),
        sa.Column("next_occurrence_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_task_records_valid_priority"),
        ),
        sa.CheckConstraint(
            "related_type IS NULL OR related_type IN ('customer', 'lead', 'order', 'reservation', 'conversation', 'inventory_item')",  # noqa: E501
            name=op.f("ck_task_records_valid_related_type"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'reservation_followup', 'order_issue', 'lead_followup', 'inventory_alert', 'system', 'recurring')",  # noqa: E501
            name=op.f("ck_task_records_valid_source"),
        ),
        sa.CheckConstraint(
            "status != 'blocked' OR blocked_reason IS NOT NULL",
            name=op.f("ck_task_records_blocked_requires_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'blocked', 'completed', 'cancelled')",
            name=op.f("ck_task_records_valid_status"),
        ),
        sa.CheckConstraint(
            "NOT is_recurring_template OR recurrence_rule IS NOT NULL",
            name=op.f("ck_task_records_recurring_template_requires_rule"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_department_id"],
            ["departments.id"],
            name=op.f("fk_task_records_assigned_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_task_records_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["staff_users.id"],
            name=op.f("fk_task_records_completed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_task_records_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["task_records.id"],
            name=op.f("fk_task_records_parent_task_id_task_records"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_task_records_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_records")),
        sa.UniqueConstraint("task_number", name=op.f("uq_task_records_task_number")),
    )
    op.create_index(
        "ix_task_records_assigned_staff_id", "task_records", ["assigned_staff_id"], unique=False
    )
    op.create_index("ix_task_records_due_at", "task_records", ["due_at"], unique=False)
    op.create_index(
        "ix_task_records_parent_task_id", "task_records", ["parent_task_id"], unique=False
    )
    op.create_index(
        "ix_task_records_related", "task_records", ["related_type", "related_id"], unique=False
    )
    op.create_index("ix_task_records_status", "task_records", ["status"], unique=False)
    op.create_index(
        "uq_task_records_idempotency_key",
        "task_records",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "communication_consents",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("consent_type", sa.String(length=40), nullable=False),
        sa.Column("consent_given", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("consent_version", sa.String(length=40), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consent_type IN ('transactional_email', 'promotional_email', 'transactional_sms', 'promotional_sms', 'transactional_whatsapp', 'promotional_whatsapp', 'global')",  # noqa: E501
            name=op.f("ck_communication_consents_valid_consent_type"),
        ),
        sa.CheckConstraint(
            "source IN ('customer_request', 'staff_entry', 'website_form', 'implicit_transactional', 'unsubscribe_link')",  # noqa: E501
            name=op.f("ck_communication_consents_valid_source"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_communication_consents_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_communication_consents_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communication_consents")),
    )
    op.create_index(
        "ix_communication_consents_customer_id",
        "communication_consents",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "communication_preferences",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_channel_id", sa.Uuid(), nullable=True),
        sa.Column("allow_transactional_email", sa.Boolean(), nullable=False),
        sa.Column("allow_transactional_sms", sa.Boolean(), nullable=False),
        sa.Column("allow_transactional_whatsapp", sa.Boolean(), nullable=False),
        sa.Column("allow_promotional_email", sa.Boolean(), nullable=False),
        sa.Column("allow_promotional_sms", sa.Boolean(), nullable=False),
        sa.Column("allow_promotional_whatsapp", sa.Boolean(), nullable=False),
        sa.Column("do_not_contact", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("language_preference", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_preferences_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_communication_preferences_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["preferred_channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_communication_preferences_preferred_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_preferences_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communication_preferences")),
        sa.UniqueConstraint("customer_id", name=op.f("uq_communication_preferences_customer_id")),
    )
    op.create_table(
        "communication_suppressions",
        sa.Column("destination_type", sa.String(length=16), nullable=False),
        sa.Column("destination_value", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("suppressed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "destination_type IN ('email', 'phone')",
            name=op.f("ck_communication_suppressions_valid_destination_type"),
        ),
        sa.CheckConstraint(
            "reason IN ('hard_bounce', 'spam_complaint', 'invalid_destination', 'manual_block', 'customer_request', 'unsubscribed')",  # noqa: E501
            name=op.f("ck_communication_suppressions_valid_reason"),
        ),
        sa.CheckConstraint(
            "scope IN ('all', 'promotional_only')",
            name=op.f("ck_communication_suppressions_valid_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_suppressions_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_communication_suppressions_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_suppressions_lifted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_communication_suppressions_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communication_suppressions")),
    )
    op.create_index(
        "uq_communication_suppressions_active_destination",
        "communication_suppressions",
        ["destination_type", "destination_value"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "message_templates",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_template_id", sa.String(length=200), nullable=True),
        sa.Column("is_transactional", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category IN ('reservation_confirmation', 'reservation_reminder', 'reservation_cancellation', 'reservation_modification', 'waitlist_update', 'table_ready', 'order_confirmation', 'order_ready', 'order_cancellation', 'feedback_request', 'lead_follow_up', 'birthday', 'anniversary', 'general')",  # noqa: E501
            name=op.f("ck_message_templates_valid_category"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')",
            name=op.f("ck_message_templates_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_message_templates_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_message_templates_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_message_templates_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_templates")),
        sa.UniqueConstraint("code", name=op.f("uq_message_templates_code")),
    )
    op.create_index(
        "ix_message_templates_category", "message_templates", ["category"], unique=False
    )
    op.create_index(
        "ix_message_templates_channel_id", "message_templates", ["channel_id"], unique=False
    )
    op.create_table(
        "task_assignments",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("previous_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("new_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["staff_users.id"], name=op.f("fk_task_assignments_actor_id_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["new_assignee_id"],
            ["staff_users.id"],
            name=op.f("fk_task_assignments_new_assignee_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_assignee_id"],
            ["staff_users.id"],
            name=op.f("fk_task_assignments_previous_assignee_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task_records.id"], name=op.f("fk_task_assignments_task_id_task_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_assignments")),
    )
    op.create_index("ix_task_assignments_task_id", "task_assignments", ["task_id"], unique=False)
    op.create_table(
        "task_status_history",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_task_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_records.id"],
            name=op.f("fk_task_status_history_task_id_task_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_status_history")),
    )
    op.create_index(
        "ix_task_status_history_task_id", "task_status_history", ["task_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("conversation_number", sa.String(length=40), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("guest_name", sa.String(length=180), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("spam_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_conversations_valid_priority"),
        ),
        sa.CheckConstraint(
            "source IN ('inbound', 'staff_initiated', 'system_event')",
            name=op.f("ck_conversations_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'pending', 'waiting_on_customer', 'waiting_on_staff', 'snoozed', 'resolved', 'closed', 'spam')",  # noqa: E501
            name=op.f("ck_conversations_valid_status"),
        ),
        sa.CheckConstraint("unread_count >= 0", name=op.f("ck_conversations_valid_unread_count")),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_conversations_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_conversations_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_conversations_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_conversations_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_conversations_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_conversations_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "conversation_number", name=op.f("uq_conversations_conversation_number")
        ),
    )
    op.create_index(
        "ix_conversations_assigned_staff_id", "conversations", ["assigned_staff_id"], unique=False
    )
    op.create_index("ix_conversations_channel_id", "conversations", ["channel_id"], unique=False)
    op.create_index("ix_conversations_customer_id", "conversations", ["customer_id"], unique=False)
    op.create_index(
        "ix_conversations_last_activity_at", "conversations", ["last_activity_at"], unique=False
    )
    op.create_index("ix_conversations_lead_id", "conversations", ["lead_id"], unique=False)
    op.create_index("ix_conversations_status", "conversations", ["status"], unique=False)
    op.create_table(
        "conversation_assignments",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("previous_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("new_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_conversation_assignments_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_assignments_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["new_assignee_id"],
            ["staff_users.id"],
            name=op.f("fk_conversation_assignments_new_assignee_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_assignee_id"],
            ["staff_users.id"],
            name=op.f("fk_conversation_assignments_previous_assignee_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_assignments")),
    )
    op.create_index(
        "ix_conversation_assignments_conversation_id",
        "conversation_assignments",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "conversation_links",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("linked_type", sa.String(length=32), nullable=False),
        sa.Column("linked_id", sa.Uuid(), nullable=False),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unlinked_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "linked_type IN ('reservation', 'order', 'waitlist_entry', 'feedback_case')",
            name=op.f("ck_conversation_links_valid_linked_type"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_links_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_conversation_links_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["unlinked_by"],
            ["staff_users.id"],
            name=op.f("fk_conversation_links_unlinked_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_conversation_links_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_links")),
    )
    op.create_index(
        "ix_conversation_links_conversation_id",
        "conversation_links",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        "ix_conversation_links_linked",
        "conversation_links",
        ["linked_type", "linked_id"],
        unique=False,
    )
    op.create_index(
        "uq_conversation_links_active",
        "conversation_links",
        ["conversation_id", "linked_type", "linked_id"],
        unique=True,
        postgresql_where=sa.text("unlinked_at IS NULL"),
    )
    op.create_table(
        "conversation_status_history",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_conversation_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_status_history_conversation_id_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_status_history")),
    )
    op.create_index(
        "ix_conversation_status_history_conversation_id",
        "conversation_status_history",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("sender_reference", sa.String(length=200), nullable=True),
        sa.Column("recipient_reference", sa.String(length=200), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "rendered_template_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("reply_to_message_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_status", sa.String(length=32), nullable=False),
        sa.Column("failure_code", sa.String(length=120), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "delivery_status IN ('draft', 'queued', 'processing', 'sent', 'delivered', 'read', 'failed', 'cancelled', 'suppressed', 'received', 'processed', 'assigned', 'replied', 'resolved', 'spam', 'created')",  # noqa: E501
            name=op.f("ck_messages_valid_delivery_status"),
        ),
        sa.CheckConstraint(
            "direction != 'outbound' OR recipient_reference IS NOT NULL",
            name=op.f("ck_messages_outbound_requires_recipient"),
        ),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound', 'internal')",
            name=op.f("ck_messages_valid_direction"),
        ),
        sa.CheckConstraint(
            "message_type != 'internal_note' OR recipient_reference IS NULL",
            name=op.f("ck_messages_internal_note_has_no_recipient"),
        ),
        sa.CheckConstraint(
            "message_type IN ('text', 'email', 'sms', 'whatsapp', 'system_event', 'template', 'internal_note', 'attachment', 'reservation_update', 'order_update', 'feedback_request')",  # noqa: E501
            name=op.f("ck_messages_valid_message_type"),
        ),
        sa.CheckConstraint(
            "delivered_at IS NULL OR sent_at IS NULL OR delivered_at >= sent_at",
            name=op.f("ck_messages_delivered_after_sent"),
        ),
        sa.CheckConstraint(
            "read_at IS NULL OR delivered_at IS NULL OR read_at >= delivered_at",
            name=op.f("ck_messages_read_after_delivered"),
        ),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_messages_valid_retry_count")),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_messages_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_messages_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_message_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_message_id_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
            name=op.f("fk_messages_template_id_message_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_messages_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"], unique=False)
    op.create_index("ix_messages_created_at", "messages", ["created_at"], unique=False)
    op.create_index("ix_messages_delivery_status", "messages", ["delivery_status"], unique=False)
    op.create_index(
        "uq_messages_idempotency_key",
        "messages",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "uq_messages_provider_message_id",
        "messages",
        ["channel_id", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.create_table(
        "inbound_webhook_events",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=True),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processing_status", sa.String(length=16), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("resulting_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ('received', 'processed', 'failed', 'ignored')",
            name=op.f("ck_inbound_webhook_events_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_inbound_webhook_events_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["resulting_message_id"],
            ["messages.id"],
            name=op.f("fk_inbound_webhook_events_resulting_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_webhook_events")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_inbound_webhook_events_event"
        ),
    )
    op.create_index(
        "ix_inbound_webhook_events_channel_id",
        "inbound_webhook_events",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "manual_call_logs",
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("staff_user_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("follow_up_required", sa.Boolean(), nullable=False),
        sa.Column("related_reservation_id", sa.Uuid(), nullable=True),
        sa.Column("related_order_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name=op.f("ck_manual_call_logs_valid_direction")
        ),
        sa.CheckConstraint(
            "outcome IN ('connected', 'no_answer', 'voicemail', 'busy', 'wrong_number', 'other')",
            name=op.f("ck_manual_call_logs_valid_outcome"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_manual_call_logs_valid_call_window"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_manual_call_logs_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_manual_call_logs_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_manual_call_logs_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_manual_call_logs_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["related_order_id"],
            ["orders.id"],
            name=op.f("fk_manual_call_logs_related_order_id_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["related_reservation_id"],
            ["reservations.id"],
            name=op.f("fk_manual_call_logs_related_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_manual_call_logs_staff_user_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_manual_call_logs_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_call_logs")),
    )
    op.create_index(
        "ix_manual_call_logs_customer_id", "manual_call_logs", ["customer_id"], unique=False
    )
    op.create_index("ix_manual_call_logs_lead_id", "manual_call_logs", ["lead_id"], unique=False)
    op.create_index(
        "ix_manual_call_logs_staff_user_id", "manual_call_logs", ["staff_user_id"], unique=False
    )
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=80), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("external_provider_reference", sa.String(length=200), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("scan_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'clean', 'infected', 'skipped')",
            name=op.f("ck_message_attachments_valid_scan_status"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('pending', 'uploaded', 'failed')",
            name=op.f("ck_message_attachments_valid_upload_status"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_message_attachments_valid_size_bytes")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_message_attachments_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_message_attachments_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_message_attachments_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_message_attachments_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_attachments")),
    )
    op.create_index(
        "ix_message_attachments_message_id", "message_attachments", ["message_id"], unique=False
    )
    op.create_table(
        "message_delivery_attempts",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("provider_response_code", sa.String(length=40), nullable=True),
        sa.Column("is_retryable", sa.Boolean(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('success', 'transient_failure', 'rate_limited', 'invalid_destination', 'authentication_error', 'template_rejected', 'suppressed', 'customer_opted_out', 'permanent_failure', 'network_timeout')",  # noqa: E501
            name=op.f("ck_message_delivery_attempts_valid_result"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_message_delivery_attempts_valid_attempt_number")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_delivery_attempts_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_delivery_attempts")),
    )
    op.create_index(
        "ix_message_delivery_attempts_message_id",
        "message_delivery_attempts",
        ["message_id"],
        unique=False,
    )
    op.create_table(
        "message_status_history",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('system', 'staff', 'webhook')",
            name=op.f("ck_message_status_history_valid_source"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_message_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_status_history_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_status_history")),
    )
    op.create_index(
        "ix_message_status_history_message_id",
        "message_status_history",
        ["message_id"],
        unique=False,
    )
    op.create_table(
        "provider_status_events",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=True),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_status", sa.String(length=24), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processing_status", sa.String(length=16), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "normalized_status IN ('accepted', 'queued', 'sent', 'delivered', 'read', 'failed', 'rejected', 'undeliverable')",  # noqa: E501
            name=op.f("ck_provider_status_events_valid_normalized_status"),
        ),
        sa.CheckConstraint(
            "processing_status IN ('received', 'processed', 'ignored', 'failed')",
            name=op.f("ck_provider_status_events_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_provider_status_events_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_provider_status_events_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_status_events")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_provider_status_events_event"
        ),
    )
    op.create_index(
        "ix_provider_status_events_message_id",
        "provider_status_events",
        ["message_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_messages",
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_reference", sa.String(length=200), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("template_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("processing_locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("result_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('reservation_reminder', 'feedback_request', 'lead_follow_up', 'manual')",
            name=op.f("ck_scheduled_messages_valid_purpose"),
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'processing', 'sent', 'cancelled', 'failed')",
            name=op.f("ck_scheduled_messages_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_scheduled_messages_valid_attempt_count")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_messages_cancelled_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_scheduled_messages_channel_id_communication_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_scheduled_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_messages_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_scheduled_messages_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_scheduled_messages_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["result_message_id"],
            ["messages.id"],
            name=op.f("fk_scheduled_messages_result_message_id_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
            name=op.f("fk_scheduled_messages_template_id_message_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_messages_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_messages")),
    )
    op.create_index(
        "ix_scheduled_messages_status_scheduled_for",
        "scheduled_messages",
        ["status", "scheduled_for"],
        unique=False,
    )
    op.create_index(
        "uq_scheduled_messages_idempotency_key",
        "scheduled_messages",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _PHASE10_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_scheduled_messages_idempotency_key",
        table_name="scheduled_messages",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_scheduled_messages_status_scheduled_for", table_name="scheduled_messages")
    op.drop_table("scheduled_messages")
    op.drop_index("ix_provider_status_events_message_id", table_name="provider_status_events")
    op.drop_table("provider_status_events")
    op.drop_index("ix_message_status_history_message_id", table_name="message_status_history")
    op.drop_table("message_status_history")
    op.drop_index("ix_message_delivery_attempts_message_id", table_name="message_delivery_attempts")
    op.drop_table("message_delivery_attempts")
    op.drop_index("ix_message_attachments_message_id", table_name="message_attachments")
    op.drop_table("message_attachments")
    op.drop_index("ix_manual_call_logs_staff_user_id", table_name="manual_call_logs")
    op.drop_index("ix_manual_call_logs_lead_id", table_name="manual_call_logs")
    op.drop_index("ix_manual_call_logs_customer_id", table_name="manual_call_logs")
    op.drop_table("manual_call_logs")
    op.drop_index("ix_inbound_webhook_events_channel_id", table_name="inbound_webhook_events")
    op.drop_table("inbound_webhook_events")
    op.drop_index(
        "uq_messages_provider_message_id",
        table_name="messages",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_messages_idempotency_key",
        table_name="messages",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_messages_delivery_status", table_name="messages")
    op.drop_index("ix_messages_created_at", table_name="messages")
    op.drop_index("ix_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_conversation_status_history_conversation_id", table_name="conversation_status_history"
    )
    op.drop_table("conversation_status_history")
    op.drop_index(
        "uq_conversation_links_active",
        table_name="conversation_links",
        postgresql_where=sa.text("unlinked_at IS NULL"),
    )
    op.drop_index("ix_conversation_links_linked", table_name="conversation_links")
    op.drop_index("ix_conversation_links_conversation_id", table_name="conversation_links")
    op.drop_table("conversation_links")
    op.drop_index(
        "ix_conversation_assignments_conversation_id", table_name="conversation_assignments"
    )
    op.drop_table("conversation_assignments")
    op.drop_index("ix_conversations_status", table_name="conversations")
    op.drop_index("ix_conversations_lead_id", table_name="conversations")
    op.drop_index("ix_conversations_last_activity_at", table_name="conversations")
    op.drop_index("ix_conversations_customer_id", table_name="conversations")
    op.drop_index("ix_conversations_channel_id", table_name="conversations")
    op.drop_index("ix_conversations_assigned_staff_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_task_status_history_task_id", table_name="task_status_history")
    op.drop_table("task_status_history")
    op.drop_index("ix_task_assignments_task_id", table_name="task_assignments")
    op.drop_table("task_assignments")
    op.drop_index("ix_message_templates_channel_id", table_name="message_templates")
    op.drop_index("ix_message_templates_category", table_name="message_templates")
    op.drop_table("message_templates")
    op.drop_index(
        "uq_communication_suppressions_active_destination",
        table_name="communication_suppressions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("communication_suppressions")
    op.drop_table("communication_preferences")
    op.drop_index("ix_communication_consents_customer_id", table_name="communication_consents")
    op.drop_table("communication_consents")
    op.drop_index(
        "uq_task_records_idempotency_key",
        table_name="task_records",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_task_records_status", table_name="task_records")
    op.drop_index("ix_task_records_related", table_name="task_records")
    op.drop_index("ix_task_records_parent_task_id", table_name="task_records")
    op.drop_index("ix_task_records_due_at", table_name="task_records")
    op.drop_index("ix_task_records_assigned_staff_id", table_name="task_records")
    op.drop_table("task_records")
    op.drop_index(
        "uq_notifications_dedup_key",
        table_name="notifications",
        postgresql_where=sa.text("dedup_key IS NOT NULL"),
    )
    op.drop_index("ix_notifications_recipient_staff_id_read_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("communication_channels")
    # ### end Alembic commands ###
