"""add_staff_users_roles_permissions_foundation

Revision ID: 139a3e5919f2
Revises: c39639df2f6c
Create Date: 2026-07-25 17:23:05.960677

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "139a3e5919f2"
down_revision: str | Sequence[str] | None = "c39639df2f6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # citext is required by staff_users.email and staff_invitations.email
    # (case-insensitive unique email matching) — DATABASE_AND_API.md
    # sections 4.1 and 4.6. Manually added; Alembic autogenerate does not
    # detect extensions.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name=op.f("uq_departments_code")),
        sa.UniqueConstraint("name", name=op.f("uq_departments_name")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("code = lower(code)", name=op.f("ck_permissions_lowercase_code")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name=op.f("ck_roles_lowercase_code")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope_type IN ('all', 'department', 'assigned', 'self', 'none')",
            name=op.f("ck_role_permissions_valid_scope_type"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name="pk_role_permissions"),
    )
    op.create_table(
        "staff_users",
        sa.Column("auth_user_id", sa.Uuid(), nullable=False),
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("account_status", sa.String(length=32), nullable=False),
        sa.Column("employment_status", sa.String(length=32), nullable=False),
        sa.Column("is_privileged", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("avatar_storage_path", sa.String(length=500), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "account_status IN "
            "('invited', 'active', 'suspended', 'disabled', 'locked', 'archived')",
            name=op.f("ck_staff_users_valid_account_status"),
        ),
        sa.CheckConstraint(
            "employment_status IN ('full_time', 'part_time', 'contract', 'intern')",
            name=op.f("ck_staff_users_valid_employment_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_staff_users_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_staff_users_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_staff_users_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_staff_users_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_users")),
        sa.UniqueConstraint("auth_user_id", name=op.f("uq_staff_users_auth_user_id")),
        sa.UniqueConstraint("employee_code", name=op.f("uq_staff_users_employee_code")),
    )
    op.create_index(
        "ix_staff_users_active",
        "staff_users",
        ["account_status"],
        unique=False,
        postgresql_where=sa.text("account_status = 'active' AND deleted_at IS NULL"),
    )
    op.create_index("ix_staff_users_department_id", "staff_users", ["department_id"], unique=False)
    op.create_index(
        "uq_staff_users_active_email",
        "staff_users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "staff_invitations",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("intended_role_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("staff_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'revoked', 'expired')",
            name=op.f("ck_staff_invitations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_staff_invitations_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["intended_role_id"],
            ["roles.id"],
            name=op.f("fk_staff_invitations_intended_role_id_roles"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["staff_users.id"],
            name=op.f("fk_staff_invitations_invited_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_staff_invitations_staff_user_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_invitations")),
    )
    op.create_index("ix_staff_invitations_email", "staff_invitations", ["email"], unique=False)
    op.create_table(
        "staff_roles",
        sa.Column("staff_user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"], ["staff_users.id"], name=op.f("fk_staff_roles_assigned_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_staff_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_staff_roles_staff_user_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("staff_user_id", "role_id", name="pk_staff_roles"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff_roles")
    op.drop_index("ix_staff_invitations_email", table_name="staff_invitations")
    op.drop_table("staff_invitations")
    op.drop_index(
        "uq_staff_users_active_email",
        table_name="staff_users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_staff_users_department_id", table_name="staff_users")
    op.drop_index(
        "ix_staff_users_active",
        table_name="staff_users",
        postgresql_where=sa.text("account_status = 'active' AND deleted_at IS NULL"),
    )
    op.drop_table("staff_users")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("departments")
    # ### end Alembic commands ###
    # citext is left installed on downgrade — dropping a shared extension is
    # unsafe to automate and it is harmless to leave enabled.
