"""add_phase13_feedback_complaints_service_recovery

Revision ID: 271354f4adbf
Revises: a64c160fc49d
Create Date: 2026-08-01 06:47:08.370220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "271354f4adbf"
down_revision: str | Sequence[str] | None = "a64c160fc49d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PHASE13_TABLES = (
    "compensation_approval_rules",
    "sla_policies",
    "feedback_entries",
    "complaints",
    "feedback_attachments",
    "feedback_ratings",
    "feedback_status_history",
    "feedback_tags",
    "review_requests",
    "complaint_assignments",
    "complaint_attachments",
    "complaint_escalations",
    "complaint_follow_ups",
    "complaint_links",
    "complaint_notes",
    "complaint_root_cause_history",
    "complaint_sla_events",
    "complaint_status_history",
    "service_recovery_actions",
    "service_recovery_action_history",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compensation_approval_rules",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("recovery_type", sa.String(length=24), nullable=True),
        sa.Column("min_value_minor", sa.Integer(), nullable=True),
        sa.Column("max_value_minor", sa.Integer(), nullable=True),
        sa.Column(
            "applicable_severities",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("required_permission", sa.String(length=100), nullable=False),
        sa.Column("allow_self_approval", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "recovery_type IS NULL OR recovery_type IN ('apology_only', 'replacement', 'refund_request', 'approved_refund', 'discount', 'coupon', 'loyalty_credit', 'complimentary_item', 'manager_follow_up', 'operational_correction')",  # noqa: E501
            name=op.f("ck_compensation_approval_rules_valid_recovery_type"),
        ),
        sa.CheckConstraint(
            "max_value_minor IS NULL OR max_value_minor >= 0",
            name=op.f("ck_compensation_approval_rules_valid_max_value_minor"),
        ),
        sa.CheckConstraint(
            "max_value_minor IS NULL OR min_value_minor IS NULL OR max_value_minor >= min_value_minor",  # noqa: E501
            name=op.f("ck_compensation_approval_rules_valid_value_range"),
        ),
        sa.CheckConstraint(
            "min_value_minor IS NULL OR min_value_minor >= 0",
            name=op.f("ck_compensation_approval_rules_valid_min_value_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_compensation_approval_rules_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_compensation_approval_rules_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compensation_approval_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_compensation_approval_rules_code")),
    )
    op.create_table(
        "sla_policies",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "applicable_categories",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "applicable_severities",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("first_response_minutes", sa.Integer(), nullable=False),
        sa.Column("acknowledgement_minutes", sa.Integer(), nullable=False),
        sa.Column("resolution_minutes", sa.Integer(), nullable=False),
        sa.Column("follow_up_minutes", sa.Integer(), nullable=True),
        sa.Column("escalation_after_minutes", sa.Integer(), nullable=True),
        sa.Column("business_hours_only", sa.Boolean(), nullable=False),
        sa.Column("default_assignee_department_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "acknowledgement_minutes > 0",
            name=op.f("ck_sla_policies_valid_acknowledgement_minutes"),
        ),
        sa.CheckConstraint(
            "escalation_after_minutes IS NULL OR escalation_after_minutes > 0",
            name=op.f("ck_sla_policies_valid_escalation_after_minutes"),
        ),
        sa.CheckConstraint(
            "first_response_minutes > 0", name=op.f("ck_sla_policies_valid_first_response_minutes")
        ),
        sa.CheckConstraint(
            "follow_up_minutes IS NULL OR follow_up_minutes > 0",
            name=op.f("ck_sla_policies_valid_follow_up_minutes"),
        ),
        sa.CheckConstraint(
            "resolution_minutes > 0", name=op.f("ck_sla_policies_valid_resolution_minutes")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_sla_policies_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["default_assignee_department_id"],
            ["departments.id"],
            name=op.f("fk_sla_policies_default_assignee_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_sla_policies_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_policies")),
        sa.UniqueConstraint("code", name=op.f("uq_sla_policies_code")),
    )
    op.create_table(
        "feedback_entries",
        sa.Column("feedback_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("guest_name", sa.String(length=160), nullable=True),
        sa.Column("guest_contact", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.String(length=16), nullable=True),
        sa.Column("consent_for_follow_up", sa.Boolean(), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("converted_to_complaint_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_feedback_entries_valid_priority"),
        ),
        sa.CheckConstraint(
            "sentiment IS NULL OR sentiment IN ('positive', 'neutral', 'negative', 'mixed')",
            name=op.f("ck_feedback_entries_valid_sentiment"),
        ),
        sa.CheckConstraint(
            "source IN ('post_order', 'post_reservation', 'website', 'whatsapp', 'email', 'manual_entry', 'public_review_reference', 'campaign')",  # noqa: E501
            name=op.f("ck_feedback_entries_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'under_review', 'action_required', 'resolved', 'closed', 'spam')",  # noqa: E501
            name=op.f("ck_feedback_entries_valid_status"),
        ),
        sa.CheckConstraint(
            "customer_id IS NOT NULL OR guest_name IS NOT NULL OR guest_contact IS NOT NULL",
            name=op.f("ck_feedback_entries_requires_customer_or_guest_identity"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR acknowledged_at IS NULL OR resolved_at >= acknowledged_at",
            name=op.f("ck_feedback_entries_valid_resolution_ordering"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_feedback_entries_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_feedback_entries_campaign_id_campaigns"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_feedback_entries_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_feedback_entries_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_feedback_entries_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_feedback_entries_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_feedback_entries_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_entries")),
        sa.UniqueConstraint("feedback_number", name=op.f("uq_feedback_entries_feedback_number")),
    )
    op.create_index(
        "ix_feedback_entries_assigned_staff_id",
        "feedback_entries",
        ["assigned_staff_id"],
        unique=False,
    )
    op.create_index(
        "ix_feedback_entries_created_at", "feedback_entries", ["created_at"], unique=False
    )
    op.create_index(
        "ix_feedback_entries_customer_id", "feedback_entries", ["customer_id"], unique=False
    )
    op.create_index("ix_feedback_entries_order_id", "feedback_entries", ["order_id"], unique=False)
    op.create_index(
        "ix_feedback_entries_reservation_id", "feedback_entries", ["reservation_id"], unique=False
    )
    op.create_index("ix_feedback_entries_status", "feedback_entries", ["status"], unique=False)
    op.create_table(
        "complaints",
        sa.Column("complaint_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_department_id", sa.Uuid(), nullable=True),
        sa.Column("current_escalation_level", sa.Integer(), nullable=False),
        sa.Column("sla_policy_id", sa.Uuid(), nullable=True),
        sa.Column("first_response_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledgement_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("follow_up_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reopened_count", sa.Integer(), nullable=False),
        sa.Column("customer_sentiment", sa.String(length=16), nullable=True),
        sa.Column("root_cause", sa.String(length=32), nullable=True),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.Column("customer_visible_summary", sa.Text(), nullable=True),
        sa.Column("is_hr_sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category IN ('food_quality', 'incorrect_item', 'missing_item', 'packaging', 'delay', 'delivery', 'payment', 'refund', 'reservation', 'staff_behavior', 'cleanliness', 'allergy_or_dietary', 'promotion', 'loyalty', 'communication', 'corporate_order', 'other')",  # noqa: E501
            name=op.f("ck_complaints_valid_category"),
        ),
        sa.CheckConstraint(
            "customer_sentiment IS NULL OR customer_sentiment IN ('positive', 'neutral', 'negative', 'mixed')",  # noqa: E501
            name=op.f("ck_complaints_valid_customer_sentiment"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_complaints_valid_priority"),
        ),
        sa.CheckConstraint(
            "root_cause IS NULL OR root_cause IN ('process_failure', 'preparation_error', 'inventory_unavailable', 'packaging_error', 'delivery_delay', 'staff_training_gap', 'communication_failure', 'system_failure', 'supplier_issue', 'policy_gap', 'customer_expectation_mismatch', 'unknown')",  # noqa: E501
            name=op.f("ck_complaints_valid_root_cause"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_complaints_valid_severity"),
        ),
        sa.CheckConstraint(
            "source_type IN ('feedback', 'direct', 'conversation', 'staff_entry', 'order', 'reservation', 'other')",  # noqa: E501
            name=op.f("ck_complaints_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'investigating', 'awaiting_customer', 'awaiting_internal', 'resolution_proposed', 'resolved', 'closed', 'reopened', 'cancelled')",  # noqa: E501
            name=op.f("ck_complaints_valid_status"),
        ),
        sa.CheckConstraint(
            "closed_at IS NULL OR resolved_at IS NULL OR closed_at >= resolved_at",
            name=op.f("ck_complaints_valid_closure_ordering"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR acknowledged_at IS NULL OR resolved_at >= acknowledged_at",
            name=op.f("ck_complaints_valid_resolution_ordering"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_department_id"],
            ["departments.id"],
            name=op.f("fk_complaints_assigned_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_complaints_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_complaints_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_complaints_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_complaints_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_complaints_feedback_id_feedback_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_complaints_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_complaints_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["sla_policy_id"],
            ["sla_policies.id"],
            name=op.f("fk_complaints_sla_policy_id_sla_policies"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_complaints_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
        sa.UniqueConstraint("complaint_number", name=op.f("uq_complaints_complaint_number")),
    )
    op.create_index(
        "ix_complaints_assigned_department_id",
        "complaints",
        ["assigned_department_id"],
        unique=False,
    )
    op.create_index(
        "ix_complaints_assigned_staff_id", "complaints", ["assigned_staff_id"], unique=False
    )
    op.create_index("ix_complaints_category", "complaints", ["category"], unique=False)
    op.create_index(
        "ix_complaints_conversation_id", "complaints", ["conversation_id"], unique=False
    )
    op.create_index("ix_complaints_created_at", "complaints", ["created_at"], unique=False)
    op.create_index("ix_complaints_customer_id", "complaints", ["customer_id"], unique=False)
    op.create_index("ix_complaints_feedback_id", "complaints", ["feedback_id"], unique=False)
    op.create_index(
        "ix_complaints_follow_up_due_at", "complaints", ["follow_up_due_at"], unique=False
    )
    op.create_index("ix_complaints_order_id", "complaints", ["order_id"], unique=False)
    op.create_index("ix_complaints_priority", "complaints", ["priority"], unique=False)
    op.create_index("ix_complaints_reservation_id", "complaints", ["reservation_id"], unique=False)
    op.create_index(
        "ix_complaints_resolution_due_at", "complaints", ["resolution_due_at"], unique=False
    )
    op.create_index("ix_complaints_severity", "complaints", ["severity"], unique=False)
    op.create_index("ix_complaints_status", "complaints", ["status"], unique=False)
    op.create_table(
        "feedback_attachments",
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=80), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("scan_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'clean', 'infected', 'skipped')",
            name=op.f("ck_feedback_attachments_valid_scan_status"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('pending', 'uploaded', 'failed')",
            name=op.f("ck_feedback_attachments_valid_upload_status"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_feedback_attachments_valid_size_bytes")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_feedback_attachments_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_feedback_attachments_feedback_id_feedback_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_feedback_attachments_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_attachments")),
    )
    op.create_index(
        "ix_feedback_attachments_feedback_id", "feedback_attachments", ["feedback_id"], unique=False
    )
    op.create_table(
        "feedback_ratings",
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("dimension", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "dimension IN ('overall', 'food_quality', 'taste', 'packaging', 'delivery', 'speed', 'staff_service', 'cleanliness', 'reservation_experience', 'value')",  # noqa: E501
            name=op.f("ck_feedback_ratings_valid_dimension"),
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_feedback_ratings_valid_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_feedback_ratings_feedback_id_feedback_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_ratings")),
    )
    op.create_index(
        "uq_feedback_ratings_entry_dimension",
        "feedback_ratings",
        ["feedback_id", "dimension"],
        unique=True,
    )
    op.create_table(
        "feedback_status_history",
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_feedback_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_feedback_status_history_feedback_id_feedback_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_status_history")),
    )
    op.create_index(
        "ix_feedback_status_history_feedback_id",
        "feedback_status_history",
        ["feedback_id"],
        unique=False,
    )
    op.create_table(
        "feedback_tags",
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_feedback_tags_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_feedback_tags_feedback_id_feedback_entries"),
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_feedback_tags_tag_id_tags")),
        sa.PrimaryKeyConstraint("feedback_id", "tag_id", name=op.f("pk_feedback_tags")),
    )
    op.create_table(
        "review_requests",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("eligibility_reason", sa.String(length=200), nullable=True),
        sa.Column("suppression_reason", sa.String(length=200), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("resulting_feedback_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_message_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'order' AND order_id IS NOT NULL AND reservation_id IS NULL) OR (source_type = 'reservation' AND reservation_id IS NOT NULL AND order_id IS NULL)",  # noqa: E501
            name=op.f("ck_review_requests_valid_source_reference"),
        ),
        sa.CheckConstraint(
            "channel IN ('whatsapp', 'email', 'sms')", name=op.f("ck_review_requests_valid_channel")
        ),
        sa.CheckConstraint(
            "source_type IN ('order', 'reservation')",
            name=op.f("ck_review_requests_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'eligible', 'scheduled', 'sent', 'delivered', 'opened', 'completed', 'expired', 'suppressed', 'cancelled', 'failed')",  # noqa: E501
            name=op.f("ck_review_requests_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_review_requests_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_review_requests_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_review_requests_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_review_requests_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["resulting_feedback_id"],
            ["feedback_entries.id"],
            name=op.f("fk_review_requests_resulting_feedback_id_feedback_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_message_id"],
            ["scheduled_messages.id"],
            name=op.f("fk_review_requests_scheduled_message_id_scheduled_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_review_requests_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_requests")),
    )
    op.create_index(
        "ix_review_requests_customer_id", "review_requests", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_review_requests_scheduled_at", "review_requests", ["scheduled_at"], unique=False
    )
    op.create_index("ix_review_requests_status", "review_requests", ["status"], unique=False)
    op.create_index(
        "uq_review_requests_idempotency_key", "review_requests", ["idempotency_key"], unique=True
    )
    op.create_table(
        "complaint_assignments",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_department_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assigned_staff_id IS NOT NULL OR assigned_department_id IS NOT NULL",
            name=op.f("ck_complaint_assignments_requires_staff_or_department"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_complaint_assignments_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_department_id"],
            ["departments.id"],
            name=op.f("fk_complaint_assignments_assigned_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_assignments_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_assignments_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_assignments")),
    )
    op.create_index(
        "ix_complaint_assignments_complaint_id",
        "complaint_assignments",
        ["complaint_id"],
        unique=False,
    )
    op.create_table(
        "complaint_attachments",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=80), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("scan_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'clean', 'infected', 'skipped')",
            name=op.f("ck_complaint_attachments_valid_scan_status"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('pending', 'uploaded', 'failed')",
            name=op.f("ck_complaint_attachments_valid_upload_status"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_complaint_attachments_valid_size_bytes")
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_attachments_complaint_id_complaints"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_complaint_attachments_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_complaint_attachments_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_attachments")),
    )
    op.create_index(
        "ix_complaint_attachments_complaint_id",
        "complaint_attachments",
        ["complaint_id"],
        unique=False,
    )
    op.create_table(
        "complaint_escalations",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("triggered_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("previous_assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("previous_assigned_department_id", sa.Uuid(), nullable=True),
        sa.Column("new_assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("new_assigned_department_id", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_escalations_complaint_id_complaints"),
        ),
        sa.ForeignKeyConstraint(
            ["new_assigned_department_id"],
            ["departments.id"],
            name=op.f("fk_complaint_escalations_new_assigned_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["new_assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_escalations_new_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_escalations_triggered_by_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_escalations")),
    )
    op.create_index(
        "ix_complaint_escalations_complaint_id",
        "complaint_escalations",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        "uq_complaint_escalations_dedup_key", "complaint_escalations", ["dedup_key"], unique=True
    )
    op.create_table(
        "complaint_follow_ups",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('satisfied', 'unsatisfied', 'no_response', 'escalated_again')",  # noqa: E501
            name=op.f("ck_complaint_follow_ups_valid_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_follow_ups_complaint_id_complaints"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_complaint_follow_ups_created_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_follow_ups")),
    )
    op.create_index(
        "ix_complaint_follow_ups_complaint_id",
        "complaint_follow_ups",
        ["complaint_id"],
        unique=False,
    )
    op.create_table(
        "complaint_links",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("related_complaint_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relationship_type IN ('duplicate_of', 'related_to')",
            name=op.f("ck_complaint_links_valid_relationship_type"),
        ),
        sa.CheckConstraint(
            "complaint_id != related_complaint_id", name=op.f("ck_complaint_links_no_self_link")
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_links_complaint_id_complaints"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_complaint_links_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["related_complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_links_related_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_links")),
    )
    op.create_index(
        "uq_complaint_links_pair",
        "complaint_links",
        ["complaint_id", "related_complaint_id"],
        unique=True,
    )
    op.create_table(
        "complaint_notes",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("author_staff_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_notes_author_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_notes_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_notes")),
    )
    op.create_index(
        "ix_complaint_notes_complaint_id", "complaint_notes", ["complaint_id"], unique=False
    )
    op.create_table(
        "complaint_root_cause_history",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("from_root_cause", sa.String(length=32), nullable=True),
        sa.Column("to_root_cause", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_root_cause_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_root_cause_history_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_root_cause_history")),
    )
    op.create_index(
        "ix_complaint_root_cause_history_complaint_id",
        "complaint_root_cause_history",
        ["complaint_id"],
        unique=False,
    )
    op.create_table(
        "complaint_sla_events",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('approaching_first_response', 'breached_first_response', 'approaching_acknowledgement', 'breached_acknowledgement', 'approaching_resolution', 'breached_resolution', 'approaching_follow_up', 'breached_follow_up')",  # noqa: E501
            name=op.f("ck_complaint_sla_events_valid_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_sla_events_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_sla_events")),
    )
    op.create_index(
        "ix_complaint_sla_events_complaint_id",
        "complaint_sla_events",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        "uq_complaint_sla_events_dedup_key", "complaint_sla_events", ["dedup_key"], unique=True
    )
    op.create_table(
        "complaint_status_history",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_complaint_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_status_history_complaint_id_complaints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_status_history")),
    )
    op.create_index(
        "ix_complaint_status_history_complaint_id",
        "complaint_status_history",
        ["complaint_id"],
        unique=False,
    )
    op.create_table(
        "service_recovery_actions",
        sa.Column("complaint_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("value_minor", sa.Integer(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("proposed_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column(
            "proposed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column("approval_rule_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_reference_type", sa.String(length=32), nullable=True),
        sa.Column("execution_reference_id", sa.Uuid(), nullable=True),
        sa.Column("failed_reason", sa.Text(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "execution_reference_type IS NULL OR execution_reference_type IN ('loyalty_ledger_entry', 'customer_credit_ledger_entry', 'order_payment', 'manual')",  # noqa: E501
            name=op.f("ck_service_recovery_actions_valid_execution_reference_type"),
        ),
        sa.CheckConstraint(
            "recovery_type IN ('apology_only', 'replacement', 'refund_request', 'approved_refund', 'discount', 'coupon', 'loyalty_credit', 'complimentary_item', 'manager_follow_up', 'operational_correction')",  # noqa: E501
            name=op.f("ck_service_recovery_actions_valid_recovery_type"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'approval_required', 'approved', 'rejected', 'executing', 'completed', 'failed', 'reversed', 'cancelled')",  # noqa: E501
            name=op.f("ck_service_recovery_actions_valid_status"),
        ),
        sa.CheckConstraint(
            "points IS NULL OR points >= 0", name=op.f("ck_service_recovery_actions_valid_points")
        ),
        sa.CheckConstraint(
            "value_minor IS NULL OR value_minor >= 0",
            name=op.f("ck_service_recovery_actions_valid_value_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_rule_id"],
            ["compensation_approval_rules.id"],
            name=op.f("fk_service_recovery_actions_approval_rule_id_compensation_approval_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_actions_approved_by_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_service_recovery_actions_complaint_id_complaints"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_actions_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_service_recovery_actions_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_actions_proposed_by_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_actions_reversed_by_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_actions_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_recovery_actions")),
    )
    op.create_index(
        "ix_service_recovery_actions_complaint_id",
        "service_recovery_actions",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        "ix_service_recovery_actions_customer_id",
        "service_recovery_actions",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_service_recovery_actions_status", "service_recovery_actions", ["status"], unique=False
    )
    op.create_index(
        "uq_service_recovery_actions_idempotency_key",
        "service_recovery_actions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "service_recovery_action_history",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["service_recovery_actions.id"],
            name=op.f("fk_service_recovery_action_history_action_id_service_recovery_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_service_recovery_action_history_actor_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_recovery_action_history")),
    )
    op.create_index(
        "ix_service_recovery_action_history_action_id",
        "service_recovery_action_history",
        ["action_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _PHASE13_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")

    # `feedback_entries.converted_to_complaint_id` references `complaints`,
    # which is created after `feedback_entries` in this same migration —
    # the FK is added here, once both tables exist, rather than declared on
    # the model's column (see FeedbackEntry's own docstring).
    op.create_foreign_key(
        "fk_feedback_entries_converted_to_complaint_id_complaints",
        "feedback_entries",
        "complaints",
        ["converted_to_complaint_id"],
        ["id"],
    )

    # Widen two polymorphic CHECK constraints so Phase 13 tasks and
    # conversation links can carry a stable back-reference to a complaint
    # (and, for tasks, a feedback entry) — the same widening-via-raw-SQL
    # pattern the Phase 11 migration used for `task_records`/`notifications`.
    # Raw SQL, not `op.create_check_constraint`/`op.drop_constraint` — this
    # metadata's naming convention re-resolves a bare constraint name
    # through the `ck_%(table_name)s_%(constraint_name)s` template a second
    # time when passed to those helpers, corrupting an already-fully-
    # qualified name.
    op.execute("ALTER TABLE task_records DROP CONSTRAINT ck_task_records_valid_related_type")
    op.execute(
        "ALTER TABLE task_records ADD CONSTRAINT ck_task_records_valid_related_type "
        "CHECK (related_type IS NULL OR related_type IN ('customer', 'lead', 'order', "
        "'reservation', 'conversation', 'inventory_item', 'knowledge_article', "
        "'staff_transition_plan', 'staff_certification', 'staff_document', "
        "'training_assignment', 'performance_review', 'complaint', 'feedback'))"
    )
    op.execute(
        "ALTER TABLE conversation_links DROP CONSTRAINT ck_conversation_links_valid_linked_type"
    )
    op.execute(
        "ALTER TABLE conversation_links ADD CONSTRAINT ck_conversation_links_valid_linked_type "
        "CHECK (linked_type IN ('reservation', 'order', 'waitlist_entry', 'feedback_case', "
        "'complaint'))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Revert the two widened CHECK constraints and drop the deferred FK
    # before touching any Phase 13 table — `complaints` is dropped before
    # `feedback_entries` below, so the FK referencing it must go first.
    op.execute(
        "ALTER TABLE conversation_links DROP CONSTRAINT ck_conversation_links_valid_linked_type"
    )
    op.execute(
        "ALTER TABLE conversation_links ADD CONSTRAINT ck_conversation_links_valid_linked_type "
        "CHECK (linked_type IN ('reservation', 'order', 'waitlist_entry', 'feedback_case'))"
    )
    op.execute("ALTER TABLE task_records DROP CONSTRAINT ck_task_records_valid_related_type")
    op.execute(
        "ALTER TABLE task_records ADD CONSTRAINT ck_task_records_valid_related_type "
        "CHECK (related_type IS NULL OR related_type IN ('customer', 'lead', 'order', "
        "'reservation', 'conversation', 'inventory_item', 'knowledge_article', "
        "'staff_transition_plan', 'staff_certification', 'staff_document', "
        "'training_assignment', 'performance_review'))"
    )
    op.drop_constraint(
        "fk_feedback_entries_converted_to_complaint_id_complaints",
        "feedback_entries",
        type_="foreignkey",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_service_recovery_action_history_action_id", table_name="service_recovery_action_history"
    )
    op.drop_table("service_recovery_action_history")
    op.drop_index(
        "uq_service_recovery_actions_idempotency_key", table_name="service_recovery_actions"
    )
    op.drop_index("ix_service_recovery_actions_status", table_name="service_recovery_actions")
    op.drop_index("ix_service_recovery_actions_customer_id", table_name="service_recovery_actions")
    op.drop_index("ix_service_recovery_actions_complaint_id", table_name="service_recovery_actions")
    op.drop_table("service_recovery_actions")
    op.drop_index("ix_complaint_status_history_complaint_id", table_name="complaint_status_history")
    op.drop_table("complaint_status_history")
    op.drop_index("uq_complaint_sla_events_dedup_key", table_name="complaint_sla_events")
    op.drop_index("ix_complaint_sla_events_complaint_id", table_name="complaint_sla_events")
    op.drop_table("complaint_sla_events")
    op.drop_index(
        "ix_complaint_root_cause_history_complaint_id", table_name="complaint_root_cause_history"
    )
    op.drop_table("complaint_root_cause_history")
    op.drop_index("ix_complaint_notes_complaint_id", table_name="complaint_notes")
    op.drop_table("complaint_notes")
    op.drop_index("uq_complaint_links_pair", table_name="complaint_links")
    op.drop_table("complaint_links")
    op.drop_index("ix_complaint_follow_ups_complaint_id", table_name="complaint_follow_ups")
    op.drop_table("complaint_follow_ups")
    op.drop_index("uq_complaint_escalations_dedup_key", table_name="complaint_escalations")
    op.drop_index("ix_complaint_escalations_complaint_id", table_name="complaint_escalations")
    op.drop_table("complaint_escalations")
    op.drop_index("ix_complaint_attachments_complaint_id", table_name="complaint_attachments")
    op.drop_table("complaint_attachments")
    op.drop_index("ix_complaint_assignments_complaint_id", table_name="complaint_assignments")
    op.drop_table("complaint_assignments")
    op.drop_index("uq_review_requests_idempotency_key", table_name="review_requests")
    op.drop_index("ix_review_requests_status", table_name="review_requests")
    op.drop_index("ix_review_requests_scheduled_at", table_name="review_requests")
    op.drop_index("ix_review_requests_customer_id", table_name="review_requests")
    op.drop_table("review_requests")
    op.drop_table("feedback_tags")
    op.drop_index("ix_feedback_status_history_feedback_id", table_name="feedback_status_history")
    op.drop_table("feedback_status_history")
    op.drop_index("uq_feedback_ratings_entry_dimension", table_name="feedback_ratings")
    op.drop_table("feedback_ratings")
    op.drop_index("ix_feedback_attachments_feedback_id", table_name="feedback_attachments")
    op.drop_table("feedback_attachments")
    op.drop_index("ix_complaints_status", table_name="complaints")
    op.drop_index("ix_complaints_severity", table_name="complaints")
    op.drop_index("ix_complaints_resolution_due_at", table_name="complaints")
    op.drop_index("ix_complaints_reservation_id", table_name="complaints")
    op.drop_index("ix_complaints_priority", table_name="complaints")
    op.drop_index("ix_complaints_order_id", table_name="complaints")
    op.drop_index("ix_complaints_follow_up_due_at", table_name="complaints")
    op.drop_index("ix_complaints_feedback_id", table_name="complaints")
    op.drop_index("ix_complaints_customer_id", table_name="complaints")
    op.drop_index("ix_complaints_created_at", table_name="complaints")
    op.drop_index("ix_complaints_conversation_id", table_name="complaints")
    op.drop_index("ix_complaints_category", table_name="complaints")
    op.drop_index("ix_complaints_assigned_staff_id", table_name="complaints")
    op.drop_index("ix_complaints_assigned_department_id", table_name="complaints")
    op.drop_table("complaints")
    op.drop_index("ix_feedback_entries_status", table_name="feedback_entries")
    op.drop_index("ix_feedback_entries_reservation_id", table_name="feedback_entries")
    op.drop_index("ix_feedback_entries_order_id", table_name="feedback_entries")
    op.drop_index("ix_feedback_entries_customer_id", table_name="feedback_entries")
    op.drop_index("ix_feedback_entries_created_at", table_name="feedback_entries")
    op.drop_index("ix_feedback_entries_assigned_staff_id", table_name="feedback_entries")
    op.drop_table("feedback_entries")
    op.drop_table("sla_policies")
    op.drop_table("compensation_approval_rules")
    # ### end Alembic commands ###
