"""add phase9 reservations tables floor management

Revision ID: 385abc1d4309
Revises: b34d3dac8a82
Create Date: 2026-07-27 20:34:10.498961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "385abc1d4309"
down_revision: str | Sequence[str] | None = "b34d3dac8a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_RESERVATION_TABLES = (
    "reservation_tags",
    "business_hours",
    "dining_areas",
    "holiday_calendar",
    "reservation_policies",
    "reservation_settings",
    "restaurant_tables",
    "table_blocks",
    "table_status_history",
    "reservations",
    "reservation_notes",
    "reservation_status_history",
    "reservation_table_assignments",
    "reservation_tag_links",
    "reservation_timeline",
    "reservation_waitlist",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation_tags",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_tags")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_reservation_tags_normalized_name")),
    )
    op.create_table(
        "business_hours",
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("closes_next_day", sa.Boolean(), nullable=False),
        sa.Column("break_starts_at", sa.Time(), nullable=True),
        sa.Column("break_ends_at", sa.Time(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(break_starts_at IS NULL) = (break_ends_at IS NULL)",
            name=op.f("ck_business_hours_valid_break_window"),
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 0 AND 6", name=op.f("ck_business_hours_valid_day_of_week")
        ),
        sa.CheckConstraint(
            "is_closed OR (opens_at IS NOT NULL AND closes_at IS NOT NULL)",
            name=op.f("ck_business_hours_valid_open_hours"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_business_hours_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_business_hours_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_hours")),
        sa.UniqueConstraint("day_of_week", name=op.f("uq_business_hours_day_of_week")),
    )
    op.create_table(
        "dining_areas",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_dining_areas_valid_sort_order")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_dining_areas_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_dining_areas_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_dining_areas_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dining_areas")),
        sa.UniqueConstraint("code", name=op.f("uq_dining_areas_code")),
    )
    op.create_index(
        "ix_dining_areas_active",
        "dining_areas",
        ["sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_table(
        "holiday_calendar",
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "is_closed OR (opens_at IS NOT NULL AND closes_at IS NOT NULL)",
            name=op.f("ck_holiday_calendar_valid_special_hours"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_holiday_calendar_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_holiday_calendar_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_holiday_calendar_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holiday_calendar")),
    )
    op.create_index(
        "uq_holiday_calendar_active_date",
        "holiday_calendar",
        ["holiday_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "reservation_policies",
        sa.Column("singleton_guard", sa.Boolean(), nullable=False),
        sa.Column("deposit_required_by_default", sa.Boolean(), nullable=False),
        sa.Column("default_deposit_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("advance_booking_limit_days", sa.Integer(), nullable=False),
        sa.Column("minimum_notice_minutes", sa.Integer(), nullable=False),
        sa.Column("cancellation_window_minutes", sa.Integer(), nullable=False),
        sa.Column("no_show_grace_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_before_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_after_minutes", sa.Integer(), nullable=False),
        sa.Column("default_minimum_party_size", sa.Integer(), nullable=False),
        sa.Column("default_maximum_party_size", sa.Integer(), nullable=False),
        sa.Column("large_party_threshold", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "advance_booking_limit_days > 0",
            name=op.f("ck_reservation_policies_valid_advance_booking_limit"),
        ),
        sa.CheckConstraint(
            "buffer_after_minutes >= 0", name=op.f("ck_reservation_policies_valid_buffer_after")
        ),
        sa.CheckConstraint(
            "buffer_before_minutes >= 0", name=op.f("ck_reservation_policies_valid_buffer_before")
        ),
        sa.CheckConstraint(
            "cancellation_window_minutes >= 0",
            name=op.f("ck_reservation_policies_valid_cancellation_window"),
        ),
        sa.CheckConstraint(
            "default_deposit_amount_minor IS NULL OR default_deposit_amount_minor >= 0",
            name=op.f("ck_reservation_policies_valid_default_deposit_amount_minor"),
        ),
        sa.CheckConstraint(
            "default_maximum_party_size >= default_minimum_party_size",
            name=op.f("ck_reservation_policies_valid_default_maximum_party_size"),
        ),
        sa.CheckConstraint(
            "default_minimum_party_size > 0",
            name=op.f("ck_reservation_policies_valid_default_minimum_party_size"),
        ),
        sa.CheckConstraint(
            "large_party_threshold >= default_maximum_party_size",
            name=op.f("ck_reservation_policies_valid_large_party_threshold"),
        ),
        sa.CheckConstraint(
            "minimum_notice_minutes >= 0", name=op.f("ck_reservation_policies_valid_minimum_notice")
        ),
        sa.CheckConstraint(
            "no_show_grace_minutes >= 0", name=op.f("ck_reservation_policies_valid_no_show_grace")
        ),
        sa.CheckConstraint(
            "singleton_guard", name=op.f("ck_reservation_policies_valid_singleton_guard")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_policies_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_policies_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_policies")),
        sa.UniqueConstraint(
            "singleton_guard", name=op.f("uq_reservation_policies_singleton_guard")
        ),
    )
    op.create_table(
        "reservation_settings",
        sa.Column("singleton_guard", sa.Boolean(), nullable=False),
        sa.Column("default_reservation_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_assignment_enabled", sa.Boolean(), nullable=False),
        sa.Column("waitlist_enabled", sa.Boolean(), nullable=False),
        sa.Column("online_booking_enabled", sa.Boolean(), nullable=False),
        sa.Column("walk_in_enabled", sa.Boolean(), nullable=False),
        sa.Column("pending_request_expiry_minutes", sa.Integer(), nullable=True),
        sa.Column("reminder_lead_time_minutes", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "default_reservation_duration_minutes > 0",
            name=op.f("ck_reservation_settings_valid_default_reservation_duration_minutes"),
        ),
        sa.CheckConstraint(
            "pending_request_expiry_minutes IS NULL OR pending_request_expiry_minutes > 0",
            name=op.f("ck_reservation_settings_valid_pending_request_expiry_minutes"),
        ),
        sa.CheckConstraint(
            "reminder_lead_time_minutes IS NULL OR reminder_lead_time_minutes > 0",
            name=op.f("ck_reservation_settings_valid_reminder_lead_time_minutes"),
        ),
        sa.CheckConstraint(
            "singleton_guard", name=op.f("ck_reservation_settings_valid_singleton_guard")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_settings_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_settings_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_settings")),
        sa.UniqueConstraint(
            "singleton_guard", name=op.f("uq_reservation_settings_singleton_guard")
        ),
    )
    op.create_table(
        "restaurant_tables",
        sa.Column("dining_area_id", sa.Uuid(), nullable=False),
        sa.Column("table_number", sa.String(length=20), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("minimum_capacity", sa.Integer(), nullable=False),
        sa.Column("maximum_capacity", sa.Integer(), nullable=True),
        sa.Column("shape", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_wheelchair_accessible", sa.Boolean(), nullable=False),
        sa.Column("is_temporary", sa.Boolean(), nullable=False),
        sa.Column("merged_with_table_id", sa.Uuid(), nullable=True),
        sa.Column("qr_identifier", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "shape IN ('round', 'square', 'rectangle', 'oval', 'booth', 'bar', 'custom')",
            name=op.f("ck_restaurant_tables_valid_shape"),
        ),
        sa.CheckConstraint(
            "status IN ('available', 'reserved', 'occupied', 'cleaning', 'blocked', "
            "'maintenance', 'merged')",
            name=op.f("ck_restaurant_tables_valid_status"),
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_restaurant_tables_valid_capacity")),
        sa.CheckConstraint(
            "maximum_capacity IS NULL OR maximum_capacity >= capacity",
            name=op.f("ck_restaurant_tables_valid_maximum_capacity"),
        ),
        sa.CheckConstraint(
            "minimum_capacity <= capacity",
            name=op.f("ck_restaurant_tables_minimum_capacity_not_above_capacity"),
        ),
        sa.CheckConstraint(
            "minimum_capacity >= 0", name=op.f("ck_restaurant_tables_valid_minimum_capacity")
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_restaurant_tables_valid_sort_order")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_restaurant_tables_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_restaurant_tables_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["dining_area_id"],
            ["dining_areas.id"],
            name=op.f("fk_restaurant_tables_dining_area_id_dining_areas"),
        ),
        sa.ForeignKeyConstraint(
            ["merged_with_table_id"],
            ["restaurant_tables.id"],
            name=op.f("fk_restaurant_tables_merged_with_table_id_restaurant_tables"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_restaurant_tables_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restaurant_tables")),
    )
    op.create_index(
        "ix_restaurant_tables_dining_area_id", "restaurant_tables", ["dining_area_id"], unique=False
    )
    op.create_index("ix_restaurant_tables_status", "restaurant_tables", ["status"], unique=False)
    op.create_index(
        "uq_restaurant_tables_number",
        "restaurant_tables",
        ["table_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_restaurant_tables_qr_identifier",
        "restaurant_tables",
        ["qr_identifier"],
        unique=True,
        postgresql_where=sa.text("qr_identifier IS NOT NULL"),
    )
    op.create_table(
        "table_blocks",
        sa.Column("restaurant_table_id", sa.Uuid(), nullable=False),
        sa.Column("block_type", sa.String(length=24), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("released_by", sa.Uuid(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "block_type IN ('cleaning', 'maintenance', 'private_event', 'other')",
            name=op.f("ck_table_blocks_valid_block_type"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_table_blocks_valid_time_window")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_table_blocks_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["released_by"],
            ["staff_users.id"],
            name=op.f("fk_table_blocks_released_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_table_id"],
            ["restaurant_tables.id"],
            name=op.f("fk_table_blocks_restaurant_table_id_restaurant_tables"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_table_blocks_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_blocks")),
    )
    op.create_index(
        "ix_table_blocks_active_window",
        "table_blocks",
        ["restaurant_table_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_index(
        "ix_table_blocks_table_id", "table_blocks", ["restaurant_table_id"], unique=False
    )
    op.create_table(
        "table_status_history",
        sa.Column("restaurant_table_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=16), nullable=True),
        sa.Column("new_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["staff_users.id"],
            name=op.f("fk_table_status_history_changed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_table_id"],
            ["restaurant_tables.id"],
            name=op.f("fk_table_status_history_restaurant_table_id_restaurant_tables"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_status_history")),
    )
    op.create_index(
        "ix_table_status_history_table_id",
        "table_status_history",
        ["restaurant_table_id"],
        unique=False,
    )
    op.create_table(
        "reservations",
        sa.Column("reservation_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("guest_name", sa.String(length=180), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("reservation_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("dining_area_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("is_walk_in", sa.Boolean(), nullable=False),
        sa.Column("special_requests", sa.Text(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.Uuid(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("no_show_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_source", sa.String(length=16), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deposit_required", sa.Boolean(), nullable=False),
        sa.Column("deposit_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "cancellation_source IS NULL OR cancellation_source IN ('customer', 'restaurant')",
            name=op.f("ck_reservations_valid_cancellation_source"),
        ),
        sa.CheckConstraint(
            "source IN ('phone', 'walk_in', 'online', 'whatsapp', 'staff')",
            name=op.f("ck_reservations_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('requested', 'pending_review', 'needs_clarification', 'approved', "
            "'rejected', 'confirmation_sending', 'confirmed', 'reminder_scheduled', 'arrived', "
            "'seated', 'completed', 'no_show', 'cancelled_by_customer', "
            "'cancelled_by_restaurant', 'expired')",
            name=op.f("ck_reservations_valid_status"),
        ),
        sa.CheckConstraint(
            "deposit_amount_minor IS NULL OR deposit_amount_minor >= 0",
            name=op.f("ck_reservations_valid_deposit_amount_minor"),
        ),
        sa.CheckConstraint(
            "end_time IS NULL OR end_time > start_time",
            name=op.f("ck_reservations_valid_time_window"),
        ),
        sa.CheckConstraint("party_size > 0", name=op.f("ck_reservations_valid_party_size")),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["staff_users.id"],
            name=op.f("fk_reservations_approved_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_reservations_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_reservations_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_reservations_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["dining_area_id"],
            ["dining_areas.id"],
            name=op.f("fk_reservations_dining_area_id_dining_areas"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_reservations_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by"],
            ["staff_users.id"],
            name=op.f("fk_reservations_rejected_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_reservations_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
        sa.UniqueConstraint("reservation_number", name=op.f("uq_reservations_reservation_number")),
    )
    op.create_index(
        "ix_reservations_assigned_staff_id", "reservations", ["assigned_staff_id"], unique=False
    )
    op.create_index("ix_reservations_customer_id", "reservations", ["customer_id"], unique=False)
    op.create_index(
        "ix_reservations_date_start_time",
        "reservations",
        ["reservation_date", "start_time"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_dining_area_id", "reservations", ["dining_area_id"], unique=False
    )
    op.create_index("ix_reservations_order_id", "reservations", ["order_id"], unique=False)
    op.create_index("ix_reservations_status", "reservations", ["status"], unique=False)
    op.create_index(
        "uq_reservations_idempotency_key",
        "reservations",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "reservation_notes",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("note_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "note_type IN ('internal', 'kitchen', 'guest_preference', 'allergy', "
            "'special_occasion', 'accessibility', 'celebration', 'vip')",
            name=op.f("ck_reservation_notes_valid_note_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_notes_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_notes_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_notes_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_notes_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_notes")),
    )
    op.create_index(
        "ix_reservation_notes_reservation_id", "reservation_notes", ["reservation_id"], unique=False
    )
    op.create_table(
        "reservation_status_history",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_reservation_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_status_history_reservation_id_reservations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_status_history")),
    )
    op.create_index(
        "ix_reservation_status_history_reservation_id",
        "reservation_status_history",
        ["reservation_id"],
        unique=False,
    )
    op.create_table(
        "reservation_table_assignments",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_table_id", sa.Uuid(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("unassigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_table_assignments_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_table_assignments_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_table_id"],
            ["restaurant_tables.id"],
            name=op.f("fk_reservation_table_assignments_restaurant_table_id_restaurant_tables"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_table_assignments")),
    )
    op.create_index(
        "ix_reservation_table_assignments_reservation_id",
        "reservation_table_assignments",
        ["reservation_id"],
        unique=False,
    )
    op.create_index(
        "ix_reservation_table_assignments_table_id",
        "reservation_table_assignments",
        ["restaurant_table_id"],
        unique=False,
    )
    op.create_index(
        "uq_reservation_table_assignments_active",
        "reservation_table_assignments",
        ["reservation_id", "restaurant_table_id"],
        unique=True,
        postgresql_where=sa.text("unassigned_at IS NULL"),
    )
    op.create_table(
        "reservation_tag_links",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_tag_links_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_tag_links_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["reservation_tags.id"],
            name=op.f("fk_reservation_tag_links_tag_id_reservation_tags"),
        ),
        sa.PrimaryKeyConstraint("reservation_id", "tag_id", name="pk_reservation_tag_links"),
    )
    op.create_table(
        "reservation_timeline",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('created', 'edited', 'confirmed', 'assigned', 'checked_in', "
            "'moved', 'cancelled', 'completed', 'no_show', 'waitlisted', 'promoted', "
            "'status_changed')",
            name=op.f("ck_reservation_timeline_valid_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_timeline_performed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_timeline_reservation_id_reservations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_timeline")),
    )
    op.create_index(
        "ix_reservation_timeline_reservation_id",
        "reservation_timeline",
        ["reservation_id"],
        unique=False,
    )
    op.create_table(
        "reservation_waitlist",
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("guest_name", sa.String(length=180), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("dining_area_id", sa.Uuid(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("estimated_wait_minutes", sa.Integer(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_reservation_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('waiting', 'notified', 'promoted', 'cancelled', 'expired')",
            name=op.f("ck_reservation_waitlist_valid_status"),
        ),
        sa.CheckConstraint("party_size > 0", name=op.f("ck_reservation_waitlist_valid_party_size")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_waitlist_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_reservation_waitlist_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["dining_area_id"],
            ["dining_areas.id"],
            name=op.f("fk_reservation_waitlist_dining_area_id_dining_areas"),
        ),
        sa.ForeignKeyConstraint(
            ["promoted_reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_waitlist_promoted_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_reservation_waitlist_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_waitlist")),
    )
    op.create_index(
        "ix_reservation_waitlist_customer_id", "reservation_waitlist", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_reservation_waitlist_dining_area_id",
        "reservation_waitlist",
        ["dining_area_id"],
        unique=False,
    )
    op.create_index(
        "ix_reservation_waitlist_status", "reservation_waitlist", ["status"], unique=False
    )
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _RESERVATION_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reservation_waitlist_status", table_name="reservation_waitlist")
    op.drop_index("ix_reservation_waitlist_dining_area_id", table_name="reservation_waitlist")
    op.drop_index("ix_reservation_waitlist_customer_id", table_name="reservation_waitlist")
    op.drop_table("reservation_waitlist")
    op.drop_index("ix_reservation_timeline_reservation_id", table_name="reservation_timeline")
    op.drop_table("reservation_timeline")
    op.drop_table("reservation_tag_links")
    op.drop_index(
        "uq_reservation_table_assignments_active",
        table_name="reservation_table_assignments",
        postgresql_where=sa.text("unassigned_at IS NULL"),
    )
    op.drop_index(
        "ix_reservation_table_assignments_table_id", table_name="reservation_table_assignments"
    )
    op.drop_index(
        "ix_reservation_table_assignments_reservation_id",
        table_name="reservation_table_assignments",
    )
    op.drop_table("reservation_table_assignments")
    op.drop_index(
        "ix_reservation_status_history_reservation_id", table_name="reservation_status_history"
    )
    op.drop_table("reservation_status_history")
    op.drop_index("ix_reservation_notes_reservation_id", table_name="reservation_notes")
    op.drop_table("reservation_notes")
    op.drop_index(
        "uq_reservations_idempotency_key",
        table_name="reservations",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_reservations_status", table_name="reservations")
    op.drop_index("ix_reservations_order_id", table_name="reservations")
    op.drop_index("ix_reservations_dining_area_id", table_name="reservations")
    op.drop_index("ix_reservations_date_start_time", table_name="reservations")
    op.drop_index("ix_reservations_customer_id", table_name="reservations")
    op.drop_index("ix_reservations_assigned_staff_id", table_name="reservations")
    op.drop_table("reservations")
    op.drop_index("ix_table_status_history_table_id", table_name="table_status_history")
    op.drop_table("table_status_history")
    op.drop_index("ix_table_blocks_table_id", table_name="table_blocks")
    op.drop_index("ix_table_blocks_active_window", table_name="table_blocks")
    op.drop_table("table_blocks")
    op.drop_index(
        "uq_restaurant_tables_qr_identifier",
        table_name="restaurant_tables",
        postgresql_where=sa.text("qr_identifier IS NOT NULL"),
    )
    op.drop_index(
        "uq_restaurant_tables_number",
        table_name="restaurant_tables",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_restaurant_tables_status", table_name="restaurant_tables")
    op.drop_index("ix_restaurant_tables_dining_area_id", table_name="restaurant_tables")
    op.drop_table("restaurant_tables")
    op.drop_table("reservation_settings")
    op.drop_table("reservation_policies")
    op.drop_index(
        "uq_holiday_calendar_active_date",
        table_name="holiday_calendar",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("holiday_calendar")
    op.drop_index(
        "ix_dining_areas_active",
        table_name="dining_areas",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_table("dining_areas")
    op.drop_table("business_hours")
    op.drop_table("reservation_tags")
    # ### end Alembic commands ###
