"""add_phase15_jobs_integrations_dead_letter_and_ops_settings

Revision ID: 4edacdc2f990
Revises: 54c9b668a050
Create Date: 2026-08-01 21:06:37.901604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4edacdc2f990"
down_revision: str | Sequence[str] | None = "54c9b668a050"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PHASE15_TABLES = (
    "dead_letter_entries",
    "feature_flags",
    "integrations",
    "operational_settings",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letter_entries",
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("original_type", sa.String(length=120), nullable=False),
        sa.Column("payload_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("failure_category", sa.String(length=64), nullable=True),
        sa.Column("final_error_summary", sa.Text(), nullable=True),
        sa.Column("attempt_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dead_letter_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_staff_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_status", sa.String(length=24), nullable=False),
        sa.Column("replay_eligible", sa.Boolean(), nullable=False),
        sa.Column("replay_actor_id", sa.Uuid(), nullable=True),
        sa.Column("replay_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "resolution_status IN ('new', 'investigating', 'corrected', 'replay_ready', "
            "'replayed', 'ignored_with_reason', 'permanently_closed')",
            name=op.f("ck_dead_letter_entries_valid_resolution_status"),
        ),
        sa.CheckConstraint(
            "source_type IN ('job', 'outbox_event')",
            name=op.f("ck_dead_letter_entries_valid_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_dead_letter_entries_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_dead_letter_entries_owner_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["replay_actor_id"],
            ["staff_users.id"],
            name=op.f("fk_dead_letter_entries_replay_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_dead_letter_entries_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letter_entries")),
    )
    op.create_index(
        "ix_dead_letter_entries_resolution_status",
        "dead_letter_entries",
        ["resolution_status"],
        unique=False,
    )
    op.create_index(
        "ix_dead_letter_entries_source",
        "dead_letter_entries",
        ["source_type", "source_id"],
        unique=False,
    )
    op.create_table(
        "feature_flags",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_feature_flags_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_feature_flags_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("code", name="uq_feature_flags_code"),
    )
    op.create_table(
        "integrations",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("provider_code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("credential_reference", sa.String(length=200), nullable=True),
        sa.Column("credential_last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("webhook_configured", sa.Boolean(), nullable=False),
        sa.Column("base_endpoint", sa.String(length=300), nullable=True),
        sa.Column("default_sender", sa.String(length=200), nullable=True),
        sa.Column("rate_limit_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_policy_reference", sa.String(length=80), nullable=True),
        sa.Column("capability_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("health_state", sa.String(length=16), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_category", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category IN ('authentication_identity', 'database_storage', 'email', 'whatsapp', "
            "'sms', 'file_storage_exports', 'ai_provider', 'analytics_observability')",
            name=op.f("ck_integrations_valid_category"),
        ),
        sa.CheckConstraint(
            "environment IN ('local', 'test', 'staging', 'production')",
            name=op.f("ck_integrations_valid_environment"),
        ),
        sa.CheckConstraint(
            "health_state IN ('unknown', 'healthy', 'degraded', 'unhealthy', 'disabled')",
            name=op.f("ck_integrations_valid_health_state"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'configuring', 'validating', 'active', 'degraded', 'paused', "
            "'disabled', 'failed', 'revoked', 'archived')",
            name=op.f("ck_integrations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_integrations_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_integrations_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("code", name="uq_integrations_code"),
    )
    op.create_index("ix_integrations_category", "integrations", ["category"], unique=False)
    op.create_index("ix_integrations_health_state", "integrations", ["health_state"], unique=False)
    op.create_table(
        "operational_settings",
        sa.Column("singleton_guard", sa.Boolean(), nullable=False),
        sa.Column("maintenance_mode_enabled", sa.Boolean(), nullable=False),
        sa.Column("maintenance_message", sa.Text(), nullable=True),
        sa.Column("scheduler_enabled", sa.Boolean(), nullable=False),
        sa.Column("default_max_attempts", sa.Integer(), nullable=False),
        sa.Column("default_retry_backoff_seconds", sa.Integer(), nullable=False),
        sa.Column("default_retry_backoff_cap_seconds", sa.Integer(), nullable=False),
        sa.Column("worker_max_jobs", sa.Integer(), nullable=False),
        sa.Column("worker_job_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("queue_priority_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "notification_channel_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("active_ai_provider_code", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "default_max_attempts > 0",
            name=op.f("ck_operational_settings_valid_default_max_attempts"),
        ),
        sa.CheckConstraint(
            "default_retry_backoff_cap_seconds >= default_retry_backoff_seconds",
            name=op.f("ck_operational_settings_valid_default_retry_backoff_cap_seconds"),
        ),
        sa.CheckConstraint(
            "default_retry_backoff_seconds > 0",
            name=op.f("ck_operational_settings_valid_default_retry_backoff_seconds"),
        ),
        sa.CheckConstraint(
            "singleton_guard", name=op.f("ck_operational_settings_valid_singleton_guard")
        ),
        sa.CheckConstraint(
            "worker_job_timeout_seconds > 0",
            name=op.f("ck_operational_settings_valid_worker_job_timeout_seconds"),
        ),
        sa.CheckConstraint(
            "worker_max_jobs > 0", name=op.f("ck_operational_settings_valid_worker_max_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_operational_settings_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_operational_settings_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operational_settings")),
        sa.UniqueConstraint(
            "singleton_guard", name=op.f("uq_operational_settings_singleton_guard")
        ),
    )
    # NOTE: autogenerate also proposed dropping/recreating
    # `fk_feedback_entries_converted_to_complaint_id_complaints` — the same
    # Phase 13 deferred-FK false positive documented in the Phase 14
    # migration (added via a raw `op.create_foreign_key` outside the
    # declarative model, so it isn't present in SQLAlchemy metadata for
    # autogenerate to diff against). That unrelated churn has been removed
    # from this migration.
    op.add_column(
        "job_records",
        sa.Column("queue_name", sa.String(length=32), nullable=False, server_default="maintenance"),
    )
    op.add_column(
        "job_records",
        sa.Column("priority", sa.String(length=16), nullable=False, server_default="normal"),
    )
    op.alter_column("job_records", "queue_name", server_default=None)
    op.alter_column("job_records", "priority", server_default=None)
    op.create_check_constraint(
        "valid_queue_name",
        "job_records",
        "queue_name IN ('critical-domain', 'communications', 'campaigns', 'reports', 'exports', "
        "'integrations', 'ai', 'maintenance')",
    )
    op.create_check_constraint(
        "valid_priority",
        "job_records",
        "priority IN ('critical', 'high', 'normal', 'low', 'maintenance')",
    )
    op.create_index(
        "ix_job_records_queue_status", "job_records", ["queue_name", "status"], unique=False
    )
    # ### end Alembic commands ###

    for table_name in _PHASE15_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_records_queue_status", table_name="job_records")
    op.drop_constraint("valid_priority", "job_records", type_="check")
    op.drop_constraint("valid_queue_name", "job_records", type_="check")
    op.drop_column("job_records", "priority")
    op.drop_column("job_records", "queue_name")
    op.drop_table("operational_settings")
    op.drop_index("ix_integrations_health_state", table_name="integrations")
    op.drop_index("ix_integrations_category", table_name="integrations")
    op.drop_table("integrations")
    op.drop_table("feature_flags")
    op.drop_index("ix_dead_letter_entries_source", table_name="dead_letter_entries")
    op.drop_index("ix_dead_letter_entries_resolution_status", table_name="dead_letter_entries")
    op.drop_table("dead_letter_entries")
    # ### end Alembic commands ###
