"""add_phase5_customers_and_leads

Revision ID: 523aed98ebd1
Revises: 68a3f066b2b9
Create Date: 2026-07-26 07:45:02.903000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "523aed98ebd1"
down_revision: str | Sequence[str] | None = "68a3f066b2b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_tags_normalized_name")),
    )
    op.create_table(
        "customers",
        sa.Column("customer_number", sa.String(length=32), nullable=False),
        sa.Column("customer_type", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("organization_name", sa.String(length=180), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("primary_phone_e164", sa.String(length=20), nullable=True),
        sa.Column("primary_email", postgresql.CITEXT(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("anniversary_date", sa.Date(), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), nullable=True),
        sa.Column("dietary_preference", sa.String(length=32), nullable=True),
        sa.Column("spice_preference", sa.String(length=32), nullable=True),
        sa.Column("customer_status", sa.String(length=32), nullable=False),
        sa.Column("customer_segment", sa.String(length=32), nullable=True),
        sa.Column("acquisition_source", sa.String(length=64), nullable=True),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("first_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_order_count", sa.Integer(), nullable=False),
        sa.Column("lifetime_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("average_order_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_into_customer_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "customer_segment IS NULL OR customer_segment IN ('new', 'repeat', 'loyal', "
            "'vip', 'at_risk', 'dormant', 'high_aov', 'family', "
            "'corporate', 'college_group', 'delivery_first', 'dine_in_first', "
            "'discount_sensitive', 'complaint_recovery')",
            name=op.f("ck_customers_valid_customer_segment"),
        ),
        sa.CheckConstraint(
            "customer_status IN ('active', 'inactive', 'blacklisted', 'archived', 'merged')",
            name=op.f("ck_customers_valid_customer_status"),
        ),
        sa.CheckConstraint(
            "customer_type IN ('individual', 'corporate')",
            name=op.f("ck_customers_valid_customer_type"),
        ),
        sa.CheckConstraint(
            "dietary_preference IS NULL OR dietary_preference IN ('vegetarian', "
            "'non_vegetarian', 'vegan', 'jain', 'no_preference')",
            name=op.f("ck_customers_valid_dietary_preference"),
        ),
        sa.CheckConstraint(
            "spice_preference IS NULL OR spice_preference IN ('mild', "
            "'medium', 'spicy', 'extra_spicy')",
            name=op.f("ck_customers_valid_spice_preference"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_customers_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_customers_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_customers_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_customer_id"],
            ["customers.id"],
            name=op.f("fk_customers_merged_into_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_customers_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("customer_number", name=op.f("uq_customers_customer_number")),
    )
    op.create_index(
        "ix_customers_active",
        "customers",
        ["customer_status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND customer_status = 'active'"),
    )
    op.create_index(
        "ix_customers_assigned_staff_id", "customers", ["assigned_staff_id"], unique=False
    )
    op.create_index("ix_customers_last_order_at", "customers", ["last_order_at"], unique=False)
    op.create_index("ix_customers_primary_email", "customers", ["primary_email"], unique=False)
    op.create_index(
        "ix_customers_primary_phone_e164", "customers", ["primary_phone_e164"], unique=False
    )
    op.create_index(
        "ix_customers_status_segment",
        "customers",
        ["customer_status", "customer_segment"],
        unique=False,
    )
    op.create_table(
        "customer_addresses",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("recipient_name", sa.String(length=160), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("address_line1", sa.String(length=200), nullable=False),
        sa.Column("address_line2", sa.String(length=200), nullable=True),
        sa.Column("landmark", sa.String(length=160), nullable=True),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("delivery_instructions", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_addresses_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_addresses_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_addresses_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_addresses_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_addresses")),
    )
    op.create_index(
        "ix_customer_addresses_customer_id", "customer_addresses", ["customer_id"], unique=False
    )
    op.create_index(
        "uq_customer_addresses_default_per_customer",
        "customer_addresses",
        ["customer_id"],
        unique=True,
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.create_table(
        "customer_consents",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("consent_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column("captured_text", sa.Text(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consent_type IN ('whatsapp_marketing', 'email_marketing', 'sms_marketing', "
            "'loyalty', 'feedback_request', 'personalization')",
            name=op.f("ck_customer_consents_valid_consent_type"),
        ),
        sa.CheckConstraint(
            "status IN ('granted', 'withdrawn', 'unknown')",
            name=op.f("ck_customer_consents_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_consents_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_consents")),
        sa.UniqueConstraint(
            "customer_id", "consent_type", name="uq_customer_consents_customer_type"
        ),
    )
    op.create_table(
        "customer_merge_events",
        sa.Column("source_customer_id", sa.Uuid(), nullable=False),
        sa.Column("surviving_customer_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mapping_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_customer_merge_events_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_merge_events_source_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["surviving_customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_merge_events_surviving_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_merge_events")),
    )
    op.create_table(
        "customer_notes",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("note_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "note_type IN ('general', 'service_preference', 'complaint', 'recovery', "
            "'corporate', 'delivery', 'reservation', 'dietary')",
            name=op.f("ck_customer_notes_valid_note_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_notes_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_customer_notes_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_notes_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_notes_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_notes")),
    )
    op.create_index(
        "ix_customer_notes_customer_id", "customer_notes", ["customer_id"], unique=False
    )
    op.create_table(
        "customer_preferences",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("vegetarian", sa.Boolean(), nullable=False),
        sa.Column("vegan", sa.Boolean(), nullable=False),
        sa.Column("jain", sa.Boolean(), nullable=False),
        sa.Column("allergen_notes", sa.Text(), nullable=True),
        sa.Column("favorite_product_note", sa.String(length=200), nullable=True),
        sa.Column("preferred_order_channel", sa.String(length=32), nullable=True),
        sa.Column("preferred_seating_zone", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_preferences_customer_id_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_preferences")),
        sa.UniqueConstraint("customer_id", name=op.f("uq_customer_preferences_customer_id")),
    )
    op.create_table(
        "customer_tags",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_tags_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_customer_tags_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_customer_tags_tag_id_tags")),
        sa.PrimaryKeyConstraint("customer_id", "tag_id", name="pk_customer_tags"),
    )
    op.create_table(
        "leads",
        sa.Column("lead_number", sa.String(length=32), nullable=False),
        sa.Column("lead_type", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("organization_name", sa.String(length=200), nullable=True),
        sa.Column("contact_name", sa.String(length=160), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("campaign_reference", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("estimated_value_minor", sa.BigInteger(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=True),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("requested_time", sa.Time(), nullable=True),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("won_customer_id", sa.Uuid(), nullable=True),
        sa.Column("lost_reason", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("do_not_contact", sa.Boolean(), nullable=False),
        sa.Column("last_contact_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("qualification_notes", sa.Text(), nullable=True),
        sa.Column("food_preferences", sa.Text(), nullable=True),
        sa.Column("budget_notes", sa.Text(), nullable=True),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("converted_by", sa.Uuid(), nullable=True),
        sa.Column("conversion_idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "lead_type IN ('corporate_catering', 'recurring_office_order', "
            "'event_booking', 'group_dining', "
            "'partnership', 'franchise_or_business_enquiry', 'general_sales_enquiry')",
            name=op.f("ck_leads_valid_lead_type"),
        ),
        sa.CheckConstraint(
            "lost_reason IS NULL OR lost_reason IN ('budget', 'timing', 'no_response', "
            "'chose_competitor', "
            "'service_unavailable', 'location_issue', 'menu_mismatch', 'duplicate', "
            "'invalid_enquiry')",
            name=op.f("ck_leads_valid_lost_reason"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')", name=op.f("ck_leads_valid_priority")
        ),
        sa.CheckConstraint(
            "source IN ('website', 'phone', 'walk_in', 'whatsapp', 'zomato_import', "
            "'swiggy_import', 'meta_campaign', "
            "'google_campaign', 'referral', 'corporate_outreach', 'event_enquiry', 'offline_qr')",
            name=op.f("ck_leads_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('new', 'contacted', 'qualified', 'interested', 'follow_up_scheduled', "
            "'proposal_shared', 'negotiating', 'won', 'lost', 'closed')",
            name=op.f("ck_leads_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_leads_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["converted_by"], ["staff_users.id"], name=op.f("fk_leads_converted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_leads_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_leads_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_leads_updated_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["won_customer_id"], ["customers.id"], name=op.f("fk_leads_won_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("lead_number", name=op.f("uq_leads_lead_number")),
    )
    op.create_index(
        "ix_leads_active",
        "leads",
        ["status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_leads_assigned_staff_next_follow_up",
        "leads",
        ["assigned_staff_id", "next_follow_up_at"],
        unique=False,
    )
    op.create_index("ix_leads_priority", "leads", ["priority"], unique=False)
    op.create_index("ix_leads_requested_date", "leads", ["requested_date"], unique=False)
    op.create_index("ix_leads_source_created_at", "leads", ["source", "created_at"], unique=False)
    op.create_index("ix_leads_status_created_at", "leads", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_leads_conversion_idempotency_key",
        "leads",
        ["conversion_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("conversion_idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "lead_activities",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "activity_type IN ('call', 'email', 'whatsapp', 'meeting', 'proposal', "
            "'note', 'status_change', 'assignment', "
            "'follow_up_created', 'follow_up_completed', 'file_added', 'customer_conversion', "
            "'order_conversion')",
            name=op.f("ck_lead_activities_valid_activity_type"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_activities_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["staff_users.id"],
            name=op.f("fk_lead_activities_performed_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_activities")),
    )
    op.create_index("ix_lead_activities_lead_id", "lead_activities", ["lead_id"], unique=False)
    op.create_table(
        "lead_follow_ups",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('scheduled', 'due', 'completed', 'cancelled', 'missed')",
            name=op.f("ck_lead_follow_ups_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["staff_users.id"],
            name=op.f("fk_lead_follow_ups_assigned_to_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["staff_users.id"],
            name=op.f("fk_lead_follow_ups_completed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_lead_follow_ups_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_follow_ups_lead_id_leads")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_lead_follow_ups_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_follow_ups")),
    )
    op.create_index(
        "ix_lead_follow_ups_assigned_to_scheduled_at",
        "lead_follow_ups",
        ["assigned_to", "scheduled_at"],
        unique=False,
    )
    op.create_index("ix_lead_follow_ups_lead_id", "lead_follow_ups", ["lead_id"], unique=False)
    op.create_index(
        "ix_lead_follow_ups_overdue",
        "lead_follow_ups",
        ["scheduled_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('scheduled', 'due')"),
    )
    op.create_table(
        "lead_status_history",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_lead_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_status_history_lead_id_leads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_status_history")),
    )
    op.create_index(
        "ix_lead_status_history_lead_id", "lead_status_history", ["lead_id"], unique=False
    )
    # ### end Alembic commands ###

    # Enable RLS with no policies on every table this migration creates —
    # SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5, added as a
    # requirement after Phase 3 shipped without it (see migration
    # 68a3f066b2b9). Blocks Supabase's public REST API (the anon key is
    # public); apps/api is unaffected since it connects as the
    # table-owning role, not through PostgREST.
    for table in (
        "tags",
        "customers",
        "customer_addresses",
        "customer_consents",
        "customer_merge_events",
        "customer_notes",
        "customer_preferences",
        "customer_tags",
        "leads",
        "lead_activities",
        "lead_follow_ups",
        "lead_status_history",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lead_status_history_lead_id", table_name="lead_status_history")
    op.drop_table("lead_status_history")
    op.drop_index(
        "ix_lead_follow_ups_overdue",
        table_name="lead_follow_ups",
        postgresql_where=sa.text("status IN ('scheduled', 'due')"),
    )
    op.drop_index("ix_lead_follow_ups_lead_id", table_name="lead_follow_ups")
    op.drop_index("ix_lead_follow_ups_assigned_to_scheduled_at", table_name="lead_follow_ups")
    op.drop_table("lead_follow_ups")
    op.drop_index("ix_lead_activities_lead_id", table_name="lead_activities")
    op.drop_table("lead_activities")
    op.drop_index(
        "uq_leads_conversion_idempotency_key",
        table_name="leads",
        postgresql_where=sa.text("conversion_idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_leads_status_created_at", table_name="leads")
    op.drop_index("ix_leads_source_created_at", table_name="leads")
    op.drop_index("ix_leads_requested_date", table_name="leads")
    op.drop_index("ix_leads_priority", table_name="leads")
    op.drop_index("ix_leads_assigned_staff_next_follow_up", table_name="leads")
    op.drop_index(
        "ix_leads_active", table_name="leads", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("leads")
    op.drop_table("customer_tags")
    op.drop_table("customer_preferences")
    op.drop_index("ix_customer_notes_customer_id", table_name="customer_notes")
    op.drop_table("customer_notes")
    op.drop_table("customer_merge_events")
    op.drop_table("customer_consents")
    op.drop_index(
        "uq_customer_addresses_default_per_customer",
        table_name="customer_addresses",
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.drop_index("ix_customer_addresses_customer_id", table_name="customer_addresses")
    op.drop_table("customer_addresses")
    op.drop_index("ix_customers_status_segment", table_name="customers")
    op.drop_index("ix_customers_primary_phone_e164", table_name="customers")
    op.drop_index("ix_customers_primary_email", table_name="customers")
    op.drop_index("ix_customers_last_order_at", table_name="customers")
    op.drop_index("ix_customers_assigned_staff_id", table_name="customers")
    op.drop_index(
        "ix_customers_active",
        table_name="customers",
        postgresql_where=sa.text("deleted_at IS NULL AND customer_status = 'active'"),
    )
    op.drop_table("customers")
    op.drop_table("tags")
    # ### end Alembic commands ###
