"""add_phase14_reports_analytics_and_controlled_ai

Revision ID: 54c9b668a050
Revises: 271354f4adbf
Create Date: 2026-08-01 14:56:28.231378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54c9b668a050"
down_revision: str | Sequence[str] | None = "271354f4adbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PHASE14_TABLES = (
    "ai_prompt_templates",
    "ai_requests",
    "anomaly_rules",
    "forecast_definitions",
    "report_definitions",
    "ai_request_feedback",
    "ai_source_references",
    "anomaly_findings",
    "forecast_snapshots",
    "report_definition_shares",
    "report_runs",
    "scheduled_reports",
    "export_artifacts",
    "report_run_datasets",
    "scheduled_report_recipients",
    "report_delivery_attempts",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_prompt_templates",
        sa.Column("feature_code", sa.String(length=48), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("allowed_input_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prohibited_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_context_tokens", sa.Integer(), nullable=True),
        sa.Column("safety_constraints", sa.Text(), nullable=True),
        sa.Column("model_config_reference", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "feature_code IN ('customer_history_summary', 'conversation_summary', "
            "'reply_draft', 'lead_status_summary', 'lead_next_action_suggestion', "
            "'campaign_performance_summary', 'campaign_observation_suggestion', "
            "'feedback_theme_summary', 'feedback_categorization', 'root_cause_hypothesis', "
            "'product_performance_summary', 'metric_change_explanation', "
            "'inventory_risk_summary', 'knowledge_content_draft', 'report_narrative', "
            "'management_review_questions', 'dashboard_summary', 'anomaly_evidence_summary', "
            "'nl_question_query_plan')",
            name=op.f("ck_ai_prompt_templates_valid_feature_code"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_ai_prompt_templates_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_ai_prompt_templates_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_prompt_templates")),
    )
    op.create_index(
        "uq_ai_prompt_templates_feature_version",
        "ai_prompt_templates",
        ["feature_code", "version"],
        unique=True,
    )
    op.create_index(
        "uq_ai_prompt_templates_one_active_per_feature",
        "ai_prompt_templates",
        ["feature_code"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "ai_requests",
        sa.Column("requested_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("feature_code", sa.String(length=48), nullable=False),
        sa.Column("prompt_template_code", sa.String(length=48), nullable=False),
        sa.Column("prompt_template_version", sa.Integer(), nullable=False),
        sa.Column("provider_code", sa.String(length=16), nullable=False),
        sa.Column("model_reference", sa.String(length=80), nullable=False),
        sa.Column("permission_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_record_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("grounding_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_text", sa.Text(), nullable=True),
        sa.Column("output_structured", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_category", sa.String(length=48), nullable=True),
        sa.Column("safety_blocked", sa.Boolean(), nullable=False),
        sa.Column("safety_block_reason", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feature_code IN ('customer_history_summary', 'conversation_summary', "
            "'reply_draft', 'lead_status_summary', 'lead_next_action_suggestion', "
            "'campaign_performance_summary', 'campaign_observation_suggestion', "
            "'feedback_theme_summary', 'feedback_categorization', 'root_cause_hypothesis', "
            "'product_performance_summary', 'metric_change_explanation', "
            "'inventory_risk_summary', 'knowledge_content_draft', 'report_narrative', "
            "'management_review_questions', 'dashboard_summary', 'anomaly_evidence_summary', "
            "'nl_question_query_plan')",
            name=op.f("ck_ai_requests_valid_feature_code"),
        ),
        sa.CheckConstraint(
            "provider_code IN ('openai', 'groq', 'mock')",
            name=op.f("ck_ai_requests_valid_provider_code"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed', 'blocked')",
            name=op.f("ck_ai_requests_valid_status"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_ai_requests_non_negative_input_tokens"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_ai_requests_non_negative_latency"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_ai_requests_non_negative_output_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_ai_requests_requested_by_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_requests")),
    )
    op.create_index("ix_ai_requests_feature_code", "ai_requests", ["feature_code"], unique=False)
    op.create_index(
        "ix_ai_requests_requested_by_staff_id",
        "ai_requests",
        ["requested_by_staff_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_ai_requests_status", "ai_requests", ["status"], unique=False)
    op.create_table(
        "anomaly_rules",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metric_code", sa.String(length=80), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("comparison_operator", sa.String(length=4), nullable=True),
        sa.Column("threshold_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("rolling_window_periods", sa.Integer(), nullable=True),
        sa.Column("minimum_sample_size", sa.Integer(), nullable=False),
        sa.Column("cooldown_hours", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notify_task", sa.Boolean(), nullable=False),
        sa.Column("notify_role_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "comparison_operator IS NULL OR comparison_operator IN ('gt', 'gte', 'lt', 'lte')",
            name=op.f("ck_anomaly_rules_valid_comparison_operator"),
        ),
        sa.CheckConstraint(
            "rule_type IN ('absolute_threshold', 'pct_change_prior_period', "
            "'rolling_average_deviation', 'count_rate_threshold', "
            "'consecutive_deterioration', 'missing_activity')",
            name=op.f("ck_anomaly_rules_valid_rule_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_anomaly_rules_valid_severity"),
        ),
        sa.CheckConstraint(
            "cooldown_hours >= 0", name=op.f("ck_anomaly_rules_non_negative_cooldown_hours")
        ),
        sa.CheckConstraint(
            "minimum_sample_size >= 1", name=op.f("ck_anomaly_rules_valid_minimum_sample_size")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_anomaly_rules_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_anomaly_rules_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly_rules")),
    )
    op.create_index("ix_anomaly_rules_is_active", "anomaly_rules", ["is_active"], unique=False)
    op.create_index("ix_anomaly_rules_metric_code", "anomaly_rules", ["metric_code"], unique=False)
    op.create_index("uq_anomaly_rules_code", "anomaly_rules", ["code"], unique=True)
    op.create_table(
        "forecast_definitions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("forecast_area", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("method_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target_metric_code", sa.String(length=80), nullable=False),
        sa.Column("dimension_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("minimum_history_periods", sa.Integer(), nullable=False),
        sa.Column("horizon_periods", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "forecast_area IN ('order_volume', 'net_revenue', 'reservation_covers', "
            "'inventory_consumption')",
            name=op.f("ck_forecast_definitions_valid_forecast_area"),
        ),
        sa.CheckConstraint(
            "method IN ('moving_average', 'linear_trend', 'seasonal_naive', "
            "'exponential_smoothing')",
            name=op.f("ck_forecast_definitions_valid_method"),
        ),
        sa.CheckConstraint(
            "horizon_periods >= 1", name=op.f("ck_forecast_definitions_valid_horizon_periods")
        ),
        sa.CheckConstraint(
            "minimum_history_periods >= 1",
            name=op.f("ck_forecast_definitions_valid_minimum_history_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_forecast_definitions_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_forecast_definitions_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_definitions")),
    )
    op.create_index(
        "ix_forecast_definitions_forecast_area",
        "forecast_definitions",
        ["forecast_area"],
        unique=False,
    )
    op.create_index("uq_forecast_definitions_code", "forecast_definitions", ["code"], unique=True)
    op.create_table(
        "report_definitions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("domain", sa.String(length=24), nullable=False),
        sa.Column("definition_type", sa.String(length=16), nullable=False),
        sa.Column("metric_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("default_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("default_window", sa.String(length=20), nullable=False),
        sa.Column("comparison_enabled", sa.Boolean(), nullable=False),
        sa.Column("owner_staff_id", sa.Uuid(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "default_window IN ('today', 'yesterday', 'current_week', 'previous_week', "
            "'current_month', 'previous_month', 'current_quarter', 'previous_quarter', 'custom')",
            name=op.f("ck_report_definitions_valid_default_window"),
        ),
        sa.CheckConstraint(
            "definition_type IN ('system', 'custom')",
            name=op.f("ck_report_definitions_valid_definition_type"),
        ),
        sa.CheckConstraint(
            "domain IN ('executive', 'sales', 'orders', 'customers', 'leads', 'reservations', "
            "'menu_products', 'inventory_suppliers', 'marketing', 'loyalty', 'feedback', "
            "'complaints', 'communication', 'staff_tasks', 'system_operations')",
            name=op.f("ck_report_definitions_valid_domain"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'shared', 'system')",
            name=op.f("ck_report_definitions_valid_visibility"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_report_definitions_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_report_definitions_owner_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_report_definitions_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_definitions")),
    )
    op.create_index("ix_report_definitions_domain", "report_definitions", ["domain"], unique=False)
    op.create_index(
        "ix_report_definitions_owner_staff_id",
        "report_definitions",
        ["owner_staff_id"],
        unique=False,
    )
    op.create_index("uq_report_definitions_code", "report_definitions", ["code"], unique=True)
    op.create_table(
        "ai_request_feedback",
        sa.Column("ai_request_id", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column("outcome_state", sa.String(length=16), nullable=False),
        sa.Column("edited_content", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("feedback_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome_state IN ('accepted', 'edited', 'rejected', 'ignored')",
            name=op.f("ck_ai_request_feedback_valid_outcome_state"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5",
            name=op.f("ck_ai_request_feedback_valid_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_request_id"],
            ["ai_requests.id"],
            name=op.f("fk_ai_request_feedback_ai_request_id_ai_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff_users.id"],
            name=op.f("fk_ai_request_feedback_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_request_feedback")),
    )
    op.create_index(
        "ix_ai_request_feedback_ai_request_id",
        "ai_request_feedback",
        ["ai_request_id"],
        unique=False,
    )
    op.create_table(
        "ai_source_references",
        sa.Column("ai_request_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=48), nullable=False),
        sa.Column("source_id", sa.String(length=160), nullable=False),
        sa.Column("source_label", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ai_request_id"],
            ["ai_requests.id"],
            name=op.f("fk_ai_source_references_ai_request_id_ai_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_source_references")),
    )
    op.create_index(
        "ix_ai_source_references_ai_request_id",
        "ai_source_references",
        ["ai_request_id"],
        unique=False,
    )
    op.create_table(
        "anomaly_findings",
        sa.Column("anomaly_rule_id", sa.Uuid(), nullable=False),
        sa.Column("metric_code", sa.String(length=80), nullable=False),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("baseline_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("expected_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("deviation_pct", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("linked_task_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_anomaly_findings_valid_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'investigating', 'resolved', 'dismissed')",
            name=op.f("ck_anomaly_findings_valid_status"),
        ),
        sa.CheckConstraint(
            "observed_window_end >= observed_window_start",
            name=op.f("ck_anomaly_findings_valid_observed_window_range"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["staff_users.id"],
            name=op.f("fk_anomaly_findings_acknowledged_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["anomaly_rule_id"],
            ["anomaly_rules.id"],
            name=op.f("fk_anomaly_findings_anomaly_rule_id_anomaly_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_task_id"],
            ["task_records.id"],
            name=op.f("fk_anomaly_findings_linked_task_id_task_records"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["staff_users.id"],
            name=op.f("fk_anomaly_findings_resolved_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly_findings")),
    )
    op.create_index(
        "ix_anomaly_findings_anomaly_rule_id", "anomaly_findings", ["anomaly_rule_id"], unique=False
    )
    op.create_index(
        "ix_anomaly_findings_metric_code", "anomaly_findings", ["metric_code"], unique=False
    )
    op.create_index("ix_anomaly_findings_status", "anomaly_findings", ["status"], unique=False)
    op.create_index("uq_anomaly_findings_dedup_key", "anomaly_findings", ["dedup_key"], unique=True)
    op.create_table(
        "forecast_snapshots",
        sa.Column("forecast_definition_id", sa.Uuid(), nullable=False),
        sa.Column("historical_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("historical_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_data_completeness_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("forecast_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence_interval", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assumptions", sa.Text(), nullable=True),
        sa.Column("backtest_mae", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("backtest_mape", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("method_version", sa.String(length=120), nullable=False),
        sa.Column("failure_details", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'insufficient_data', 'failed')",
            name=op.f("ck_forecast_snapshots_valid_status"),
        ),
        sa.CheckConstraint(
            "historical_window_end >= historical_window_start",
            name=op.f("ck_forecast_snapshots_valid_historical_window_range"),
        ),
        sa.CheckConstraint(
            "horizon_end >= horizon_start", name=op.f("ck_forecast_snapshots_valid_horizon_range")
        ),
        sa.CheckConstraint(
            "input_data_completeness_pct IS NULL OR input_data_completeness_pct BETWEEN 0 AND 100",
            name=op.f("ck_forecast_snapshots_valid_completeness_pct"),
        ),
        sa.ForeignKeyConstraint(
            ["forecast_definition_id"],
            ["forecast_definitions.id"],
            name=op.f("fk_forecast_snapshots_forecast_definition_id_forecast_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_snapshots")),
    )
    op.create_index(
        "ix_forecast_snapshots_forecast_definition_id",
        "forecast_snapshots",
        ["forecast_definition_id"],
        unique=False,
    )
    op.create_index("ix_forecast_snapshots_status", "forecast_snapshots", ["status"], unique=False)
    op.create_table(
        "report_definition_shares",
        sa.Column("report_definition_id", sa.Uuid(), nullable=False),
        sa.Column("shared_with_staff_id", sa.Uuid(), nullable=True),
        sa.Column("shared_with_role_code", sa.String(length=64), nullable=True),
        sa.Column("permission_level", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "permission_level IN ('view', 'run')",
            name=op.f("ck_report_definition_shares_valid_permission_level"),
        ),
        sa.CheckConstraint(
            "(shared_with_staff_id IS NOT NULL) != (shared_with_role_code IS NOT NULL)",
            name=op.f("ck_report_definition_shares_exactly_one_share_target"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_report_definition_shares_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["report_definition_id"],
            ["report_definitions.id"],
            name=op.f("fk_report_definition_shares_report_definition_id_report_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_report_definition_shares_shared_with_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_definition_shares")),
    )
    op.create_index(
        "ix_report_definition_shares_report_definition_id",
        "report_definition_shares",
        ["report_definition_id"],
        unique=False,
    )
    op.create_index(
        "uq_report_definition_shares_role",
        "report_definition_shares",
        ["report_definition_id", "shared_with_role_code"],
        unique=True,
        postgresql_where=sa.text("shared_with_role_code IS NOT NULL"),
    )
    op.create_index(
        "uq_report_definition_shares_staff",
        "report_definition_shares",
        ["report_definition_id", "shared_with_staff_id"],
        unique=True,
        postgresql_where=sa.text("shared_with_staff_id IS NOT NULL"),
    )
    op.create_table(
        "report_runs",
        sa.Column("report_definition_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("window_code", sa.String(length=20), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("comparison_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comparison_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("filters_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "metric_versions_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_details", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name=op.f("ck_report_runs_valid_status"),
        ),
        sa.CheckConstraint(
            "trigger_source IN ('manual', 'scheduled', 'system')",
            name=op.f("ck_report_runs_valid_trigger_source"),
        ),
        sa.CheckConstraint(
            "comparison_window_end IS NULL OR comparison_window_start IS NULL "
            "OR comparison_window_end >= comparison_window_start",
            name=op.f("ck_report_runs_valid_comparison_window_range"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_report_runs_non_negative_row_count"),
        ),
        sa.CheckConstraint(
            "window_end >= window_start", name=op.f("ck_report_runs_valid_window_range")
        ),
        sa.ForeignKeyConstraint(
            ["report_definition_id"],
            ["report_definitions.id"],
            name=op.f("fk_report_runs_report_definition_id_report_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_report_runs_requested_by_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_runs")),
    )
    op.create_index("ix_report_runs_created_at", "report_runs", ["created_at"], unique=False)
    op.create_index(
        "ix_report_runs_report_definition_id", "report_runs", ["report_definition_id"], unique=False
    )
    op.create_index(
        "ix_report_runs_requested_by_staff_id",
        "report_runs",
        ["requested_by_staff_id"],
        unique=False,
    )
    op.create_index("ix_report_runs_status", "report_runs", ["status"], unique=False)
    op.create_table(
        "scheduled_reports",
        sa.Column("report_definition_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("schedule_frequency", sa.String(length=8), nullable=False),
        sa.Column("schedule_day_of_week", sa.Integer(), nullable=True),
        sa.Column("schedule_day_of_month", sa.Integer(), nullable=True),
        sa.Column("schedule_time_of_day", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("output_format", sa.String(length=8), nullable=False),
        sa.Column("fixed_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("include_ai_narrative", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(schedule_frequency != 'monthly') OR (schedule_day_of_month IS NOT NULL)",
            name=op.f("ck_scheduled_reports_monthly_requires_day_of_month"),
        ),
        sa.CheckConstraint(
            "(schedule_frequency != 'weekly') OR (schedule_day_of_week IS NOT NULL)",
            name=op.f("ck_scheduled_reports_weekly_requires_day_of_week"),
        ),
        sa.CheckConstraint(
            "output_format IN ('csv', 'xlsx', 'pdf')",
            name=op.f("ck_scheduled_reports_valid_output_format"),
        ),
        sa.CheckConstraint(
            "schedule_frequency IN ('daily', 'weekly', 'monthly')",
            name=op.f("ck_scheduled_reports_valid_frequency"),
        ),
        sa.CheckConstraint(
            "schedule_day_of_month IS NULL OR schedule_day_of_month BETWEEN 1 AND 28",
            name=op.f("ck_scheduled_reports_valid_day_of_month"),
        ),
        sa.CheckConstraint(
            "schedule_day_of_week IS NULL OR schedule_day_of_week BETWEEN 0 AND 6",
            name=op.f("ck_scheduled_reports_valid_day_of_week"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_reports_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["report_definition_id"],
            ["report_definitions.id"],
            name=op.f("fk_scheduled_reports_report_definition_id_report_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_reports_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_reports")),
    )
    op.create_index(
        "ix_scheduled_reports_is_enabled", "scheduled_reports", ["is_enabled"], unique=False
    )
    op.create_index(
        "ix_scheduled_reports_report_definition_id",
        "scheduled_reports",
        ["report_definition_id"],
        unique=False,
    )
    op.create_table(
        "export_artifacts",
        sa.Column("report_run_id", sa.Uuid(), nullable=True),
        sa.Column("export_source", sa.String(length=16), nullable=False),
        sa.Column("requested_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("export_format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("job_record_id", sa.Uuid(), nullable=True),
        sa.Column("storage_bucket", sa.String(length=64), nullable=True),
        sa.Column("storage_path", sa.String(length=300), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_details", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "export_format IN ('csv', 'xlsx', 'pdf')",
            name=op.f("ck_export_artifacts_valid_export_format"),
        ),
        sa.CheckConstraint(
            "export_source IN ('report_run', 'domain_direct')",
            name=op.f("ck_export_artifacts_valid_export_source"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'generating', 'completed', 'failed')",
            name=op.f("ck_export_artifacts_valid_status"),
        ),
        sa.CheckConstraint(
            "file_size_bytes IS NULL OR file_size_bytes >= 0",
            name=op.f("ck_export_artifacts_non_negative_file_size"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_export_artifacts_non_negative_row_count"),
        ),
        sa.ForeignKeyConstraint(
            ["job_record_id"],
            ["job_records.id"],
            name=op.f("fk_export_artifacts_job_record_id_job_records"),
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_export_artifacts_report_run_id_report_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_export_artifacts_requested_by_staff_id_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_artifacts")),
    )
    op.create_index(
        "ix_export_artifacts_expires_at", "export_artifacts", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_export_artifacts_report_run_id", "export_artifacts", ["report_run_id"], unique=False
    )
    op.create_index(
        "ix_export_artifacts_requested_by_staff_id",
        "export_artifacts",
        ["requested_by_staff_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_export_artifacts_status", "export_artifacts", ["status"], unique=False)
    op.create_table(
        "report_run_datasets",
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_report_run_datasets_report_run_id_report_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_run_datasets")),
    )
    op.create_index(
        "uq_report_run_datasets_report_run_id",
        "report_run_datasets",
        ["report_run_id"],
        unique=True,
    )
    op.create_table(
        "scheduled_report_recipients",
        sa.Column("scheduled_report_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_staff_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_role_code", sa.String(length=64), nullable=True),
        sa.Column("recipient_email_override", sa.String(length=320), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(recipient_staff_id IS NOT NULL)::int + (recipient_role_code IS NOT NULL)::int "
            "+ (recipient_email_override IS NOT NULL)::int = 1",
            name=op.f("ck_scheduled_report_recipients_exactly_one_recipient_target"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_scheduled_report_recipients_recipient_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_report_id"],
            ["scheduled_reports.id"],
            name=op.f("fk_scheduled_report_recipients_scheduled_report_id_scheduled_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_report_recipients")),
    )
    op.create_index(
        "ix_scheduled_report_recipients_scheduled_report_id",
        "scheduled_report_recipients",
        ["scheduled_report_id"],
        unique=False,
    )
    op.create_table(
        "report_delivery_attempts",
        sa.Column("scheduled_report_id", sa.Uuid(), nullable=False),
        sa.Column("report_run_id", sa.Uuid(), nullable=True),
        sa.Column("export_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("occurrence_key", sa.String(length=160), nullable=False),
        sa.Column("recipient_reference", sa.String(length=320), nullable=False),
        sa.Column("delivery_channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_details", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_channel IN ('email')",
            name=op.f("ck_report_delivery_attempts_valid_delivery_channel"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'delivered', 'failed')",
            name=op.f("ck_report_delivery_attempts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["export_artifact_id"],
            ["export_artifacts.id"],
            name=op.f("fk_report_delivery_attempts_export_artifact_id_export_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_report_delivery_attempts_report_run_id_report_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_report_id"],
            ["scheduled_reports.id"],
            name=op.f("fk_report_delivery_attempts_scheduled_report_id_scheduled_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_delivery_attempts")),
    )
    op.create_index(
        "uq_report_delivery_attempts_occurrence",
        "report_delivery_attempts",
        ["scheduled_report_id", "occurrence_key", "recipient_reference"],
        unique=True,
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping/recreating
    # `fk_feedback_entries_converted_to_complaint_id_complaints` — a false
    # positive caused by Phase 13's deliberately deferred FK (added via a
    # raw `op.create_foreign_key` outside the declarative model, so it
    # isn't present in SQLAlchemy metadata for autogenerate to diff
    # against). That unrelated churn has been removed from this migration.

    for table_name in _PHASE14_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_report_delivery_attempts_occurrence", table_name="report_delivery_attempts")
    op.drop_table("report_delivery_attempts")
    op.drop_index(
        "ix_scheduled_report_recipients_scheduled_report_id",
        table_name="scheduled_report_recipients",
    )
    op.drop_table("scheduled_report_recipients")
    op.drop_index("uq_report_run_datasets_report_run_id", table_name="report_run_datasets")
    op.drop_table("report_run_datasets")
    op.drop_index("ix_export_artifacts_status", table_name="export_artifacts")
    op.drop_index("ix_export_artifacts_requested_by_staff_id", table_name="export_artifacts")
    op.drop_index("ix_export_artifacts_report_run_id", table_name="export_artifacts")
    op.drop_index("ix_export_artifacts_expires_at", table_name="export_artifacts")
    op.drop_table("export_artifacts")
    op.drop_index("ix_scheduled_reports_report_definition_id", table_name="scheduled_reports")
    op.drop_index("ix_scheduled_reports_is_enabled", table_name="scheduled_reports")
    op.drop_table("scheduled_reports")
    op.drop_index("ix_report_runs_status", table_name="report_runs")
    op.drop_index("ix_report_runs_requested_by_staff_id", table_name="report_runs")
    op.drop_index("ix_report_runs_report_definition_id", table_name="report_runs")
    op.drop_index("ix_report_runs_created_at", table_name="report_runs")
    op.drop_table("report_runs")
    op.drop_index(
        "uq_report_definition_shares_staff",
        table_name="report_definition_shares",
        postgresql_where=sa.text("shared_with_staff_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_report_definition_shares_role",
        table_name="report_definition_shares",
        postgresql_where=sa.text("shared_with_role_code IS NOT NULL"),
    )
    op.drop_index(
        "ix_report_definition_shares_report_definition_id", table_name="report_definition_shares"
    )
    op.drop_table("report_definition_shares")
    op.drop_index("ix_forecast_snapshots_status", table_name="forecast_snapshots")
    op.drop_index("ix_forecast_snapshots_forecast_definition_id", table_name="forecast_snapshots")
    op.drop_table("forecast_snapshots")
    op.drop_index("uq_anomaly_findings_dedup_key", table_name="anomaly_findings")
    op.drop_index("ix_anomaly_findings_status", table_name="anomaly_findings")
    op.drop_index("ix_anomaly_findings_metric_code", table_name="anomaly_findings")
    op.drop_index("ix_anomaly_findings_anomaly_rule_id", table_name="anomaly_findings")
    op.drop_table("anomaly_findings")
    op.drop_index("ix_ai_source_references_ai_request_id", table_name="ai_source_references")
    op.drop_table("ai_source_references")
    op.drop_index("ix_ai_request_feedback_ai_request_id", table_name="ai_request_feedback")
    op.drop_table("ai_request_feedback")
    op.drop_index("uq_report_definitions_code", table_name="report_definitions")
    op.drop_index("ix_report_definitions_owner_staff_id", table_name="report_definitions")
    op.drop_index("ix_report_definitions_domain", table_name="report_definitions")
    op.drop_table("report_definitions")
    op.drop_index("uq_forecast_definitions_code", table_name="forecast_definitions")
    op.drop_index("ix_forecast_definitions_forecast_area", table_name="forecast_definitions")
    op.drop_table("forecast_definitions")
    op.drop_index("uq_anomaly_rules_code", table_name="anomaly_rules")
    op.drop_index("ix_anomaly_rules_metric_code", table_name="anomaly_rules")
    op.drop_index("ix_anomaly_rules_is_active", table_name="anomaly_rules")
    op.drop_table("anomaly_rules")
    op.drop_index("ix_ai_requests_status", table_name="ai_requests")
    op.drop_index("ix_ai_requests_requested_by_staff_id", table_name="ai_requests")
    op.drop_index("ix_ai_requests_feature_code", table_name="ai_requests")
    op.drop_table("ai_requests")
    op.drop_index(
        "uq_ai_prompt_templates_one_active_per_feature",
        table_name="ai_prompt_templates",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index("uq_ai_prompt_templates_feature_version", table_name="ai_prompt_templates")
    op.drop_table("ai_prompt_templates")
    # ### end Alembic commands ###
