"""add phase7 orders and order lifecycle

Revision ID: 6c1158e315c2
Revises: b36e4b05396d
Create Date: 2026-07-26 18:57:22.831471

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c1158e315c2"
down_revision: str | Sequence[str] | None = "b36e4b05396d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ORDER_TABLES = (
    "orders",
    "order_items",
    "order_item_modifiers",
    "order_timeline",
    "order_notes",
    "order_status_history",
    "order_payments",
    "order_discounts",
    "order_taxes",
    "order_charges",
    "order_assignments",
    "order_source_metadata",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=16), nullable=False),
        sa.Column("assigned_staff_id", sa.Uuid(), nullable=True),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("charges_minor", sa.BigInteger(), nullable=False),
        sa.Column("grand_total_minor", sa.BigInteger(), nullable=False),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("estimated_completion_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "order_type IN ('dine_in', 'takeaway', 'delivery')",
            name=op.f("ck_orders_valid_order_type"),
        ),
        sa.CheckConstraint(
            "payment_status IN ('pending', 'partial', 'paid', 'refunded', 'failed')",
            name=op.f("ck_orders_valid_payment_status"),
        ),
        sa.CheckConstraint(
            "source IN "
            "('pos', 'walk_in', 'website', 'whatsapp', 'phone_call', 'zomato', 'swiggy', 'manual')",
            name=op.f("ck_orders_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN "
            "('draft', 'pending_confirmation', 'confirmed', 'preparing', 'ready', 'completed', "
            "'cancelled')",
            name=op.f("ck_orders_valid_status"),
        ),
        sa.CheckConstraint("charges_minor >= 0", name=op.f("ck_orders_valid_charges_minor")),
        sa.CheckConstraint("discount_minor >= 0", name=op.f("ck_orders_valid_discount_minor")),
        sa.CheckConstraint(
            "grand_total_minor >= 0", name=op.f("ck_orders_valid_grand_total_minor")
        ),
        sa.CheckConstraint("subtotal_minor >= 0", name=op.f("ck_orders_valid_subtotal_minor")),
        sa.CheckConstraint("tax_minor >= 0", name=op.f("ck_orders_valid_tax_minor")),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_orders_assigned_staff_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_orders_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_orders_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_orders_lead_id_leads")),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_orders_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index(
        "ix_orders_active",
        "orders",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_orders_assigned_staff_id", "orders", ["assigned_staff_id"], unique=False)
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"], unique=False)
    op.create_index("ix_orders_payment_status", "orders", ["payment_status"], unique=False)
    op.create_index("ix_orders_source_created_at", "orders", ["source", "created_at"], unique=False)
    op.create_index("ix_orders_status_created_at", "orders", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_orders_idempotency_key",
        "orders",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "order_assignments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("unassigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_order_assignments_assigned_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_assignments_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff_users.id"], name=op.f("fk_order_assignments_staff_id_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_assignments")),
    )
    op.create_index(
        "ix_order_assignments_order_id", "order_assignments", ["order_id"], unique=False
    )
    op.create_table(
        "order_charges",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("charge_type", sa.String(length=32), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "charge_type IN ('packaging', 'delivery', 'service', 'other')",
            name=op.f("ck_order_charges_valid_charge_type"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_order_charges_valid_amount_minor")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_charges_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_charges")),
    )
    op.create_index("ix_order_charges_order_id", "order_charges", ["order_id"], unique=False)
    op.create_table(
        "order_discounts",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("discount_type", sa.String(length=32), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_type IN "
            "('flat', 'percentage', 'manual', 'coupon_placeholder', 'manager_override')",
            name=op.f("ck_order_discounts_valid_discount_type"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_order_discounts_valid_amount_minor")),
        sa.CheckConstraint(
            "percentage IS NULL OR (percentage >= 0 AND percentage <= 100)",
            name=op.f("ck_order_discounts_valid_percentage"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["staff_users.id"],
            name=op.f("fk_order_discounts_approved_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_order_discounts_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_discounts_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_discounts")),
    )
    op.create_index("ix_order_discounts_order_id", "order_discounts", ["order_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("product_name_snapshot", sa.String(length=180), nullable=False),
        sa.Column("variant_name_snapshot", sa.String(length=120), nullable=True),
        sa.Column("product_code_snapshot", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("final_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("kitchen_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'cancelled')", name=op.f("ck_order_items_valid_status")
        ),
        sa.CheckConstraint("discount_minor >= 0", name=op.f("ck_order_items_valid_discount_minor")),
        sa.CheckConstraint(
            "final_price_minor >= 0", name=op.f("ck_order_items_valid_final_price_minor")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_valid_quantity")),
        sa.CheckConstraint("tax_minor >= 0", name=op.f("ck_order_items_valid_tax_minor")),
        sa.CheckConstraint(
            "unit_price_minor >= 0", name=op.f("ck_order_items_valid_unit_price_minor")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_order_items_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_order_items_updated_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_order_items_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)
    op.create_index("ix_order_items_product_id", "order_items", ["product_id"], unique=False)
    op.create_table(
        "order_notes",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_order_notes_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_order_notes_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_notes_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_order_notes_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_notes")),
    )
    op.create_index("ix_order_notes_order_id", "order_notes", ["order_id"], unique=False)
    op.create_table(
        "order_payments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('cash', 'card', 'upi', 'online')",
            name=op.f("ck_order_payments_valid_method"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'partial', 'paid', 'refunded', 'failed')",
            name=op.f("ck_order_payments_valid_status"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_order_payments_valid_amount_minor")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_payments_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["staff_users.id"],
            name=op.f("fk_order_payments_recorded_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_order_payments_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_payments")),
    )
    op.create_index("ix_order_payments_order_id", "order_payments", ["order_id"], unique=False)
    op.create_table(
        "order_source_metadata",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("external_order_id", sa.Text(), nullable=True),
        sa.Column("external_platform_reference", sa.Text(), nullable=True),
        sa.Column("reconciliation_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_source_metadata_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_order_source_metadata")),
    )
    op.create_index(
        "uq_order_source_metadata_external_order_id",
        "order_source_metadata",
        ["external_order_id"],
        unique=True,
        postgresql_where=sa.text("external_order_id IS NOT NULL"),
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
            name=op.f("fk_order_status_history_actor_id_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_status_history_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        "ix_order_status_history_order_id", "order_status_history", ["order_id"], unique=False
    )
    op.create_table(
        "order_taxes",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("tax_name", sa.String(length=64), nullable=False),
        sa.Column("rate_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_order_taxes_valid_amount_minor")),
        sa.CheckConstraint(
            "rate_percentage IS NULL OR (rate_percentage >= 0 AND rate_percentage <= 100)",
            name=op.f("ck_order_taxes_valid_rate_percentage"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_taxes_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_taxes")),
    )
    op.create_index("ix_order_taxes_order_id", "order_taxes", ["order_id"], unique=False)
    op.create_table(
        "order_timeline",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_type IN "
            "('created', 'assigned', 'status_changed', 'payment_updated', 'note_added', "
            "'cancelled', 'completed', 'manual_edit')",
            name=op.f("ck_order_timeline_valid_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_timeline_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["staff_users.id"],
            name=op.f("fk_order_timeline_performed_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_timeline")),
    )
    op.create_index("ix_order_timeline_order_id", "order_timeline", ["order_id"], unique=False)
    op.create_table(
        "order_item_modifiers",
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("modifier_id", sa.Uuid(), nullable=True),
        sa.Column("modifier_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("price_minor_snapshot", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_minor_snapshot >= 0",
            name=op.f("ck_order_item_modifiers_valid_price_minor_snapshot"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_item_modifiers_valid_quantity")),
        sa.ForeignKeyConstraint(
            ["modifier_id"],
            ["modifiers.id"],
            name=op.f("fk_order_item_modifiers_modifier_id_modifiers"),
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_order_item_modifiers_order_item_id_order_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_item_modifiers")),
    )
    op.create_index(
        "ix_order_item_modifiers_order_item_id",
        "order_item_modifiers",
        ["order_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _ORDER_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_item_modifiers_order_item_id", table_name="order_item_modifiers")
    op.drop_table("order_item_modifiers")
    op.drop_index("ix_order_timeline_order_id", table_name="order_timeline")
    op.drop_table("order_timeline")
    op.drop_index("ix_order_taxes_order_id", table_name="order_taxes")
    op.drop_table("order_taxes")
    op.drop_index("ix_order_status_history_order_id", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(
        "uq_order_source_metadata_external_order_id",
        table_name="order_source_metadata",
        postgresql_where=sa.text("external_order_id IS NOT NULL"),
    )
    op.drop_table("order_source_metadata")
    op.drop_index("ix_order_payments_order_id", table_name="order_payments")
    op.drop_table("order_payments")
    op.drop_index("ix_order_notes_order_id", table_name="order_notes")
    op.drop_table("order_notes")
    op.drop_index("ix_order_items_product_id", table_name="order_items")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_order_discounts_order_id", table_name="order_discounts")
    op.drop_table("order_discounts")
    op.drop_index("ix_order_charges_order_id", table_name="order_charges")
    op.drop_table("order_charges")
    op.drop_index("ix_order_assignments_order_id", table_name="order_assignments")
    op.drop_table("order_assignments")
    op.drop_index(
        "uq_orders_idempotency_key",
        table_name="orders",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_orders_status_created_at", table_name="orders")
    op.drop_index("ix_orders_source_created_at", table_name="orders")
    op.drop_index("ix_orders_payment_status", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_index("ix_orders_assigned_staff_id", table_name="orders")
    op.drop_index(
        "ix_orders_active", table_name="orders", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("orders")
    # ### end Alembic commands ###
