"""add phase8 inventory recipes and stock operations

Revision ID: b34d3dac8a82
Revises: 6c1158e315c2
Create Date: 2026-07-27 00:01:10.153284

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b34d3dac8a82"
down_revision: str | Sequence[str] | None = "6c1158e315c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_INVENTORY_TABLES = (
    "units_of_measure",
    "inventory_categories",
    "storage_locations",
    "suppliers",
    "inventory_items",
    "inventory_batches",
    "stock_movements",
    "stock_balances",
    "stock_receipts",
    "stock_receipt_items",
    "stock_adjustments",
    "wastage_records",
    "stock_transfers",
    "stock_transfer_items",
    "stock_counts",
    "stock_count_lines",
    "recipes",
    "recipe_items",
    "order_inventory_states",
)

# A database-level guard for the append-only stock ledger. This phase's own
# instruction is emphatic ("Posted stock movements must not be edited or
# deleted... Corrections must be made through reversal or compensating
# movements"), and app.inventory.ledger is written to honour that — but a
# rule enforced only in application code is one stray script away from being
# broken, and a corrupted ledger cannot be reconstructed from anything else.
#
# UPDATE is allowed *only* for the two reversal-bookkeeping columns, so
# marking a movement as reversed still works while the recorded fact
# (item, location, quantity, type, cost, actor, time) stays immutable.
# DELETE is refused outright.
_LEDGER_GUARD_FUNCTION = """
CREATE OR REPLACE FUNCTION rkpr_stock_movements_append_only()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'stock_movements is append-only: post a reversal movement instead of deleting %',
            OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
        OR NEW.movement_number IS DISTINCT FROM OLD.movement_number
        OR NEW.inventory_item_id IS DISTINCT FROM OLD.inventory_item_id
        OR NEW.storage_location_id IS DISTINCT FROM OLD.storage_location_id
        OR NEW.batch_id IS DISTINCT FROM OLD.batch_id
        OR NEW.movement_type IS DISTINCT FROM OLD.movement_type
        OR NEW.quantity_delta IS DISTINCT FROM OLD.quantity_delta
        OR NEW.entered_unit_id IS DISTINCT FROM OLD.entered_unit_id
        OR NEW.entered_quantity IS DISTINCT FROM OLD.entered_quantity
        OR NEW.affects_on_hand IS DISTINCT FROM OLD.affects_on_hand
        OR NEW.unit_cost_minor IS DISTINCT FROM OLD.unit_cost_minor
        OR NEW.total_value_minor IS DISTINCT FROM OLD.total_value_minor
        OR NEW.reference_type IS DISTINCT FROM OLD.reference_type
        OR NEW.reference_id IS DISTINCT FROM OLD.reference_id
        OR NEW.source_movement_id IS DISTINCT FROM OLD.source_movement_id
        OR NEW.reason IS DISTINCT FROM OLD.reason
        OR NEW.performed_by IS DISTINCT FROM OLD.performed_by
        OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
        OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
        OR NEW.metadata IS DISTINCT FROM OLD.metadata
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
    THEN
        RAISE EXCEPTION
            'stock_movements is append-only: only reversed_by_movement_id and reversed_at '
            'may be updated (movement %)', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_LEDGER_GUARD_TRIGGER = """
CREATE TRIGGER trg_stock_movements_append_only
BEFORE UPDATE OR DELETE ON stock_movements
FOR EACH ROW EXECUTE FUNCTION rkpr_stock_movements_append_only();
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_categories",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_inventory_categories_valid_sort_order")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_categories_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_categories_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_categories_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_inventory_categories_code")),
    )
    op.create_index(
        "ix_inventory_categories_active",
        "inventory_categories",
        ["sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_table(
        "storage_locations",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location_type", sa.String(length=32), nullable=False),
        sa.Column("allows_negative_stock", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "location_type IN "
            "('kitchen', 'dry_store', 'chilled', 'frozen', 'bar', 'packaging', 'other')",
            name=op.f("ck_storage_locations_valid_location_type"),
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_storage_locations_valid_sort_order")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_storage_locations_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_storage_locations_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_storage_locations_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_locations")),
        sa.UniqueConstraint("code", name=op.f("uq_storage_locations_code")),
    )
    op.create_index(
        "ix_storage_locations_active",
        "storage_locations",
        ["sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("contact_person", sa.String(length=160), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("address_line1", sa.String(length=200), nullable=True),
        sa.Column("address_line2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("supply_categories", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("normal_lead_time_days", sa.Integer(), nullable=True),
        sa.Column("payment_terms", sa.String(length=120), nullable=True),
        sa.Column("minimum_order_value_minor", sa.BigInteger(), nullable=True),
        sa.Column("tax_identifier", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'archived')", name=op.f("ck_suppliers_valid_status")
        ),
        sa.CheckConstraint(
            "minimum_order_value_minor IS NULL OR minimum_order_value_minor >= 0",
            name=op.f("ck_suppliers_valid_minimum_order_value_minor"),
        ),
        sa.CheckConstraint(
            "normal_lead_time_days IS NULL OR normal_lead_time_days >= 0",
            name=op.f("ck_suppliers_valid_normal_lead_time_days"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_suppliers_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_suppliers_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_suppliers_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("supplier_code", name=op.f("uq_suppliers_supplier_code")),
    )
    op.create_index(
        "ix_suppliers_active",
        "suppliers",
        ["name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )
    op.create_index("ix_suppliers_name", "suppliers", ["name"], unique=False)
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("unit_type", sa.String(length=16), nullable=False),
        sa.Column("base_unit_id", sa.Uuid(), nullable=True),
        sa.Column("conversion_factor", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "unit_type IN ('weight', 'volume', 'count')",
            name=op.f("ck_units_of_measure_valid_unit_type"),
        ),
        sa.CheckConstraint(
            "(base_unit_id IS NULL AND conversion_factor = 1) OR base_unit_id IS NOT NULL",
            name=op.f("ck_units_of_measure_base_unit_has_unit_factor"),
        ),
        sa.CheckConstraint(
            "conversion_factor > 0", name=op.f("ck_units_of_measure_valid_conversion_factor")
        ),
        sa.CheckConstraint(
            "decimal_places >= 0 AND decimal_places <= 3",
            name=op.f("ck_units_of_measure_valid_decimal_places"),
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_units_of_measure_valid_sort_order")),
        sa.ForeignKeyConstraint(
            ["base_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_units_of_measure_base_unit_id_units_of_measure"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_units_of_measure_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_units_of_measure_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_units_of_measure_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("code", name=op.f("uq_units_of_measure_code")),
    )
    op.create_index(
        "ix_units_of_measure_active",
        "units_of_measure",
        ["unit_type", "sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_index(
        "ix_units_of_measure_unit_type", "units_of_measure", ["unit_type"], unique=False
    )
    op.create_table(
        "inventory_items",
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("base_unit_id", sa.Uuid(), nullable=False),
        sa.Column("default_purchase_unit_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_conversion_factor", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("default_location_id", sa.Uuid(), nullable=True),
        sa.Column("preferred_supplier_id", sa.Uuid(), nullable=True),
        sa.Column("alternative_supplier_id", sa.Uuid(), nullable=True),
        sa.Column("current_stock", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reserved_stock", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reorder_level", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reorder_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("target_stock", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("minimum_stock", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("maximum_stock", sa.Numeric(precision=16, scale=3), nullable=True),
        sa.Column("standard_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("latest_purchase_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("average_unit_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("is_perishable", sa.Boolean(), nullable=False),
        sa.Column("requires_batch_tracking", sa.Boolean(), nullable=False),
        sa.Column("requires_expiry_tracking", sa.Boolean(), nullable=False),
        sa.Column("allergen_flags", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("supplier_item_code", sa.String(length=64), nullable=True),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("storage_instructions", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("stock_status", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_counted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "stock_status IN "
            "('in_stock', 'low_stock', 'critical_stock', 'out_of_stock', 'reserved', "
            "'quarantined', 'expired', 'damaged', 'under_count_review', 'discontinued')",
            name=op.f("ck_inventory_items_valid_stock_status"),
        ),
        sa.CheckConstraint(
            "NOT requires_expiry_tracking OR requires_batch_tracking",
            name=op.f("ck_inventory_items_expiry_tracking_requires_batch_tracking"),
        ),
        sa.CheckConstraint(
            "average_unit_cost_minor IS NULL OR average_unit_cost_minor >= 0",
            name=op.f("ck_inventory_items_valid_average_unit_cost_minor"),
        ),
        sa.CheckConstraint(
            "latest_purchase_cost_minor IS NULL OR latest_purchase_cost_minor >= 0",
            name=op.f("ck_inventory_items_valid_latest_purchase_cost_minor"),
        ),
        sa.CheckConstraint(
            "lead_time_days IS NULL OR lead_time_days >= 0",
            name=op.f("ck_inventory_items_valid_lead_time_days"),
        ),
        sa.CheckConstraint(
            "maximum_stock IS NULL OR maximum_stock >= 0",
            name=op.f("ck_inventory_items_valid_maximum_stock"),
        ),
        sa.CheckConstraint(
            "minimum_stock >= 0", name=op.f("ck_inventory_items_valid_minimum_stock")
        ),
        sa.CheckConstraint(
            "purchase_conversion_factor IS NULL OR purchase_conversion_factor > 0",
            name=op.f("ck_inventory_items_valid_purchase_conversion_factor"),
        ),
        sa.CheckConstraint(
            "reorder_level >= 0", name=op.f("ck_inventory_items_valid_reorder_level")
        ),
        sa.CheckConstraint(
            "reorder_quantity >= 0", name=op.f("ck_inventory_items_valid_reorder_quantity")
        ),
        sa.CheckConstraint(
            "shelf_life_days IS NULL OR shelf_life_days >= 0",
            name=op.f("ck_inventory_items_valid_shelf_life_days"),
        ),
        sa.CheckConstraint(
            "standard_cost_minor IS NULL OR standard_cost_minor >= 0",
            name=op.f("ck_inventory_items_valid_standard_cost_minor"),
        ),
        sa.CheckConstraint("target_stock >= 0", name=op.f("ck_inventory_items_valid_target_stock")),
        sa.ForeignKeyConstraint(
            ["alternative_supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_inventory_items_alternative_supplier_id_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["base_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_inventory_items_base_unit_id_units_of_measure"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["inventory_categories.id"],
            name=op.f("fk_inventory_items_category_id_inventory_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_items_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["default_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_inventory_items_default_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["default_purchase_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_inventory_items_default_purchase_unit_id_units_of_measure"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_items_deleted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["preferred_supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_inventory_items_preferred_supplier_id_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_items_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
        sa.UniqueConstraint("item_code", name=op.f("uq_inventory_items_item_code")),
    )
    op.create_index(
        "ix_inventory_items_active",
        "inventory_items",
        ["category_id", "name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_index(
        "ix_inventory_items_category_id", "inventory_items", ["category_id"], unique=False
    )
    op.create_index("ix_inventory_items_name", "inventory_items", ["name"], unique=False)
    op.create_index(
        "ix_inventory_items_preferred_supplier_id",
        "inventory_items",
        ["preferred_supplier_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_reorder_watch",
        "inventory_items",
        ["stock_status", "current_stock"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.create_index(
        "ix_inventory_items_stock_status", "inventory_items", ["stock_status"], unique=False
    )
    op.create_index(
        "uq_inventory_items_barcode",
        "inventory_items",
        ["barcode"],
        unique=True,
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.create_table(
        "stock_counts",
        sa.Column("count_number", sa.String(length=40), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'in_progress', 'submitted', 'approved', 'cancelled')",
            name=op.f("ck_stock_counts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_counts_approved_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["counted_by"], ["staff_users.id"], name=op.f("fk_stock_counts_counted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_stock_counts_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_counts_storage_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_counts_submitted_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_stock_counts_updated_by_staff_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_counts")),
        sa.UniqueConstraint("count_number", name=op.f("uq_stock_counts_count_number")),
    )
    op.create_index(
        "ix_stock_counts_location_id", "stock_counts", ["storage_location_id"], unique=False
    )
    op.create_index(
        "ix_stock_counts_status_scheduled",
        "stock_counts",
        ["status", "scheduled_date"],
        unique=False,
    )
    op.create_index(
        "uq_stock_counts_active_per_location",
        "stock_counts",
        ["storage_location_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft', 'in_progress', 'submitted')"),
    )
    op.create_table(
        "stock_receipts",
        sa.Column("receipt_number", sa.String(length=40), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("supplier_reference", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("posted_by", sa.Uuid(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'posted', 'reversed')", name=op.f("ck_stock_receipts_valid_status")
        ),
        sa.CheckConstraint(
            "total_value_minor >= 0", name=op.f("ck_stock_receipts_valid_total_value_minor")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_receipts_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"], ["staff_users.id"], name=op.f("fk_stock_receipts_posted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_receipts_reversed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_receipts_storage_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_stock_receipts_supplier_id_suppliers")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_receipts_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_receipts")),
        sa.UniqueConstraint("receipt_number", name=op.f("uq_stock_receipts_receipt_number")),
    )
    op.create_index(
        "ix_stock_receipts_location_id", "stock_receipts", ["storage_location_id"], unique=False
    )
    op.create_index(
        "ix_stock_receipts_status_received",
        "stock_receipts",
        ["status", "received_date"],
        unique=False,
    )
    op.create_index(
        "ix_stock_receipts_supplier_id", "stock_receipts", ["supplier_id"], unique=False
    )
    op.create_table(
        "stock_transfers",
        sa.Column("transfer_number", sa.String(length=40), nullable=False),
        sa.Column("source_location_id", sa.Uuid(), nullable=False),
        sa.Column("destination_location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("posted_by", sa.Uuid(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'posted', 'reversed')",
            name=op.f("ck_stock_transfers_valid_status"),
        ),
        sa.CheckConstraint(
            "source_location_id <> destination_location_id",
            name=op.f("ck_stock_transfers_source_and_destination_differ"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_transfers_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_transfers_destination_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"], ["staff_users.id"], name=op.f("fk_stock_transfers_posted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_transfers_requested_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_transfers_reversed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_transfers_source_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_transfers_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
        sa.UniqueConstraint("transfer_number", name=op.f("uq_stock_transfers_transfer_number")),
    )
    op.create_index(
        "ix_stock_transfers_destination_location_id",
        "stock_transfers",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_transfers_source_location_id",
        "stock_transfers",
        ["source_location_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_transfers_status_created",
        "stock_transfers",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "inventory_batches",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("batch_code", sa.String(length=80), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("received_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("remaining_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("manufactured_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("unit_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'depleted', 'quarantined', 'expired', 'damaged')",
            name=op.f("ck_inventory_batches_valid_status"),
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at >= received_at::date",
            name=op.f("ck_inventory_batches_expiry_not_before_received"),
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR manufactured_at IS NULL OR expires_at >= manufactured_at",
            name=op.f("ck_inventory_batches_expiry_not_before_manufactured"),
        ),
        sa.CheckConstraint(
            "received_quantity > 0", name=op.f("ck_inventory_batches_valid_received_quantity")
        ),
        sa.CheckConstraint(
            "remaining_quantity <= received_quantity",
            name=op.f("ck_inventory_batches_remaining_not_above_received"),
        ),
        sa.CheckConstraint(
            "remaining_quantity >= 0", name=op.f("ck_inventory_batches_valid_remaining_quantity")
        ),
        sa.CheckConstraint(
            "unit_cost_minor IS NULL OR unit_cost_minor >= 0",
            name=op.f("ck_inventory_batches_valid_unit_cost_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_batches_created_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_inventory_batches_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_inventory_batches_storage_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_inventory_batches_supplier_id_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_inventory_batches_updated_by_staff_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_batches")),
        sa.UniqueConstraint(
            "inventory_item_id", "batch_code", name="uq_inventory_batches_item_code"
        ),
    )
    op.create_index(
        "ix_inventory_batches_expiring",
        "inventory_batches",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text(
            "expires_at IS NOT NULL AND status = 'active' AND remaining_quantity > 0"
        ),
    )
    op.create_index(
        "ix_inventory_batches_fefo",
        "inventory_batches",
        ["inventory_item_id", "expires_at", "received_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active' AND remaining_quantity > 0"),
    )
    op.create_index(
        "ix_inventory_batches_item_id", "inventory_batches", ["inventory_item_id"], unique=False
    )
    op.create_index(
        "ix_inventory_batches_location_id",
        "inventory_batches",
        ["storage_location_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_batches_supplier_id", "inventory_batches", ["supplier_id"], unique=False
    )
    op.create_table(
        "order_inventory_states",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumption_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("estimated_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("consumed_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("post_consumption_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'reserved', 'consumed', 'released', 'skipped')",
            name=op.f("ck_order_inventory_states_valid_state"),
        ),
        sa.CheckConstraint(
            "consumed_cost_minor IS NULL OR consumed_cost_minor >= 0",
            name=op.f("ck_order_inventory_states_valid_consumed_cost_minor"),
        ),
        sa.CheckConstraint(
            "estimated_cost_minor IS NULL OR estimated_cost_minor >= 0",
            name=op.f("ck_order_inventory_states_valid_estimated_cost_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_inventory_states_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_inventory_states")),
    )
    op.create_index(
        "ix_order_inventory_states_state", "order_inventory_states", ["state"], unique=False
    )
    op.create_index(
        "uq_order_inventory_states_order_id", "order_inventory_states", ["order_id"], unique=True
    )
    op.create_table(
        "recipes",
        sa.Column("recipe_code", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("yield_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("yield_unit_id", sa.Uuid(), nullable=True),
        sa.Column("preparation_loss_percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_recipes_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "preparation_loss_percentage >= 0 AND preparation_loss_percentage < 100",
            name=op.f("ck_recipes_valid_preparation_loss_percentage"),
        ),
        sa.CheckConstraint("yield_quantity > 0", name=op.f("ck_recipes_valid_yield_quantity")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_recipes_created_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["staff_users.id"], name=op.f("fk_recipes_deleted_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_recipes_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_recipes_updated_by_staff_users")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_recipes_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["yield_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_recipes_yield_unit_id_units_of_measure"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
        sa.UniqueConstraint("recipe_code", name=op.f("uq_recipes_recipe_code")),
    )
    op.create_index("ix_recipes_product_id", "recipes", ["product_id"], unique=False)
    op.create_index("ix_recipes_variant_id", "recipes", ["variant_id"], unique=False)
    op.create_index(
        "uq_recipes_active_base",
        "recipes",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active AND variant_id IS NULL"),
    )
    op.create_index(
        "uq_recipes_active_variant",
        "recipes",
        ["product_id", "variant_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active AND variant_id IS NOT NULL"),
    )
    op.create_table(
        "stock_balances",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("on_hand_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("allows_negative", sa.Boolean(), nullable=False),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_counted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "on_hand_quantity >= 0 OR allows_negative",
            name=op.f("ck_stock_balances_valid_on_hand_quantity"),
        ),
        sa.CheckConstraint(
            "reserved_quantity <= on_hand_quantity OR allows_negative",
            name=op.f("ck_stock_balances_reserved_not_above_on_hand"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_stock_balances_valid_reserved_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_balances_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_balances_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_balances_storage_location_id_storage_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balances")),
    )
    op.create_index("ix_stock_balances_batch_id", "stock_balances", ["batch_id"], unique=False)
    op.create_index(
        "ix_stock_balances_item_id", "stock_balances", ["inventory_item_id"], unique=False
    )
    op.create_index(
        "ix_stock_balances_location_id", "stock_balances", ["storage_location_id"], unique=False
    )
    op.create_index(
        "ix_stock_balances_with_stock",
        "stock_balances",
        ["inventory_item_id", "storage_location_id"],
        unique=False,
        postgresql_where=sa.text("on_hand_quantity > 0"),
    )
    op.create_index(
        "uq_stock_balances_item_location_batch",
        "stock_balances",
        ["inventory_item_id", "storage_location_id", "batch_id"],
        unique=True,
        postgresql_where=sa.text("batch_id IS NOT NULL"),
    )
    op.create_index(
        "uq_stock_balances_item_location_nobatch",
        "stock_balances",
        ["inventory_item_id", "storage_location_id"],
        unique=True,
        postgresql_where=sa.text("batch_id IS NULL"),
    )
    op.create_table(
        "stock_movements",
        sa.Column("movement_number", sa.String(length=40), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("movement_type", sa.String(length=64), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("entered_unit_id", sa.Uuid(), nullable=True),
        sa.Column("entered_quantity", sa.Numeric(precision=16, scale=3), nullable=True),
        sa.Column("affects_on_hand", sa.Boolean(), nullable=False),
        sa.Column("unit_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("total_value_minor", sa.BigInteger(), nullable=True),
        sa.Column("reference_type", sa.String(length=64), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("source_movement_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_by_movement_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(movement_type IN ('order_reservation', 'reservation_release') "
            "AND NOT affects_on_hand AND quantity_delta > 0) "
            "OR (movement_type NOT IN ('order_reservation', 'reservation_release') "
            "AND affects_on_hand)",
            name=op.f("ck_stock_movements_reservation_movements_do_not_affect_on_hand"),
        ),
        sa.CheckConstraint(
            "movement_type IN "
            "('opening_balance', 'purchase_receipt', 'order_reservation', "
            "'reservation_release', 'order_consumption', 'wastage', 'positive_adjustment', "
            "'negative_adjustment', 'transfer_out', 'transfer_in', 'supplier_return', "
            "'customer_return', 'stock_count_adjustment', 'reversal')",
            name=op.f("ck_stock_movements_valid_movement_type"),
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=op.f("ck_stock_movements_quantity_delta_non_zero")
        ),
        sa.CheckConstraint(
            "unit_cost_minor IS NULL OR unit_cost_minor >= 0",
            name=op.f("ck_stock_movements_valid_unit_cost_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_movements_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["entered_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_stock_movements_entered_unit_id_units_of_measure"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_movements_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_movements_performed_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_movements_reversed_by_movement_id_stock_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["source_movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_movements_source_movement_id_stock_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_movements_storage_location_id_storage_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
        sa.UniqueConstraint("movement_number", name=op.f("uq_stock_movements_movement_number")),
    )
    op.create_index(
        "ix_stock_movements_balance_rebuild",
        "stock_movements",
        ["inventory_item_id", "storage_location_id", "batch_id"],
        unique=False,
    )
    op.create_index("ix_stock_movements_batch_id", "stock_movements", ["batch_id"], unique=False)
    op.create_index(
        "ix_stock_movements_item_occurred",
        "stock_movements",
        ["inventory_item_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_location_occurred",
        "stock_movements",
        ["storage_location_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_occurred_at", "stock_movements", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_stock_movements_performed_by", "stock_movements", ["performed_by"], unique=False
    )
    op.create_index(
        "ix_stock_movements_reference",
        "stock_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_type_occurred",
        "stock_movements",
        ["movement_type", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "uq_stock_movements_idempotency_key",
        "stock_movements",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "stock_receipt_items",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_unit_id", sa.Uuid(), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("accepted_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("rejected_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("unit_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("line_total_minor", sa.BigInteger(), nullable=False),
        sa.Column("batch_code", sa.String(length=80), nullable=True),
        sa.Column("manufactured_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accepted_quantity + rejected_quantity <= received_quantity",
            name=op.f("ck_stock_receipt_items_accepted_plus_rejected_within_received"),
        ),
        sa.CheckConstraint(
            "accepted_quantity >= 0", name=op.f("ck_stock_receipt_items_valid_accepted_quantity")
        ),
        sa.CheckConstraint(
            "base_quantity >= 0", name=op.f("ck_stock_receipt_items_valid_base_quantity")
        ),
        sa.CheckConstraint(
            "line_total_minor >= 0", name=op.f("ck_stock_receipt_items_valid_line_total_minor")
        ),
        sa.CheckConstraint(
            "received_quantity > 0", name=op.f("ck_stock_receipt_items_valid_received_quantity")
        ),
        sa.CheckConstraint(
            "rejected_quantity >= 0", name=op.f("ck_stock_receipt_items_valid_rejected_quantity")
        ),
        sa.CheckConstraint(
            "unit_cost_minor >= 0", name=op.f("ck_stock_receipt_items_valid_unit_cost_minor")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_receipt_items_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_receipt_items_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_stock_receipt_items_purchase_unit_id_units_of_measure"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["stock_receipts.id"],
            name=op.f("fk_stock_receipt_items_receipt_id_stock_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_receipt_items")),
    )
    op.create_index(
        "ix_stock_receipt_items_item_id", "stock_receipt_items", ["inventory_item_id"], unique=False
    )
    op.create_index(
        "ix_stock_receipt_items_receipt_id", "stock_receipt_items", ["receipt_id"], unique=False
    )
    op.create_table(
        "stock_transfer_items",
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("destination_batch_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_items_valid_quantity")),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_transfer_items_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_transfer_items_destination_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_transfer_items_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfers.id"],
            name=op.f("fk_stock_transfer_items_transfer_id_stock_transfers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_items")),
    )
    op.create_index(
        "ix_stock_transfer_items_item_id",
        "stock_transfer_items",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_transfer_items_transfer_id", "stock_transfer_items", ["transfer_id"], unique=False
    )
    op.create_table(
        "recipe_items",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_required", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("waste_factor", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_quantity > 0", name=op.f("ck_recipe_items_valid_base_quantity")),
        sa.CheckConstraint("display_order >= 0", name=op.f("ck_recipe_items_valid_display_order")),
        sa.CheckConstraint(
            "quantity_required > 0", name=op.f("ck_recipe_items_valid_quantity_required")
        ),
        sa.CheckConstraint(
            "waste_factor >= 0 AND waste_factor < 1",
            name=op.f("ck_recipe_items_valid_waste_factor"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_recipe_items_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], name=op.f("fk_recipe_items_recipe_id_recipes")
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_recipe_items_storage_location_id_storage_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units_of_measure.id"],
            name=op.f("fk_recipe_items_unit_id_units_of_measure"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_items")),
    )
    op.create_index(
        "ix_recipe_items_inventory_item_id", "recipe_items", ["inventory_item_id"], unique=False
    )
    op.create_index("ix_recipe_items_recipe_id", "recipe_items", ["recipe_id"], unique=False)
    op.create_index(
        "uq_recipe_items_recipe_item",
        "recipe_items",
        ["recipe_id", "inventory_item_id"],
        unique=True,
    )
    op.create_table(
        "stock_adjustments",
        sa.Column("adjustment_number", sa.String(length=40), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reason_category", sa.String(length=48), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("value_impact_minor", sa.BigInteger(), nullable=True),
        sa.Column("movement_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('increase', 'decrease')",
            name=op.f("ck_stock_adjustments_valid_direction"),
        ),
        sa.CheckConstraint(
            "reason_category IN "
            "('count_difference', 'data_correction', 'damaged', 'spoiled', 'missing', "
            "'found', 'unit_conversion_correction')",
            name=op.f("ck_stock_adjustments_valid_reason_category"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_adjustments_valid_quantity")),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_adjustments_approved_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_adjustments_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_adjustments_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_adjustments_movement_id_stock_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["staff_users.id"],
            name=op.f("fk_stock_adjustments_recorded_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_stock_adjustments_storage_location_id_storage_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustments")),
        sa.UniqueConstraint(
            "adjustment_number", name=op.f("uq_stock_adjustments_adjustment_number")
        ),
    )
    op.create_index(
        "ix_stock_adjustments_created_at", "stock_adjustments", ["created_at"], unique=False
    )
    op.create_index(
        "ix_stock_adjustments_item_id", "stock_adjustments", ["inventory_item_id"], unique=False
    )
    op.create_index(
        "ix_stock_adjustments_location_id",
        "stock_adjustments",
        ["storage_location_id"],
        unique=False,
    )
    op.create_table(
        "stock_count_lines",
        sa.Column("count_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("system_quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("counted_quantity", sa.Numeric(precision=16, scale=3), nullable=True),
        sa.Column("variance_quantity", sa.Numeric(precision=16, scale=3), nullable=True),
        sa.Column("variance_value_minor", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("movement_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "counted_quantity IS NULL OR counted_quantity >= 0",
            name=op.f("ck_stock_count_lines_valid_counted_quantity"),
        ),
        sa.CheckConstraint(
            "system_quantity >= 0", name=op.f("ck_stock_count_lines_valid_system_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_stock_count_lines_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["count_id"],
            ["stock_counts.id"],
            name=op.f("fk_stock_count_lines_count_id_stock_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_count_lines_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_count_lines_movement_id_stock_movements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_count_lines")),
    )
    op.create_index(
        "ix_stock_count_lines_count_id", "stock_count_lines", ["count_id"], unique=False
    )
    op.create_index(
        "ix_stock_count_lines_item_id", "stock_count_lines", ["inventory_item_id"], unique=False
    )
    op.create_table(
        "wastage_records",
        sa.Column("wastage_number", sa.String(length=40), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("reason_category", sa.String(length=48), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("station", sa.String(length=120), nullable=True),
        sa.Column("related_order_id", sa.Uuid(), nullable=True),
        sa.Column("value_impact_minor", sa.BigInteger(), nullable=True),
        sa.Column("movement_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason_category IN "
            "('preparation_waste', 'overproduction', 'spoilage', 'expiry', "
            "'customer_return', 'quality_failure', 'accidental_damage', 'staff_error', 'other')",
            name=op.f("ck_wastage_records_valid_reason_category"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_wastage_records_valid_quantity")),
        sa.CheckConstraint(
            "value_impact_minor IS NULL OR value_impact_minor >= 0",
            name=op.f("ck_wastage_records_valid_value_impact_minor"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["staff_users.id"],
            name=op.f("fk_wastage_records_approved_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
            name=op.f("fk_wastage_records_batch_id_inventory_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_wastage_records_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_wastage_records_movement_id_stock_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["staff_users.id"],
            name=op.f("fk_wastage_records_recorded_by_staff_users"),
        ),
        sa.ForeignKeyConstraint(
            ["related_order_id"],
            ["orders.id"],
            name=op.f("fk_wastage_records_related_order_id_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_wastage_records_storage_location_id_storage_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wastage_records")),
        sa.UniqueConstraint("wastage_number", name=op.f("uq_wastage_records_wastage_number")),
    )
    op.create_index("ix_wastage_records_batch_id", "wastage_records", ["batch_id"], unique=False)
    op.create_index(
        "ix_wastage_records_created_at", "wastage_records", ["created_at"], unique=False
    )
    op.create_index(
        "ix_wastage_records_item_id", "wastage_records", ["inventory_item_id"], unique=False
    )
    op.create_index(
        "ix_wastage_records_location_id", "wastage_records", ["storage_location_id"], unique=False
    )
    op.create_index(
        "ix_wastage_records_reason_created",
        "wastage_records",
        ["reason_category", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_wastage_records_related_order_id", "wastage_records", ["related_order_id"], unique=False
    )
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _INVENTORY_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")

    op.execute(_LEDGER_GUARD_FUNCTION)
    op.execute(_LEDGER_GUARD_TRIGGER)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_stock_movements_append_only ON stock_movements")
    op.execute("DROP FUNCTION IF EXISTS rkpr_stock_movements_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wastage_records_related_order_id", table_name="wastage_records")
    op.drop_index("ix_wastage_records_reason_created", table_name="wastage_records")
    op.drop_index("ix_wastage_records_location_id", table_name="wastage_records")
    op.drop_index("ix_wastage_records_item_id", table_name="wastage_records")
    op.drop_index("ix_wastage_records_created_at", table_name="wastage_records")
    op.drop_index("ix_wastage_records_batch_id", table_name="wastage_records")
    op.drop_table("wastage_records")
    op.drop_index("ix_stock_count_lines_item_id", table_name="stock_count_lines")
    op.drop_index("ix_stock_count_lines_count_id", table_name="stock_count_lines")
    op.drop_table("stock_count_lines")
    op.drop_index("ix_stock_adjustments_location_id", table_name="stock_adjustments")
    op.drop_index("ix_stock_adjustments_item_id", table_name="stock_adjustments")
    op.drop_index("ix_stock_adjustments_created_at", table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    op.drop_index("uq_recipe_items_recipe_item", table_name="recipe_items")
    op.drop_index("ix_recipe_items_recipe_id", table_name="recipe_items")
    op.drop_index("ix_recipe_items_inventory_item_id", table_name="recipe_items")
    op.drop_table("recipe_items")
    op.drop_index("ix_stock_transfer_items_transfer_id", table_name="stock_transfer_items")
    op.drop_index("ix_stock_transfer_items_item_id", table_name="stock_transfer_items")
    op.drop_table("stock_transfer_items")
    op.drop_index("ix_stock_receipt_items_receipt_id", table_name="stock_receipt_items")
    op.drop_index("ix_stock_receipt_items_item_id", table_name="stock_receipt_items")
    op.drop_table("stock_receipt_items")
    op.drop_index(
        "uq_stock_movements_idempotency_key",
        table_name="stock_movements",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_stock_movements_type_occurred", table_name="stock_movements")
    op.drop_index("ix_stock_movements_reference", table_name="stock_movements")
    op.drop_index("ix_stock_movements_performed_by", table_name="stock_movements")
    op.drop_index("ix_stock_movements_occurred_at", table_name="stock_movements")
    op.drop_index("ix_stock_movements_location_occurred", table_name="stock_movements")
    op.drop_index("ix_stock_movements_item_occurred", table_name="stock_movements")
    op.drop_index("ix_stock_movements_batch_id", table_name="stock_movements")
    op.drop_index("ix_stock_movements_balance_rebuild", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(
        "uq_stock_balances_item_location_nobatch",
        table_name="stock_balances",
        postgresql_where=sa.text("batch_id IS NULL"),
    )
    op.drop_index(
        "uq_stock_balances_item_location_batch",
        table_name="stock_balances",
        postgresql_where=sa.text("batch_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_stock_balances_with_stock",
        table_name="stock_balances",
        postgresql_where=sa.text("on_hand_quantity > 0"),
    )
    op.drop_index("ix_stock_balances_location_id", table_name="stock_balances")
    op.drop_index("ix_stock_balances_item_id", table_name="stock_balances")
    op.drop_index("ix_stock_balances_batch_id", table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_index(
        "uq_recipes_active_variant",
        table_name="recipes",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active AND variant_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_recipes_active_base",
        table_name="recipes",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active AND variant_id IS NULL"),
    )
    op.drop_index("ix_recipes_variant_id", table_name="recipes")
    op.drop_index("ix_recipes_product_id", table_name="recipes")
    op.drop_table("recipes")
    op.drop_index("uq_order_inventory_states_order_id", table_name="order_inventory_states")
    op.drop_index("ix_order_inventory_states_state", table_name="order_inventory_states")
    op.drop_table("order_inventory_states")
    op.drop_index("ix_inventory_batches_supplier_id", table_name="inventory_batches")
    op.drop_index("ix_inventory_batches_location_id", table_name="inventory_batches")
    op.drop_index("ix_inventory_batches_item_id", table_name="inventory_batches")
    op.drop_index(
        "ix_inventory_batches_fefo",
        table_name="inventory_batches",
        postgresql_where=sa.text("status = 'active' AND remaining_quantity > 0"),
    )
    op.drop_index(
        "ix_inventory_batches_expiring",
        table_name="inventory_batches",
        postgresql_where=sa.text(
            "expires_at IS NOT NULL AND status = 'active' AND remaining_quantity > 0"
        ),
    )
    op.drop_table("inventory_batches")
    op.drop_index("ix_stock_transfers_status_created", table_name="stock_transfers")
    op.drop_index("ix_stock_transfers_source_location_id", table_name="stock_transfers")
    op.drop_index("ix_stock_transfers_destination_location_id", table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index("ix_stock_receipts_supplier_id", table_name="stock_receipts")
    op.drop_index("ix_stock_receipts_status_received", table_name="stock_receipts")
    op.drop_index("ix_stock_receipts_location_id", table_name="stock_receipts")
    op.drop_table("stock_receipts")
    op.drop_index(
        "uq_stock_counts_active_per_location",
        table_name="stock_counts",
        postgresql_where=sa.text("status IN ('draft', 'in_progress', 'submitted')"),
    )
    op.drop_index("ix_stock_counts_status_scheduled", table_name="stock_counts")
    op.drop_index("ix_stock_counts_location_id", table_name="stock_counts")
    op.drop_table("stock_counts")
    op.drop_index(
        "uq_inventory_items_barcode",
        table_name="inventory_items",
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.drop_index("ix_inventory_items_stock_status", table_name="inventory_items")
    op.drop_index(
        "ix_inventory_items_reorder_watch",
        table_name="inventory_items",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_index("ix_inventory_items_preferred_supplier_id", table_name="inventory_items")
    op.drop_index("ix_inventory_items_name", table_name="inventory_items")
    op.drop_index("ix_inventory_items_category_id", table_name="inventory_items")
    op.drop_index(
        "ix_inventory_items_active",
        table_name="inventory_items",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_table("inventory_items")
    op.drop_index("ix_units_of_measure_unit_type", table_name="units_of_measure")
    op.drop_index(
        "ix_units_of_measure_active",
        table_name="units_of_measure",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_table("units_of_measure")
    op.drop_index("ix_suppliers_name", table_name="suppliers")
    op.drop_index(
        "ix_suppliers_active",
        table_name="suppliers",
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )
    op.drop_table("suppliers")
    op.drop_index(
        "ix_storage_locations_active",
        table_name="storage_locations",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_table("storage_locations")
    op.drop_index(
        "ix_inventory_categories_active",
        table_name="inventory_categories",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_table("inventory_categories")
    # ### end Alembic commands ###
