"""add_phase12_loyalty_offers_campaigns_referrals_gift_cards_and_customer_credit

Revision ID: c8f5d1d4e495
Revises: e718e5a70d10
Create Date: 2026-07-31 09:01:54.736740

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8f5d1d4e495"
down_revision: str | Sequence[str] | None = "e718e5a70d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PHASE12_TABLES = (
    "loyalty_programs",
    "loyalty_tiers",
    "loyalty_accounts",
    "loyalty_tier_memberships",
    "loyalty_ledger_entries",
    "segments",
    "segment_memberships",
    "offers",
    "offer_versions",
    "coupons",
    "offer_redemptions",
    "campaigns",
    "campaign_recipients",
    "referral_programs",
    "referral_codes",
    "referral_relationships",
    "achievements",
    "customer_achievement_awards",
    "gift_cards",
    "gift_card_ledger_entries",
    "customer_credit_accounts",
    "customer_credit_ledger_entries",
    "commercial_risk_flags",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_versions",
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("eligibility_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benefit_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("minimum_order_value_minor", sa.BigInteger(), nullable=True),
        sa.Column("maximum_discount_minor", sa.BigInteger(), nullable=True),
        sa.Column("applicable_product_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("excluded_product_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "applicable_category_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("channel_eligibility", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("day_time_windows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("global_usage_limit", sa.Integer(), nullable=True),
        sa.Column("per_customer_usage_limit", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_offer_versions_valid_version_number")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_offer_versions_created_by_staff_users"),
        ),  # noqa: E501
        # offer_id -> offers.id is added below via op.create_foreign_key() once
        # `offers` exists — offers.latest_version_id references offer_versions.id,
        # so these two tables form a circular dependency that cannot both be
        # declared inline (the same pattern Phase 11 used for
        # knowledge_articles/knowledge_article_versions).
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_versions")),
    )
    op.create_index("ix_offer_versions_offer_id", "offer_versions", ["offer_id"], unique=False)
    op.create_index(
        "uq_offer_versions_offer_number",
        "offer_versions",
        ["offer_id", "version_number"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "offers",
        sa.Column("offer_code", sa.String(length=60), nullable=False),
        sa.Column("internal_name", sa.String(length=160), nullable=False),
        sa.Column("customer_facing_name", sa.String(length=160), nullable=False),
        sa.Column("offer_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requires_code", sa.Boolean(), nullable=False),
        sa.Column("stackability_group", sa.String(length=60), nullable=True),
        sa.Column("is_exclusive", sa.Boolean(), nullable=False),
        sa.Column("budget_cap_minor", sa.BigInteger(), nullable=True),
        sa.Column("redemption_cap", sa.Integer(), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("financial_owner_id", sa.Uuid(), nullable=True),
        sa.Column("terms_and_notes", sa.Text(), nullable=True),
        sa.Column("latest_version_number", sa.Integer(), nullable=False),
        sa.Column("latest_version_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "offer_type IN ('percentage_discount', 'fixed_discount', 'item_discount', 'category_discount', 'buy_x_get_y', 'combo_price', 'free_item', 'delivery_fee_discount', 'loyalty_bonus', 'internal_credit', 'service_recovery')",  # noqa: E501
            name=op.f("ck_offers_valid_offer_type"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('draft', 'in_review', 'approved', 'active', 'paused', 'expired', 'cancelled', 'archived')",  # noqa: E501
            name=op.f("ck_offers_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "latest_version_number >= 1", name=op.f("ck_offers_valid_latest_version_number")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["approved_by"], ["staff_users.id"], name=op.f("fk_offers_approved_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_offers_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["financial_owner_id"],
            ["staff_users.id"],
            name=op.f("fk_offers_financial_owner_id_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["latest_version_id"],
            ["offer_versions.id"],
            name=op.f("fk_offers_latest_version_id_offer_versions"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_offers_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
        sa.UniqueConstraint("offer_code", name=op.f("uq_offers_offer_code")),
    )
    op.create_index("ix_offers_offer_type", "offers", ["offer_type"], unique=False)
    op.create_index("ix_offers_status", "offers", ["status"], unique=False)
    op.create_foreign_key(
        op.f("fk_offer_versions_offer_id_offers"),
        "offer_versions",
        "offers",
        ["offer_id"],
        ["id"],
    )
    op.create_table(
        "achievements",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("condition_version", sa.Integer(), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("reward_ledger", sa.String(length=16), nullable=False),
        sa.Column("reward_amount", sa.Integer(), nullable=True),
        sa.Column("is_repeatable", sa.Boolean(), nullable=False),
        sa.Column("cooldown_days", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "reward_ledger = 'none' OR reward_amount > 0",
            name=op.f("ck_achievements_reward_amount_when_rewarding"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "reward_ledger IN ('none', 'loyalty_points', 'internal_credit')",
            name=op.f("ck_achievements_valid_reward_ledger"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "cooldown_days IS NULL OR cooldown_days > 0",
            name=op.f("ck_achievements_valid_cooldown_days"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_achievements_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_achievements_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
        sa.UniqueConstraint("code", name=op.f("uq_achievements_code")),
    )
    op.create_index("ix_achievements_is_active", "achievements", ["is_active"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("objective", sa.String(length=60), nullable=True),
        sa.Column("campaign_type", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("channel_templates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_segment_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excluded_segment_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("linked_offer_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("send_window_start_local", sa.String(length=5), nullable=True),
        sa.Column("send_window_end_local", sa.String(length=5), nullable=True),
        sa.Column("audience_snapshot_taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_size", sa.Integer(), nullable=True),
        sa.Column("budget_minor", sa.BigInteger(), nullable=True),
        sa.Column("owner_staff_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'ready', 'scheduled', 'running', 'paused', 'completed', 'cancelled', 'failed', 'archived')",  # noqa: E501
            name=op.f("ck_campaigns_valid_status"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["approved_by"], ["staff_users.id"], name=op.f("fk_campaigns_approved_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_campaigns_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["linked_offer_id"], ["offers.id"], name=op.f("fk_campaigns_linked_offer_id_offers")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["owner_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_campaigns_owner_staff_id_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_campaigns_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("code", name=op.f("uq_campaigns_code")),
    )
    op.create_index("ix_campaigns_scheduled_at", "campaigns", ["scheduled_at"], unique=False)
    op.create_index("ix_campaigns_status", "campaigns", ["status"], unique=False)
    op.create_table(
        "loyalty_programs",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("points_display_name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("points_per_currency_unit", sa.Integer(), nullable=False),
        sa.Column("currency_unit_minor", sa.Integer(), nullable=False),
        sa.Column("redemption_points_per_unit", sa.Integer(), nullable=False),
        sa.Column("redemption_value_minor", sa.Integer(), nullable=False),
        sa.Column("minimum_redemption_points", sa.Integer(), nullable=False),
        sa.Column("max_redemption_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("points_expiry_days", sa.Integer(), nullable=True),
        sa.Column("terms_summary", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused', 'archived')",
            name=op.f("ck_loyalty_programs_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "currency_unit_minor > 0", name=op.f("ck_loyalty_programs_valid_currency_unit_minor")
        ),  # noqa: E501
        sa.CheckConstraint(
            "max_redemption_percent IS NULL OR (max_redemption_percent > 0 AND max_redemption_percent <= 100)",  # noqa: E501
            name=op.f("ck_loyalty_programs_valid_max_redemption_percent"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "minimum_redemption_points >= 0",
            name=op.f("ck_loyalty_programs_valid_minimum_redemption_points"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "points_expiry_days IS NULL OR points_expiry_days > 0",
            name=op.f("ck_loyalty_programs_valid_points_expiry_days"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "points_per_currency_unit > 0",
            name=op.f("ck_loyalty_programs_valid_points_per_currency_unit"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "redemption_points_per_unit > 0",
            name=op.f("ck_loyalty_programs_valid_redemption_points_per_unit"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "redemption_value_minor > 0",
            name=op.f("ck_loyalty_programs_valid_redemption_value_minor"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_loyalty_programs_created_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_loyalty_programs_updated_by_staff_users"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_programs")),
        sa.UniqueConstraint("code", name=op.f("uq_loyalty_programs_code")),
    )
    op.create_index("ix_loyalty_programs_status", "loyalty_programs", ["status"], unique=False)
    op.create_index(
        "uq_loyalty_programs_one_default_active",
        "loyalty_programs",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default AND status = 'active'"),
    )  # noqa: E501
    op.create_table(
        "referral_programs",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("referrer_eligibility_note", sa.Text(), nullable=True),
        sa.Column("referee_eligibility_note", sa.Text(), nullable=True),
        sa.Column("qualifying_order_minimum_minor", sa.BigInteger(), nullable=True),
        sa.Column("reward_ledger", sa.String(length=16), nullable=False),
        sa.Column("referrer_reward_amount", sa.Integer(), nullable=False),
        sa.Column("referee_reward_amount", sa.Integer(), nullable=False),
        sa.Column("max_active_codes_per_referrer", sa.Integer(), nullable=False),
        sa.Column("max_rewarded_referrals_per_window", sa.Integer(), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=True),
        sa.Column("reward_hold_days", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "reward_ledger IN ('loyalty_points', 'internal_credit')",
            name=op.f("ck_referral_programs_valid_reward_ledger"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused', 'archived')",
            name=op.f("ck_referral_programs_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "qualifying_order_minimum_minor IS NULL OR qualifying_order_minimum_minor >= 0",
            name=op.f("ck_referral_programs_valid_qualifying_order_minimum_minor"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "referee_reward_amount > 0",
            name=op.f("ck_referral_programs_valid_referee_reward_amount"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "referrer_reward_amount > 0",
            name=op.f("ck_referral_programs_valid_referrer_reward_amount"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "reward_hold_days >= 0", name=op.f("ck_referral_programs_valid_reward_hold_days")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_referral_programs_created_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff_users.id"],
            name=op.f("fk_referral_programs_updated_by_staff_users"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_programs")),
        sa.UniqueConstraint("code", name=op.f("uq_referral_programs_code")),
    )
    op.create_index("ix_referral_programs_status", "referral_programs", ["status"], unique=False)
    op.create_table(
        "segments",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("segment_type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("rule_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("refresh_strategy", sa.String(length=30), nullable=True),
        sa.Column("estimated_count", sa.Integer(), nullable=True),
        sa.Column("last_computed_count", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_staff_id", sa.Uuid(), nullable=True),
        sa.Column("is_seed_builtin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "segment_type IN ('dynamic', 'static')", name=op.f("ck_segments_valid_segment_type")
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')", name=op.f("ck_segments_valid_status")
        ),  # noqa: E501
        sa.CheckConstraint("rule_version >= 1", name=op.f("ck_segments_valid_rule_version")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_segments_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["owner_staff_id"],
            ["staff_users.id"],
            name=op.f("fk_segments_owner_staff_id_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_segments_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segments")),
        sa.UniqueConstraint("code", name=op.f("uq_segments_code")),
    )
    op.create_index("ix_segments_status", "segments", ["status"], unique=False)
    op.create_index("ix_segments_type", "segments", ["segment_type"], unique=False)
    op.create_table(
        "commercial_risk_flags",
        sa.Column("flag_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("staff_user_id", sa.Uuid(), nullable=True),
        sa.Column("related_type", sa.String(length=40), nullable=True),
        sa.Column("related_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "flag_type IN ('repeated_manual_adjustment', 'repeated_reversal', 'excessive_coupon_failures', 'high_value_issuance', 'self_referral_attempt', 'identity_overlap', 'duplicate_attempt')",  # noqa: E501
            name=op.f("ck_commercial_risk_flags_valid_flag_type"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('open', 'reviewing', 'resolved', 'dismissed')",
            name=op.f("ck_commercial_risk_flags_valid_status"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_commercial_risk_flags_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["staff_users.id"],
            name=op.f("fk_commercial_risk_flags_reviewed_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_commercial_risk_flags_staff_user_id_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_records.id"],
            name=op.f("fk_commercial_risk_flags_task_id_task_records"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commercial_risk_flags")),
    )
    op.create_index(
        "ix_commercial_risk_flags_customer_id",
        "commercial_risk_flags",
        ["customer_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_commercial_risk_flags_flag_type", "commercial_risk_flags", ["flag_type"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_commercial_risk_flags_related",
        "commercial_risk_flags",
        ["related_type", "related_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_commercial_risk_flags_status", "commercial_risk_flags", ["status"], unique=False
    )  # noqa: E501
    op.create_table(
        "coupons",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("is_reusable", sa.Boolean(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redemption_limit", sa.Integer(), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=False),
        sa.Column("source_campaign_id", sa.Uuid(), nullable=True),
        sa.Column("generation_batch", sa.String(length=60), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint("redemption_count >= 0", name=op.f("ck_coupons_valid_redemption_count")),
        sa.CheckConstraint(
            "redemption_limit IS NULL OR redemption_limit > 0",
            name=op.f("ck_coupons_valid_redemption_limit"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_coupons_customer_id_customers")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["offer_id"], ["offers.id"], name=op.f("fk_coupons_offer_id_offers")
        ),
        sa.ForeignKeyConstraint(
            ["source_campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_coupons_source_campaign_id_campaigns"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
    )
    op.create_index("ix_coupons_customer_id", "coupons", ["customer_id"], unique=False)
    op.create_index("ix_coupons_offer_id", "coupons", ["offer_id"], unique=False)
    op.create_index("uq_coupons_code", "coupons", ["code"], unique=True)
    op.create_table(
        "customer_achievement_awards",
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("source_event_type", sa.String(length=60), nullable=False),
        sa.Column("source_event_key", sa.String(length=160), nullable=False),
        sa.Column("is_repeatable_award", sa.Boolean(), nullable=False),
        sa.Column("reward_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.String(length=300), nullable=True),
        sa.Column("awarded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_customer_achievement_awards_achievement_id_achievements"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_achievement_awards_customer_id_customers"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_achievement_awards")),
    )
    op.create_index(
        "ix_customer_achievement_awards_achievement_id",
        "customer_achievement_awards",
        ["achievement_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_customer_achievement_awards_customer_id",
        "customer_achievement_awards",
        ["customer_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_customer_achievement_awards_non_repeatable",
        "customer_achievement_awards",
        ["achievement_id", "customer_id"],
        unique=True,
        postgresql_where=sa.text("is_repeatable_award = false"),
    )  # noqa: E501
    op.create_index(
        "uq_customer_achievement_awards_source_event",
        "customer_achievement_awards",
        ["achievement_id", "customer_id", "source_event_key"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "customer_credit_accounts",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("current_balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'closed')",
            name=op.f("ck_customer_credit_accounts_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "current_balance_minor >= 0",
            name=op.f("ck_customer_credit_accounts_valid_current_balance_minor"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_credit_accounts_customer_id_customers"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_credit_accounts")),
    )
    op.create_index(
        "uq_customer_credit_accounts_customer_id",
        "customer_credit_accounts",
        ["customer_id"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "loyalty_tiers",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("qualification_metric", sa.String(length=24), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("rolling_window_days", sa.Integer(), nullable=True),
        sa.Column("benefits_summary", sa.Text(), nullable=True),
        sa.Column("points_multiplier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("review_period_days", sa.Integer(), nullable=True),
        sa.Column("downgrade_grace_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "qualification_metric IN ('lifetime_spend', 'rolling_spend', 'points_earned', 'completed_orders', 'visits', 'manual')",  # noqa: E501
            name=op.f("ck_loyalty_tiers_valid_qualification_metric"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "points_multiplier > 0", name=op.f("ck_loyalty_tiers_valid_points_multiplier")
        ),  # noqa: E501
        sa.CheckConstraint("rank >= 0", name=op.f("ck_loyalty_tiers_valid_rank")),
        sa.CheckConstraint(
            "rolling_window_days IS NULL OR rolling_window_days > 0",
            name=op.f("ck_loyalty_tiers_valid_rolling_window_days"),
        ),  # noqa: E501
        sa.CheckConstraint("threshold >= 0", name=op.f("ck_loyalty_tiers_valid_threshold")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_loyalty_tiers_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["loyalty_programs.id"],
            name=op.f("fk_loyalty_tiers_program_id_loyalty_programs"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_loyalty_tiers_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_tiers")),
    )
    op.create_index(
        "ix_loyalty_tiers_program_rank", "loyalty_tiers", ["program_id", "rank"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_loyalty_tiers_program_code", "loyalty_tiers", ["program_id", "code"], unique=True
    )  # noqa: E501
    op.create_table(
        "referral_codes",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("referrer_customer_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["referral_programs.id"],
            name=op.f("fk_referral_codes_program_id_referral_programs"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["referrer_customer_id"],
            ["customers.id"],
            name=op.f("fk_referral_codes_referrer_customer_id_customers"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_codes")),
    )
    op.create_index("ix_referral_codes_program_id", "referral_codes", ["program_id"], unique=False)
    op.create_index(
        "ix_referral_codes_referrer_customer_id",
        "referral_codes",
        ["referrer_customer_id"],
        unique=False,
    )  # noqa: E501
    op.create_index("uq_referral_codes_code", "referral_codes", ["code"], unique=True)
    op.create_table(
        "segment_memberships",
        sa.Column("segment_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=True),
        sa.Column("added_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('added', 'removed')", name=op.f("ck_segment_memberships_valid_action")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["staff_users.id"],
            name=op.f("fk_segment_memberships_added_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_segment_memberships_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["segment_id"], ["segments.id"], name=op.f("fk_segment_memberships_segment_id_segments")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segment_memberships")),
    )
    op.create_index(
        "ix_segment_memberships_customer_id", "segment_memberships", ["customer_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_segment_memberships_segment_customer",
        "segment_memberships",
        ["segment_id", "customer_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_segment_memberships_segment_id", "segment_memberships", ["segment_id"], unique=False
    )  # noqa: E501
    op.create_table(
        "customer_credit_ledger_entries",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=12), nullable=False),
        sa.Column("issue_reason", sa.String(length=24), nullable=True),
        sa.Column("amount_delta_minor", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_minor", sa.BigInteger(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approval_reference", sa.String(length=120), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('issue', 'redeem', 'reverse', 'adjust', 'expire', 'migration')",
            name=op.f("ck_customer_credit_ledger_entries_valid_entry_type"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "issue_reason IS NULL OR issue_reason IN ('service_recovery', 'refund_as_credit', 'campaign_reward', 'referral_reward', 'achievement_reward', 'goodwill_adjustment', 'migration')",  # noqa: E501
            name=op.f("ck_customer_credit_ledger_entries_valid_issue_reason"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "amount_delta_minor <> 0",
            name=op.f("ck_customer_credit_ledger_entries_amount_delta_non_zero"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "balance_after_minor >= 0",
            name=op.f("ck_customer_credit_ledger_entries_valid_balance_after_minor"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_credit_accounts.id"],
            name=op.f("fk_customer_credit_ledger_entries_account_id_customer_credit_accounts"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_customer_credit_ledger_entries_created_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["customer_credit_ledger_entries.id"],
            name=op.f(
                "fk_customer_credit_ledger_entries_reversal_of_id_customer_credit_ledger_entries"
            ),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_credit_ledger_entries")),
    )
    op.create_index(
        "ix_customer_credit_ledger_entries_account_id",
        "customer_credit_ledger_entries",
        ["account_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_customer_credit_ledger_entries_source",
        "customer_credit_ledger_entries",
        ["source_type", "source_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_customer_credit_ledger_entries_idempotency_key",
        "customer_credit_ledger_entries",
        ["idempotency_key"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "loyalty_accounts",
        sa.Column("account_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("points_balance", sa.Integer(), nullable=False),
        sa.Column("lifetime_points_earned", sa.Integer(), nullable=False),
        sa.Column("lifetime_points_redeemed", sa.Integer(), nullable=False),
        sa.Column("lifetime_points_expired", sa.Integer(), nullable=False),
        sa.Column("current_tier_id", sa.Uuid(), nullable=True),
        sa.Column("tier_effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tier_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enrollment_source", sa.String(length=60), nullable=True),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_version_accepted", sa.String(length=30), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'closed', 'merged')",
            name=op.f("ck_loyalty_accounts_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "lifetime_points_earned >= 0", name=op.f("ck_loyalty_accounts_valid_lifetime_earned")
        ),  # noqa: E501
        sa.CheckConstraint(
            "lifetime_points_expired >= 0", name=op.f("ck_loyalty_accounts_valid_lifetime_expired")
        ),  # noqa: E501
        sa.CheckConstraint(
            "lifetime_points_redeemed >= 0",
            name=op.f("ck_loyalty_accounts_valid_lifetime_redeemed"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "points_balance >= 0", name=op.f("ck_loyalty_accounts_valid_points_balance")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["current_tier_id"],
            ["loyalty_tiers.id"],
            name=op.f("fk_loyalty_accounts_current_tier_id_loyalty_tiers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_loyalty_accounts_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["loyalty_programs.id"],
            name=op.f("fk_loyalty_accounts_program_id_loyalty_programs"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_accounts")),
        sa.UniqueConstraint("account_number", name=op.f("uq_loyalty_accounts_account_number")),
    )
    op.create_index(
        "ix_loyalty_accounts_current_tier_id", "loyalty_accounts", ["current_tier_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_accounts_program_id", "loyalty_accounts", ["program_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_loyalty_accounts_customer_program",
        "loyalty_accounts",
        ["customer_id", "program_id"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "loyalty_ledger_entries",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=24), nullable=False),
        sa.Column("points_delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remaining_in_lot", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("approval_reference", sa.String(length=120), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_by_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "entry_type IN ('earn_order', 'earn_campaign', 'earn_manual', 'redeem_order', 'redeem_reward', 'expire', 'reverse_earn', 'reverse_redemption', 'service_recovery_credit', 'merge_transfer', 'correction', 'referral_reward', 'achievement_reward')",  # noqa: E501
            name=op.f("ck_loyalty_ledger_entries_valid_entry_type"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_loyalty_ledger_entries_valid_balance_after")
        ),  # noqa: E501
        sa.CheckConstraint(
            "points_delta <> 0", name=op.f("ck_loyalty_ledger_entries_points_delta_non_zero")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["loyalty_accounts.id"],
            name=op.f("fk_loyalty_ledger_entries_account_id_loyalty_accounts"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_loyalty_ledger_entries_created_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["loyalty_ledger_entries.id"],
            name=op.f("fk_loyalty_ledger_entries_reversal_of_id_loyalty_ledger_entries"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["reversed_by_id"],
            ["loyalty_ledger_entries.id"],
            name=op.f("fk_loyalty_ledger_entries_reversed_by_id_loyalty_ledger_entries"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_ledger_entries")),
    )
    op.create_index(
        "ix_loyalty_ledger_entries_account_created",
        "loyalty_ledger_entries",
        ["account_id", "created_at"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_ledger_entries_account_id",
        "loyalty_ledger_entries",
        ["account_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_ledger_entries_entry_type",
        "loyalty_ledger_entries",
        ["entry_type"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_ledger_entries_expiry_at", "loyalty_ledger_entries", ["expiry_at"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_ledger_entries_reversal_of_id",
        "loyalty_ledger_entries",
        ["reversal_of_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_loyalty_ledger_entries_source",
        "loyalty_ledger_entries",
        ["source_type", "source_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_loyalty_ledger_entries_idempotency_key",
        "loyalty_ledger_entries",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )  # noqa: E501
    op.create_table(
        "loyalty_tier_memberships",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("tier_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("qualification_snapshot", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source IN ('automatic', 'manual', 'imported', 'migration')",
            name=op.f("ck_loyalty_tier_memberships_valid_source"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["loyalty_accounts.id"],
            name=op.f("fk_loyalty_tier_memberships_account_id_loyalty_accounts"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["staff_users.id"],
            name=op.f("fk_loyalty_tier_memberships_assigned_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["loyalty_tiers.id"],
            name=op.f("fk_loyalty_tier_memberships_tier_id_loyalty_tiers"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_tier_memberships")),
    )
    op.create_index(
        "ix_loyalty_tier_memberships_account_id",
        "loyalty_tier_memberships",
        ["account_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_loyalty_tier_memberships_one_current",
        "loyalty_tier_memberships",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )  # noqa: E501
    op.create_table(
        "offer_redemptions",
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("offer_version_id", sa.Uuid(), nullable=False),
        sa.Column("coupon_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("entered_code", sa.String(length=40), nullable=True),
        sa.Column("eligible_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("discount_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column(
            "evaluation_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("reservation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('reserved', 'applied', 'confirmed', 'reversed', 'rejected', 'expired')",
            name=op.f("ck_offer_redemptions_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "discount_amount_minor >= 0",
            name=op.f("ck_offer_redemptions_valid_discount_amount_minor"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "eligible_amount_minor >= 0",
            name=op.f("ck_offer_redemptions_valid_eligible_amount_minor"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["coupon_id"], ["coupons.id"], name=op.f("fk_offer_redemptions_coupon_id_coupons")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_offer_redemptions_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["offer_id"], ["offers.id"], name=op.f("fk_offer_redemptions_offer_id_offers")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["offer_version_id"],
            ["offer_versions.id"],
            name=op.f("fk_offer_redemptions_offer_version_id_offer_versions"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_offer_redemptions_order_id_orders")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_redemptions")),
    )
    op.create_index(
        "ix_offer_redemptions_customer_id", "offer_redemptions", ["customer_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_offer_redemptions_offer_id", "offer_redemptions", ["offer_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_offer_redemptions_order_id", "offer_redemptions", ["order_id"], unique=False
    )  # noqa: E501
    op.create_index("ix_offer_redemptions_status", "offer_redemptions", ["status"], unique=False)
    op.create_index(
        "uq_offer_redemptions_idempotency_key",
        "offer_redemptions",
        ["idempotency_key"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "referral_relationships",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column("referrer_customer_id", sa.Uuid(), nullable=False),
        sa.Column("referred_identity_key", sa.String(length=200), nullable=False),
        sa.Column("referred_customer_id", sa.Uuid(), nullable=True),
        sa.Column("attributed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qualifying_order_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("referrer_reward_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column("referee_reward_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rewarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.CheckConstraint(
            "status IN ('invited', 'attributed', 'qualified', 'rewarded', 'rejected', 'cancelled')",
            name=op.f("ck_referral_relationships_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "referred_customer_id IS NULL OR referred_customer_id <> referrer_customer_id",
            name=op.f("ck_referral_relationships_no_self_referral"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["referral_codes.id"],
            name=op.f("fk_referral_relationships_code_id_referral_codes"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["referral_programs.id"],
            name=op.f("fk_referral_relationships_program_id_referral_programs"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["qualifying_order_id"],
            ["orders.id"],
            name=op.f("fk_referral_relationships_qualifying_order_id_orders"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["referred_customer_id"],
            ["customers.id"],
            name=op.f("fk_referral_relationships_referred_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["referrer_customer_id"],
            ["customers.id"],
            name=op.f("fk_referral_relationships_referrer_customer_id_customers"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_relationships")),
    )
    op.create_index(
        "ix_referral_relationships_program_id",
        "referral_relationships",
        ["program_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_referral_relationships_referrer_customer_id",
        "referral_relationships",
        ["referrer_customer_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_referral_relationships_status", "referral_relationships", ["status"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_referral_relationships_identity",
        "referral_relationships",
        ["program_id", "referred_identity_key"],
        unique=True,
    )  # noqa: E501
    op.create_index(
        "uq_referral_relationships_qualifying_order",
        "referral_relationships",
        ["qualifying_order_id"],
        unique=True,
        postgresql_where=sa.text("qualifying_order_id IS NOT NULL"),
    )  # noqa: E501
    op.create_table(
        "gift_cards",
        sa.Column("card_number", sa.String(length=40), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("code_last4", sa.String(length=4), nullable=False),
        sa.Column("pin_hash", sa.String(length=128), nullable=True),
        sa.Column("purchaser_customer_id", sa.Uuid(), nullable=True),
        sa.Column("purchaser_contact", sa.String(length=200), nullable=True),
        sa.Column("recipient_customer_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_name", sa.String(length=160), nullable=True),
        sa.Column("recipient_contact", sa.String(length=200), nullable=True),
        sa.Column("initial_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("current_balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_order_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_status", sa.String(length=30), nullable=True),
        sa.Column("delivery_message_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'partially_redeemed', 'fully_redeemed', 'expired', 'suspended', 'cancelled')",  # noqa: E501
            name=op.f("ck_gift_cards_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "current_balance_minor <= initial_amount_minor",
            name=op.f("ck_gift_cards_balance_not_above_initial"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "current_balance_minor >= 0", name=op.f("ck_gift_cards_valid_current_balance_minor")
        ),  # noqa: E501
        sa.CheckConstraint(
            "initial_amount_minor > 0", name=op.f("ck_gift_cards_valid_initial_amount_minor")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"], ["staff_users.id"], name=op.f("fk_gift_cards_created_by_staff_users")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["delivery_message_id"],
            ["messages.id"],
            name=op.f("fk_gift_cards_delivery_message_id_messages"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["purchaser_customer_id"],
            ["customers.id"],
            name=op.f("fk_gift_cards_purchaser_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["recipient_customer_id"],
            ["customers.id"],
            name=op.f("fk_gift_cards_recipient_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["source_order_id"], ["orders.id"], name=op.f("fk_gift_cards_source_order_id_orders")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["updated_by"], ["staff_users.id"], name=op.f("fk_gift_cards_updated_by_staff_users")
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_cards")),
        sa.UniqueConstraint("card_number", name=op.f("uq_gift_cards_card_number")),
    )
    op.create_index(
        "ix_gift_cards_purchaser_customer_id", "gift_cards", ["purchaser_customer_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_gift_cards_recipient_customer_id", "gift_cards", ["recipient_customer_id"], unique=False
    )  # noqa: E501
    op.create_index("ix_gift_cards_status", "gift_cards", ["status"], unique=False)
    op.create_index("uq_gift_cards_code_hash", "gift_cards", ["code_hash"], unique=True)
    op.create_table(
        "campaign_recipients",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("eligibility_reason", sa.Text(), nullable=True),
        sa.Column("suppression_reason", sa.String(length=60), nullable=True),
        sa.Column("scheduled_message_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'eligible', 'suppressed', 'sent', 'failed')",
            name=op.f("ck_campaign_recipients_valid_status"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_campaign_recipients_valid_attempt_count")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_recipients_campaign_id_campaigns"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["communication_channels.id"],
            name=op.f("fk_campaign_recipients_channel_id_communication_channels"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_campaign_recipients_customer_id_customers"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_campaign_recipients_message_id_messages")
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["scheduled_message_id"],
            ["scheduled_messages.id"],
            name=op.f("fk_campaign_recipients_scheduled_message_id_scheduled_messages"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["source_segment_id"],
            ["segments.id"],
            name=op.f("fk_campaign_recipients_source_segment_id_segments"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_recipients")),
    )
    op.create_index(
        "ix_campaign_recipients_campaign_id", "campaign_recipients", ["campaign_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_campaign_recipients_customer_id", "campaign_recipients", ["customer_id"], unique=False
    )  # noqa: E501
    op.create_index(
        "ix_campaign_recipients_status", "campaign_recipients", ["status"], unique=False
    )  # noqa: E501
    op.create_index(
        "uq_campaign_recipients_campaign_customer_channel",
        "campaign_recipients",
        ["campaign_id", "customer_id", "channel_id"],
        unique=True,
    )  # noqa: E501
    op.create_table(
        "gift_card_ledger_entries",
        sa.Column("gift_card_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=12), nullable=False),
        sa.Column("amount_delta_minor", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_minor", sa.BigInteger(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('issue', 'activate', 'redeem', 'reverse', 'adjust', 'expire', 'cancel', 'migration')",  # noqa: E501
            name=op.f("ck_gift_card_ledger_entries_valid_entry_type"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "amount_delta_minor <> 0",
            name=op.f("ck_gift_card_ledger_entries_amount_delta_non_zero"),
        ),  # noqa: E501
        sa.CheckConstraint(
            "balance_after_minor >= 0",
            name=op.f("ck_gift_card_ledger_entries_valid_balance_after_minor"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff_users.id"],
            name=op.f("fk_gift_card_ledger_entries_created_by_staff_users"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["gift_card_id"],
            ["gift_cards.id"],
            name=op.f("fk_gift_card_ledger_entries_gift_card_id_gift_cards"),
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["gift_card_ledger_entries.id"],
            name=op.f("fk_gift_card_ledger_entries_reversal_of_id_gift_card_ledger_entries"),
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_card_ledger_entries")),
    )
    op.create_index(
        "ix_gift_card_ledger_entries_gift_card_id",
        "gift_card_ledger_entries",
        ["gift_card_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "ix_gift_card_ledger_entries_source",
        "gift_card_ledger_entries",
        ["source_type", "source_id"],
        unique=False,
    )  # noqa: E501
    op.create_index(
        "uq_gift_card_ledger_entries_idempotency_key",
        "gift_card_ledger_entries",
        ["idempotency_key"],
        unique=True,
    )  # noqa: E501
    # ### end Alembic commands ###

    # Supabase's PostgREST layer is reachable via the public anon key unless
    # RLS blocks it, even though apps/api's own connection (table-owning
    # role) is unaffected — SECURITY_PERFORMANCE_AND_QUALITY.md section 8.5,
    # the same convention every table-creating migration since Phase 3 has
    # followed.
    for table_name in _PHASE12_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_gift_card_ledger_entries_idempotency_key", table_name="gift_card_ledger_entries"
    )  # noqa: E501
    op.drop_index("ix_gift_card_ledger_entries_source", table_name="gift_card_ledger_entries")
    op.drop_index("ix_gift_card_ledger_entries_gift_card_id", table_name="gift_card_ledger_entries")
    op.drop_table("gift_card_ledger_entries")
    op.drop_index(
        "uq_campaign_recipients_campaign_customer_channel", table_name="campaign_recipients"
    )  # noqa: E501
    op.drop_index("ix_campaign_recipients_status", table_name="campaign_recipients")
    op.drop_index("ix_campaign_recipients_customer_id", table_name="campaign_recipients")
    op.drop_index("ix_campaign_recipients_campaign_id", table_name="campaign_recipients")
    op.drop_table("campaign_recipients")
    op.drop_index("uq_gift_cards_code_hash", table_name="gift_cards")
    op.drop_index("ix_gift_cards_status", table_name="gift_cards")
    op.drop_index("ix_gift_cards_recipient_customer_id", table_name="gift_cards")
    op.drop_index("ix_gift_cards_purchaser_customer_id", table_name="gift_cards")
    op.drop_table("gift_cards")
    op.drop_index(
        "uq_referral_relationships_qualifying_order",
        table_name="referral_relationships",
        postgresql_where=sa.text("qualifying_order_id IS NOT NULL"),
    )  # noqa: E501
    op.drop_index("uq_referral_relationships_identity", table_name="referral_relationships")
    op.drop_index("ix_referral_relationships_status", table_name="referral_relationships")
    op.drop_index(
        "ix_referral_relationships_referrer_customer_id", table_name="referral_relationships"
    )  # noqa: E501
    op.drop_index("ix_referral_relationships_program_id", table_name="referral_relationships")
    op.drop_table("referral_relationships")
    op.drop_index("uq_offer_redemptions_idempotency_key", table_name="offer_redemptions")
    op.drop_index("ix_offer_redemptions_status", table_name="offer_redemptions")
    op.drop_index("ix_offer_redemptions_order_id", table_name="offer_redemptions")
    op.drop_index("ix_offer_redemptions_offer_id", table_name="offer_redemptions")
    op.drop_index("ix_offer_redemptions_customer_id", table_name="offer_redemptions")
    op.drop_table("offer_redemptions")
    op.drop_index(
        "uq_loyalty_tier_memberships_one_current",
        table_name="loyalty_tier_memberships",
        postgresql_where=sa.text("effective_to IS NULL"),
    )  # noqa: E501
    op.drop_index("ix_loyalty_tier_memberships_account_id", table_name="loyalty_tier_memberships")
    op.drop_table("loyalty_tier_memberships")
    op.drop_index(
        "uq_loyalty_ledger_entries_idempotency_key",
        table_name="loyalty_ledger_entries",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )  # noqa: E501
    op.drop_index("ix_loyalty_ledger_entries_source", table_name="loyalty_ledger_entries")
    op.drop_index("ix_loyalty_ledger_entries_reversal_of_id", table_name="loyalty_ledger_entries")
    op.drop_index("ix_loyalty_ledger_entries_expiry_at", table_name="loyalty_ledger_entries")
    op.drop_index("ix_loyalty_ledger_entries_entry_type", table_name="loyalty_ledger_entries")
    op.drop_index("ix_loyalty_ledger_entries_account_id", table_name="loyalty_ledger_entries")
    op.drop_index("ix_loyalty_ledger_entries_account_created", table_name="loyalty_ledger_entries")
    op.drop_table("loyalty_ledger_entries")
    op.drop_index("uq_loyalty_accounts_customer_program", table_name="loyalty_accounts")
    op.drop_index("ix_loyalty_accounts_program_id", table_name="loyalty_accounts")
    op.drop_index("ix_loyalty_accounts_current_tier_id", table_name="loyalty_accounts")
    op.drop_table("loyalty_accounts")
    op.drop_index(
        "uq_customer_credit_ledger_entries_idempotency_key",
        table_name="customer_credit_ledger_entries",
    )  # noqa: E501
    op.drop_index(
        "ix_customer_credit_ledger_entries_source", table_name="customer_credit_ledger_entries"
    )  # noqa: E501
    op.drop_index(
        "ix_customer_credit_ledger_entries_account_id", table_name="customer_credit_ledger_entries"
    )  # noqa: E501
    op.drop_table("customer_credit_ledger_entries")
    op.drop_index("ix_segment_memberships_segment_id", table_name="segment_memberships")
    op.drop_index("ix_segment_memberships_segment_customer", table_name="segment_memberships")
    op.drop_index("ix_segment_memberships_customer_id", table_name="segment_memberships")
    op.drop_table("segment_memberships")
    op.drop_index("uq_referral_codes_code", table_name="referral_codes")
    op.drop_index("ix_referral_codes_referrer_customer_id", table_name="referral_codes")
    op.drop_index("ix_referral_codes_program_id", table_name="referral_codes")
    op.drop_table("referral_codes")
    op.drop_index("uq_loyalty_tiers_program_code", table_name="loyalty_tiers")
    op.drop_index("ix_loyalty_tiers_program_rank", table_name="loyalty_tiers")
    op.drop_table("loyalty_tiers")
    op.drop_index("uq_customer_credit_accounts_customer_id", table_name="customer_credit_accounts")
    op.drop_table("customer_credit_accounts")
    op.drop_index(
        "uq_customer_achievement_awards_source_event", table_name="customer_achievement_awards"
    )  # noqa: E501
    op.drop_index(
        "uq_customer_achievement_awards_non_repeatable",
        table_name="customer_achievement_awards",
        postgresql_where=sa.text("is_repeatable_award = false"),
    )  # noqa: E501
    op.drop_index(
        "ix_customer_achievement_awards_customer_id", table_name="customer_achievement_awards"
    )  # noqa: E501
    op.drop_index(
        "ix_customer_achievement_awards_achievement_id", table_name="customer_achievement_awards"
    )  # noqa: E501
    op.drop_table("customer_achievement_awards")
    op.drop_index("uq_coupons_code", table_name="coupons")
    op.drop_index("ix_coupons_offer_id", table_name="coupons")
    op.drop_index("ix_coupons_customer_id", table_name="coupons")
    op.drop_table("coupons")
    op.drop_index("ix_commercial_risk_flags_status", table_name="commercial_risk_flags")
    op.drop_index("ix_commercial_risk_flags_related", table_name="commercial_risk_flags")
    op.drop_index("ix_commercial_risk_flags_flag_type", table_name="commercial_risk_flags")
    op.drop_index("ix_commercial_risk_flags_customer_id", table_name="commercial_risk_flags")
    op.drop_table("commercial_risk_flags")
    op.drop_index("ix_segments_type", table_name="segments")
    op.drop_index("ix_segments_status", table_name="segments")
    op.drop_table("segments")
    op.drop_index("ix_referral_programs_status", table_name="referral_programs")
    op.drop_table("referral_programs")
    op.drop_index(
        "uq_loyalty_programs_one_default_active",
        table_name="loyalty_programs",
        postgresql_where=sa.text("is_default AND status = 'active'"),
    )  # noqa: E501
    op.drop_index("ix_loyalty_programs_status", table_name="loyalty_programs")
    op.drop_table("loyalty_programs")
    op.drop_index("ix_campaigns_status", table_name="campaigns")
    op.drop_index("ix_campaigns_scheduled_at", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index("ix_achievements_is_active", table_name="achievements")
    op.drop_table("achievements")
    op.drop_index("ix_offers_status", table_name="offers")
    op.drop_index("ix_offers_offer_type", table_name="offers")
    # Drop the deferred circular FK (added post-creation in upgrade()) before
    # either table so PostgreSQL doesn't refuse to drop `offers` while
    # `offer_versions.offer_id` still references it.
    op.drop_constraint(
        op.f("fk_offer_versions_offer_id_offers"), "offer_versions", type_="foreignkey"
    )
    op.drop_table("offers")
    op.drop_index("uq_offer_versions_offer_number", table_name="offer_versions")
    op.drop_index("ix_offer_versions_offer_id", table_name="offer_versions")
    op.drop_table("offer_versions")
    # ### end Alembic commands ###
