"""add_staff_invitations_name_fields

Revision ID: c9582fab677e
Revises: 139a3e5919f2
Create Date: 2026-07-25 17:28:30.631388

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9582fab677e"
down_revision: str | Sequence[str] | None = "139a3e5919f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "staff_invitations", sa.Column("first_name", sa.String(length=80), nullable=False)
    )
    op.add_column("staff_invitations", sa.Column("last_name", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("staff_invitations", "last_name")
    op.drop_column("staff_invitations", "first_name")
    # ### end Alembic commands ###
