"""add_phase15_notification_delivery_tracking

Revision ID: cf0b81306a8f
Revises: 4edacdc2f990
Create Date: 2026-08-01 23:09:59.599292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf0b81306a8f"
down_revision: str | Sequence[str] | None = "4edacdc2f990"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_delivery_attempts",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_reference", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('email', 'whatsapp', 'sms', 'push')",
            name=op.f("ck_notification_delivery_attempts_valid_channel"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'delivered', 'failed', 'skipped')",
            name=op.f("ck_notification_delivery_attempts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_delivery_attempts_notification_id_notifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_delivery_attempts")),
    )
    op.create_index(
        "ix_notification_delivery_attempts_notification_id",
        "notification_delivery_attempts",
        ["notification_id"],
        unique=False,
    )
    # NOTE: autogenerate also proposed dropping/recreating
    # `fk_feedback_entries_converted_to_complaint_id_complaints` — the same
    # Phase 13 deferred-FK false positive documented in the Phase 14 and
    # Phase 15 job/integration migrations. Removed from this migration.
    op.add_column(
        "notifications",
        sa.Column("delivery_channels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE notification_delivery_attempts ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "delivery_channels")
    op.drop_index(
        "ix_notification_delivery_attempts_notification_id",
        table_name="notification_delivery_attempts",
    )
    op.drop_table("notification_delivery_attempts")
    # ### end Alembic commands ###
